version: 2
updates:
  - package-ecosystem: "github-actions"
    open-pull-requests-limit: 1
    directory: "/"
    schedule:
      interval: "daily"

  - package-ecosystem: "npm"
    open-pull-requests-limit: 1
    directory: "/"
    reviewers:
      - chronark
    schedule:
      interval: "daily"

  - package-ecosystem: "docker"
    open-pull-requests-limit: 1
    directory: "/"
    reviewers:
      - chronark
    schedule:
      interval: "daily"
