variables:   

  # Enabled:
  STAGING_ENABLED: 1
  CI_KUBERNETES_ACTIVE: 1

stages:
  - review
  - staging
  - production
  - cleanup


.auto-deploy:
  before_script:
    - set +e && chmod 600 $CI_PROJECT_DIR.tmp/KUBECONFIG && set -e
    - if [ -n "$KUBE_CONTEXT" ]; then kubectl config use-context "$KUBE_CONTEXT"; fi
    - chmod 400 $KUBECONFIG
  image: "registry.gitlab.com/gitlab-org/cluster-integration/auto-deploy-image:v2.48.0"
  dependencies: []



## Review job is deploying automatically on every push to "staging" branch
review:
  extends: .auto-deploy
  stage: review
  environment:
    name: review/$CI_COMMIT_REF_NAME
    # Bullboard URL
    url: https://$AUTO_DEVOPS_COMMON_NAME
    on_stop: stop_review
  script:
    - helm repo add azure-marketplace https://marketplace.azurecr.io/helm/v1/repo
    # Add a redis deployment with nodeport service, limit CPU and memory, set a password, set standard persistent storage 3 GB. Name: redis-schemabase-staging
    - helm upgrade --install -n $KUBE_NAMESPACE redis-schemabase-staging azure-marketplace/redis --set architecture="standalone" --set auth.password="$REDIS_PASSWORD" --set resources.requests.cpu=100m --set resources.requests.memory=128Mi --set resources.limits.cpu=200m --set resources.limits.memory=256Mi --set persistence.size=3Gi --set service.type=NodePort
    # Add a mysql deployment with 5 GB storage and nodeport service, limit CPU and memory, set a password, set standard persistent storage 3 GB. Name: mysql-schemabase-staging
    - helm upgrade --install -n $KUBE_NAMESPACE mysql-schemabase-staging azure-marketplace/mysql --set auth.database="schemabase" --set auth.username="schemabase" --set auth.password="$MYSQL_PASSWORD" --set resources.requests.cpu=100m --set resources.requests.memory=128Mi --set resources.limits.cpu=200m --set resources.limits.memory=256Mi --set persistence.size=5Gi --set service.type=NodePort

  rules:
    - if: '$CI_KUBERNETES_ACTIVE == null || $CI_KUBERNETES_ACTIVE == ""'
      when: never
    - if: "$REVIEW_DISABLED"
      when: never
    - if: "($CI_COMMIT_REF_PROTECTED == 'true' || $CI_COMMIT_TAG)"
      when: never
    - if: "$CI_COMMIT_REF_NAME == 'staging'"

## Review job is deploying automatically on every push to "prod" branch
production:
  extends: .auto-deploy
  stage: production
  script: 
    - helm repo add azure-marketplace https://marketplace.azurecr.io/helm/v1/repo
    # Add a redis deployment with nodeport service, limit CPU and memory, set a password, set standard persistent storage 3 GB. Name: redis-schemabase-production
    # Add a mysql deployment with nodeport service, limit CPU and memory, set a password, set standard persistent storage 30 GB. Name: mysql-schemabase-production
  environment:
    name: production
    # Bullboard URL
    url: ""
  rules:
    - if: '$CI_KUBERNETES_ACTIVE == null || $CI_KUBERNETES_ACTIVE == ""'
      when: never
    - if: '$CI_COMMIT_REF_NAME == "prod"' 

stop_review:
  extends: .auto-deploy
  stage: cleanup
  variables:
    GIT_STRATEGY: none
  script:
    - auto-deploy delete
  environment:
    name: review/$CI_COMMIT_REF_NAME
    action: stop
  allow_failure: true
  rules:
    - if: '$CI_KUBERNETES_ACTIVE == null || $CI_KUBERNETES_ACTIVE == ""'
      when: never
    - if: '$CI_COMMIT_BRANCH == "v1"'
      when: never
    - if: "$REVIEW_DISABLED"
      when: never
    - if: "$CI_COMMIT_TAG || $CI_COMMIT_BRANCH"
      when: manual


