# In ci we want to test against very specific version of saleor
# (namely the ones we have in production)
# This can be achieved by running the following command:
# $ export SALEOR_VERSION="XXX" docker-compose -f docker-compose.ci.yaml up

services:
  saleor_api:
    image: ${SALEOR_IMAGE}

  eci_api:
    depends_on:
      - kafka

  eci_worker:
    depends_on:
      - kafka
  zookeeper:
    image: docker.io/bitnami/zookeeper:3.7
    ports:
      - "2181:2181"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka:
    container_name: kafka
    image: docker.io/bitnami/kafka:3
    ports:
      - "9092:9092"
    environment:
      KAFKA_CFG_ZOOKEEPER_CONNECT: zookeeper:2181
      ALLOW_PLAINTEXT_LISTENER: "yes"
    depends_on:
      - zookeeper
