version: "3.9"

services:
  # Our own database where we store tenants and config
  eci_db:
    container_name: db.eci
    image: postgres
    ports:
      # Must be exposed on the host for prisma to migrate and seed
      - 5432:5432
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  # Nextjs Serverless application to receive api from various services
  eci_api:
    image: eci_api
    build:
      context: .
      dockerfile: ./services/api/Dockerfile

    container_name: api.eci
    ports:
      - 3000:3000
    environment:
      DATABASE_URL: ${DATABASE_URL}
      DATABASE_URL_POOL: ${DATABASE_URL_POOL}

      KAFKA_BROKER_URL: ${KAFKA_BROKER_URL}
      KAFKA_SASL_MECHANISM: ${KAFKA_SASL_MECHANISM}
      KAFKA_USERNAME: ${KAFKA_USERNAME}
      KAFKA_PASSWORD: ${KAFKA_PASSWORD}
      SIGNING_KEY: anything
      NODE_ENV: production
      ECI_BASE_URL: http://api.eci:3000
      ECI_ENV: development
      JWT_SIGNING_KEY: ${JWT_SIGNING_KEY}
    depends_on:
      - eci_db

  eci_worker:
    image: eci_worker
    container_name: worker.eci

    build:
      context: .
      dockerfile: ./services/worker/Dockerfile
      args:
        - commit_sha=development
    environment:
      DATABASE_URL: ${DATABASE_URL}
      DATABASE_URL_POOL: ${DATABASE_URL_POOL}

      KAFKA_BROKER_URL: ${KAFKA_BROKER_URL}
      KAFKA_SASL_MECHANISM: ${KAFKA_SASL_MECHANISM}
      KAFKA_USERNAME: ${KAFKA_USERNAME}
      KAFKA_PASSWORD: ${KAFKA_PASSWORD}
      SIGNING_KEY: anything
      NODE_ENV: production
      ECI_ENV: development
      ZOHO_ZCSRF_TOKEN: ${ZOHO_ZCSRF_TOKEN}
      ZOHO_COOKIES: ${ZOHO_COOKIES}
      SENDGRID_API_KEY: ${SENDGRID_API_KEY}

    depends_on:
      - eci_db

  saleor_api:
    image: registry.gitlab.com/trieb.work/saleor:3.0.0-b.13-triebwork1
    container_name: saleor.eci
    ports:
      - 8000:8000
    command: python manage.py runserver 0.0.0.0:8000

    environment:
      DATABASE_URL: postgres://saleor:saleor@saleor_db:5432/postgres
      SECRET_KEY: de068091c088ad706703ed50cdec8994e596936cda803a7c0a9df98b454b4860
      STOREFRONT_URL: http://storefront.saleor.api:4000/
      DASHBOARD_URL: http://dashboard.saleor.api:9000/
      ALLOWED_CLIENT_HOSTS: localhost,api.eci
      ALLOWED_HOSTS: saleor.eci,localhost
      ELASTIC_APM_ENABLED: "False"
    depends_on:
      - saleor_db

  # Required by saleor
  saleor_db:
    image: postgres
    environment:
      - POSTGRES_USER=saleor
      - POSTGRES_PASSWORD=saleor
    ports:
      - 15432:5432
