version: "3.9"

services:
  # Our own database where we store tenants and config
  eci_db:
    image: postgres
    ports:
      # Must be exposed on the host for prisma to migrate and seed
      - 5432:5432
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - eci_db:/var/lib/postgresql

  # Nextjs Serverless application to receive webhooks from various services
  eci_webhooks:
    image: eci_webhooks
    build:
      context: .
      dockerfile: ./apps/webhooks/Dockerfile
    container_name: webhooks.eci
    ports:
      - 3000:3000
    environment:
      DATABASE_URL: postgres://postgres:postgres@eci_db:5432/postgres
      DATABASE_URL_POOL: postgres://postgres:postgres@eci_db:5432/postgres
      REDIS_HOST: redis
      REDIS_PORT: 6379
      SIGNING_KEY: anything
      NODE_ENV: production
      ECI_BASE_URL: http://webhooks.eci:3000
      ECI_ENV: development
    depends_on:
      - eci_db
      - redis

  eci_worker:
    image: eci_worker

    build:
      context: .
      dockerfile: ./apps/worker/Dockerfile
      args:
        - commit_sha=development
    environment:
      DATABASE_URL: postgres://postgres:postgres@eci_db:5432/postgres
      DATABASE_URL_POOL: postgres://postgres:postgres@eci_db:5432/postgres
      REDIS_HOST: redis
      REDIS_PORT: 6379
      SIGNING_KEY: anything
      NODE_ENV: production
      ECI_ENV: development
    depends_on:
      - eci_db
      - redis

  # Saleor Graphql API
  saleor_api:
    image: ghcr.io/saleor/saleor:3.0.0-b.27
    container_name: saleor.eci

    ports:
      - 8000:8000
    command: python manage.py runserver 0.0.0.0:8000

    environment:
      DATABASE_URL: postgres://saleor:saleor@saleor_db:5432/postgres
      SECRET_KEY: adgkadgkajsdg
      STOREFRONT_URL: http://storefront.saleor.api:4000/
      DASHBOARD_URL: http://dashboard.saleor.api:9000/
      ALLOWED_CLIENT_HOSTS: localhost,webhooks.eci
      ALLOWED_HOSTS: saleor.eci,localhost
      DEBUG: "True"
    depends_on:
      - saleor_db

  # Required by saleor
  saleor_db:
    image: postgres
    environment:
      - POSTGRES_USER=saleor
      - POSTGRES_PASSWORD=saleor
    ports:
      - 15432:5432
    volumes:
      - saleor_db:/var/lib/postgresql

  redis:
    image: redis
    ports:
      - 6379:6379

volumes:
  eci_db:
  saleor_db:
