version: "3.9"

# This will apply in local development.
# In ci this file will be replaced by `docker-compose.ci.yml`

services:
  saleor_dashboard:
    container_name: dashboard.saleor.eci
    image: chronark/saleor-dashboard
    # build:
    #   context: https://github.com/mirumee/saleor-dashboard.git
    #   dockerfile: Dockerfile.dev
    ports:
      - 9000:9000
    command: npm start -- --host 0.0.0.0
    depends_on:
      - saleor_api
