version: "3.1"

services:
  # Our own database where we store tenants and config
  eci_db:
    image: postgres
    ports:
      # Must be exposed on the host for prisma to migrate and seed
      - 5432:5432
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_MULTIPLE_DATABASES=postgres

  # Nextjs Serverless application to receive webhooks from various services
  eci_webhooks:
    image: triebwork/eci-webhooks
    container_name: webhooks.eci
    build:
      context: .
      dockerfile: ./apps/webhooks/Dockerfile
    ports:
      - 3000:3000
    environment:
      DATABASE_URL: postgres://postgres:postgres@eci_db:5432/postgres
      DATABASE_URL_POOL: postgres://postgres:postgres@eci_db:5432/postgres
      CI:
      REDIS_HOST: redis
      REDIS_PORT: 6379
      SIGNING_KEY: anything
      NODE_ENV: production
      ECI_BASE_URL: http://webhooks.eci:3000

  eci_worker:
    image: triebwork/eci-worker
    build:
      context: .
      dockerfile: ./apps/worker/Dockerfile
    environment:
      DATABASE_URL: postgres://postgres:postgres@eci_db:5432/postgres
      DATABASE_URL_POOL: postgres://postgres:postgres@eci_db:5432/postgres
      CI:
      REDIS_HOST: redis
      REDIS_PORT: 6379
      SIGNING_KEY: anything
      NODE_ENV: production

  # Saleor Graphql API
  saleor_api:
    image: chronark/saleor
    build:
      context: ./vendor/saleor
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    depends_on:
      - saleor_db
    command: python manage.py runserver 0.0.0.0:8000

    environment:
      DATABASE_URL: postgres://saleor:saleor@saleor_db:5432/postgres
      SECRET_KEY: adgkadgkajsdg
      STOREFRONT_URL: http://localhost:4000/
      DASHBOARD_URL: http://localhost:9000/
      REDIS_URL: redis://redis:6379/0

  saleor_dashboard:
    image: chronark/saleor-dashboard
    build:
      context: ./vendor/saleor-dashboard
      dockerfile: Dockerfile.dev
    ports:
      - 9000:9000
    command: npm start -- --host 0.0.0.0

  # Required by saleor
  saleor_db:
    image: postgres
    environment:
      - POSTGRES_USER=saleor
      - POSTGRES_PASSWORD=saleor
    ports:
      - 15432:5432
    volumes:
      - saleor-db:/var/lib/postgresql/data

  redis:
    image: redis
    ports:
      - 6379:6379

  redis-commander:
    image: rediscommander/redis-commander
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - 8081:8081

volumes:
  # Migrating and seeding the db takes a long time so we "cache" it for local development
  saleor-db:
