version: "3.9"

# This will apply in local development.
# In ci this file will be replaced by `docker-compose.ci.yml`

services:
  saleor_dashboard:
    container_name: dashboard.saleor.eci
    build:
      context: https://github.com/saleor/saleor-dashboard.git#3.0
      dockerfile: Dockerfile
    ports:
      - 9000:80
    depends_on:
      - saleor_api

  kafka-ui:
    image: provectuslabs/kafka-ui
    container_name: kafka-ui

    ports:
      - "8080:8080"
    environment:
      - KAFKA_CLUSTERS_0_NAME=eci
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:9092
      # - KAFKA_CLUSTERS_0_PROPERTIES_SECURITY_PROTOCOL=SASL_SSL
      # - KAFKA_CLUSTERS_0_PROPERTIES_SASL_MECHANISM=SCRAM-SHA-256
      # - KAFKA_CLUSTERS_0_PROPERTIES_SASL_JAAS_CONFIG=org.apache.kafka.common.security.scram.ScramLoginModule required username="${KAFKA_USERNAME}" password="${KAFKA_PASSWORD}";
      # - KAFKA_CLUSTERS_0_PROPERTIES_PROTOCOL=SASL
