version: "3.1"

services:
  postgres:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  saleor:
    image: registry.gitlab.com/trieb.work/saleor:3.0-triebwork7
    environment:
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/postgres
      SECRET_KEY: adgkadgkajsdg
    # exec
    # python manage.py migrate
    # python manage.py populatedb --createsuperuser
    # email: admin@example.com, pw: admin
