/* eslint-disable max-len */
import { NoopLogger } from "@eci/pkg/logger";
import { PrismaClient } from "@eci/pkg/prisma";
import { beforeEach, describe, jest, test, beforeAll } from "@jest/globals";
import { SalesOrder, Zoho, ZohoApiClient } from "@trieb.work/zoho-ts";
import { ZohoSalesOrdersSyncService } from ".";

let zohoApp: any;

beforeEach(() => {
  jest.clearAllMocks();
});

describe("Zoho Inventory SalesOrders Sync", () => {
  const prismaClient = new PrismaClient();

  const zohoClient = undefined as unknown as ZohoApiClient;
  const mockedZohoClient = {
    salesOrder: {
      list: async () =>
        await Promise.resolve([
          {
            salesorder_id: "116240000001637008",
            zcrm_potential_id: "",
            zcrm_potential_name: "",
            customer_name: "Christina Lang",
            customer_id: "116240000000631001",
            email: "zinkljannik+chri@gmail.com",
            delivery_date: "",
            company_name: "",
            color_code: "",
            current_sub_status_id: "",
            current_sub_status: "confirmed",
            pickup_location_id: "",
            salesorder_number: "SO-00060",
            reference_number: "",
            date: "2022-08-23",
            shipment_date: "",
            shipment_days: "",
            due_by_days: "",
            due_in_days: "",
            currency_id: "116240000000000071",
            source: "Client",
            currency_code: "EUR",
            total: 2.68,
            bcy_total: 2.68,
            total_invoiced_amount: 0.0,
            created_time: "2022-08-23T17:18:39+0200",
            last_modified_time: "2022-08-23T17:18:41+0200",
            is_emailed: false,
            quantity: 1.0,
            quantity_invoiced: 0.0,
            quantity_packed: 0.0,
            quantity_shipped: 0.0,
            order_status: "confirmed",
            invoiced_status: "not_invoiced",
            paid_status: "unpaid",
            shipped_status: "pending",
            status: "confirmed",
            is_drop_shipment: false,
            is_backorder: false,
            is_manually_fulfilled: false,
            sales_channel: "direct_sales",
            sales_channel_formatted: "Direct Sales",
            salesperson_name: "",
            has_attachment: false,
            cf_ready_to_fulfill: "false",
            cf_ready_to_fulfill_unformatted: false,
            cf_language: "en",
            cf_language_unformatted: "en",
            balance: 2.68,
            delivery_method: "",
            delivery_method_id: "",
          },
          {
            salesorder_id: "116240000001580015",
            zcrm_potential_id: "",
            zcrm_potential_name: "",
            customer_name: "Jannik Zinkl",
            customer_id: "116240000001504002",
            email: "zinkljannik@gmail.com",
            delivery_date: "",
            company_name: "",
            color_code: "",
            current_sub_status_id: "",
            current_sub_status: "draft",
            pickup_location_id: "",
            salesorder_number: "SO-00059",
            reference_number: "",
            date: "2022-06-07",
            shipment_date: "",
            shipment_days: "",
            due_by_days: "",
            due_in_days: "",
            currency_id: "116240000000000071",
            source: "Client",
            currency_code: "EUR",
            total: 19.62,
            bcy_total: 19.62,
            total_invoiced_amount: 0.0,
            created_time: "2022-06-07T14:16:42+0200",
            last_modified_time: "2022-06-07T14:16:42+0200",
            is_emailed: false,
            quantity: 2.0,
            quantity_invoiced: 0.0,
            quantity_packed: 0.0,
            quantity_shipped: 0.0,
            order_status: "draft",
            invoiced_status: "",
            paid_status: "",
            shipped_status: "",
            status: "draft",
            is_drop_shipment: false,
            is_backorder: false,
            is_manually_fulfilled: false,
            sales_channel: "direct_sales",
            sales_channel_formatted: "Direct Sales",
            salesperson_name: "",
            has_attachment: false,
            cf_ready_to_fulfill: "false",
            cf_ready_to_fulfill_unformatted: false,
            cf_language: "en",
            cf_language_unformatted: "en",
            balance: 19.62,
            delivery_method: "",
            delivery_method_id: "",
          },
          {
            salesorder_id: "116240000001532575",
            zcrm_potential_id: "",
            zcrm_potential_name: "",
            customer_name: "Christina Lang",
            customer_id: "116240000000631001",
            email: "zinkljannik+chri@gmail.com",
            delivery_date: "",
            company_name: "",
            color_code: "",
            current_sub_status_id: "",
            current_sub_status: "confirmed",
            pickup_location_id: "",
            salesorder_number: "SO-00057",
            reference_number: "",
            date: "2022-05-12",
            shipment_date: "",
            shipment_days: "",
            due_by_days: "",
            due_in_days: "",
            currency_id: "116240000000000071",
            source: "Client",
            currency_code: "EUR",
            total: 1.07,
            bcy_total: 1.07,
            total_invoiced_amount: 0.0,
            created_time: "2022-05-12T17:44:41+0200",
            last_modified_time: "2022-07-21T14:13:49+0200",
            is_emailed: false,
            quantity: 2.0,
            quantity_invoiced: 0.0,
            quantity_packed: 0.0,
            quantity_shipped: 0.0,
            order_status: "confirmed",
            invoiced_status: "not_invoiced",
            paid_status: "unpaid",
            shipped_status: "pending",
            status: "confirmed",
            is_drop_shipment: false,
            is_backorder: false,
            is_manually_fulfilled: false,
            sales_channel: "direct_sales",
            sales_channel_formatted: "Direct Sales",
            salesperson_name: "",
            has_attachment: false,
            cf_ready_to_fulfill: "false",
            cf_ready_to_fulfill_unformatted: false,
            cf_language: "en",
            cf_language_unformatted: "en",
            balance: 0.0,
            delivery_method: "",
            delivery_method_id: "",
          },
          {
            salesorder_id: "116240000001504271",
            zcrm_potential_id: "",
            zcrm_potential_name: "",
            customer_name: "Jannik Zinkl",
            customer_id: "116240000001504002",
            email: "zinkljannik@gmail.com",
            delivery_date: "",
            company_name: "",
            color_code: "",
            current_sub_status_id: "",
            current_sub_status: "confirmed",
            pickup_location_id: "",
            salesorder_number: "STORE-1992",
            reference_number: "T3JkZXI6MTk5Mg==",
            date: "2022-04-20",
            shipment_date: "",
            shipment_days: "",
            due_by_days: "",
            due_in_days: "",
            currency_id: "116240000000000071",
            source: "Api",
            currency_code: "EUR",
            total: 12.21,
            bcy_total: 12.21,
            total_invoiced_amount: 12.21,
            created_time: "2022-04-20T11:08:15+0200",
            last_modified_time: "2022-05-12T11:27:11+0200",
            is_emailed: false,
            quantity: 1.0,
            quantity_invoiced: 1.0,
            quantity_packed: 0.0,
            quantity_shipped: 0.0,
            order_status: "confirmed",
            invoiced_status: "invoiced",
            paid_status: "paid",
            shipped_status: "pending",
            status: "confirmed",
            is_drop_shipment: false,
            is_backorder: false,
            is_manually_fulfilled: false,
            sales_channel: "direct_sales",
            sales_channel_formatted: "Direct Sales",
            salesperson_name: "",
            has_attachment: false,
            cf_ready_to_fulfill: "true",
            cf_ready_to_fulfill_unformatted: true,
            cf_language: "en",
            cf_language_unformatted: "en",
            balance: 12.21,
            delivery_method: "DPD Germany",
            delivery_method_id: "116240000000037235",
          },
          {
            salesorder_id: "116240000001500001",
            zcrm_potential_id: "",
            zcrm_potential_name: "",
            customer_name: "Linda Thomas",
            customer_id: "116240000001499002",
            email: "megan.chang@example.com",
            delivery_date: "",
            company_name: "",
            color_code: "",
            current_sub_status_id: "",
            current_sub_status: "confirmed",
            pickup_location_id: "",
            salesorder_number: "STORE-1990",
            reference_number: "T3JkZXI6MTk5MA==",
            date: "2022-04-19",
            shipment_date: "",
            shipment_days: "",
            due_by_days: "",
            due_in_days: "",
            currency_id: "116240000000000071",
            source: "Api",
            currency_code: "EUR",
            total: 20.21,
            bcy_total: 20.21,
            total_invoiced_amount: 0.0,
            created_time: "2022-04-19T16:16:21+0200",
            last_modified_time: "2022-06-24T20:03:21+0200",
            is_emailed: false,
            quantity: 2.0,
            quantity_invoiced: 0.0,
            quantity_packed: 0.0,
            quantity_shipped: 0.0,
            order_status: "confirmed",
            invoiced_status: "not_invoiced",
            paid_status: "unpaid",
            shipped_status: "pending",
            status: "confirmed",
            is_drop_shipment: false,
            is_backorder: false,
            is_manually_fulfilled: false,
            sales_channel: "direct_sales",
            sales_channel_formatted: "Direct Sales",
            salesperson_name: "",
            has_attachment: false,
            cf_ready_to_fulfill: "true",
            cf_ready_to_fulfill_unformatted: true,
            cf_language: "en",
            cf_language_unformatted: "en",
            balance: 20.21,
            delivery_method: "DPD Germany",
            delivery_method_id: "116240000000037235",
          },
        ]),
      get: async (salesorderid: string) => {
        const mapping: { [key: string]: SalesOrder } = {
          "98644000012567298": {
            salesorder_id: "98644000012567298",
            documents: [],
            zcrm_potential_id: "",
            zcrm_potential_name: "",
            salesorder_number: "STORE-3139",
            date: "2022-05-12",
            offline_created_date_with_time: "",
            tracking_url: "",
            has_discount: false,
            status: "fulfilled",
            color_code: "",
            current_sub_status_id: "",
            current_sub_status: "closed",
            sub_statuses: [],
            shipment_date: "",
            reference_number: "T3JkZXI6MzEzOQ==",
            customer_id: "98644000003798974",
            customer_name: "Goerke Impulse",
            contact_persons: ["98644000003798976"],
            contact_person_details: [
              {
                phone: "",
                mobile: "",
                last_name: "Goerke",
                contact_person_id: "98644000003798976",
                first_name: "Andre",
                email: "andre@goerke-Impulse.de",
              },
            ],
            source: "Api",
            contact_category: "",
            currency_id: "98644000000000071",
            currency_code: "EUR",
            currency_symbol: "€",
            exchange_rate: 1.0,
            is_discount_before_tax: true,
            discount_type: "entity_level",
            delivery_method: "DPD Germany",
            is_inclusive_tax: true,
            tax_rounding: "item_level",
            order_status: "closed",
            invoiced_status: "invoiced",
            paid_status: "paid",
            shipped_status: "fulfilled",
            sales_channel: "direct_sales",
            sales_channel_formatted: "Direktverkauf",
            account_identifier: "",
            integration_id: "",
            is_dropshipped: false,
            is_backordered: false,
            is_manually_fulfilled: false,
            can_manually_fulfill: false,
            has_qty_cancelled: false,
            shipping_details: {},
            created_by_email: "jannik@trieb.work",
            total_quantity: 2.0,
            line_items: [
              {
                line_item_id: "98644000012567303",
                variant_id: "98644000002082003",
                item_id: "98644000002082003",
                product_id: "98644000002082003",
                attribute_name1: "",
                attribute_name2: "",
                attribute_name3: "",
                attribute_option_name1: "",
                attribute_option_name2: "",
                attribute_option_name3: "",
                attribute_option_data1: "",
                attribute_option_data2: "",
                attribute_option_data3: "",
                is_combo_product: false,
                warehouse_id: "98644000000108128",
                warehouse_name: "GIGATEC GmbH",
                sku: "granola-1701-fruehsportfreunde",
                name: 'BIO Hafer-Granola mit Früchten "Frühsportfreunde"',
                group_name: 'BIO Granola Himbeere "Frühsportfreunde"',
                description: "",
                item_order: 2,
                bcy_rate: 6.72,
                rate: 6.72,
                quantity: 1.0,
                quantity_manuallyfulfilled: 0.0,
                unit: "Stück",
                pricebook_id: "",
                header_id: "",
                header_name: "",
                discount: 0.0,
                discounts: [],
                tax_id: "98644000003254506",
                tax_name: "USt. reduziert",
                tax_type: "tax",
                tax_percentage: 7,
                item_total: 6.28,
                item_sub_total: 6.28,
                item_total_inclusive_of_tax: 6.72,
                product_type: "goods",
                line_item_type: "goods",
                item_type: "inventory",
                is_invoiced: true,
                is_unconfirmed_product: false,
                tags: [],
                image_name: "heyho_granola_glas_Frühsportfreunde.jpg",
                image_type: "jpg",
                image_document_id: "98644000002158251",
                document_id: "98644000002158251",
                item_custom_fields: [
                  {
                    field_id: "98644000002082020",
                    customfield_id: "98644000002082020",

                    show_in_portal: false,

                    index: 1,
                    label: "Öko-Kontrollstelle",
                    show_on_pdf: false,
                    edit_on_portal: false,
                    edit_on_store: false,
                    api_name: "cf_ko_kontrollstelle",
                    show_in_all_pdf: false,
                    value_formatted: "DE-ÖKO-007",
                    search_entity: "item",
                    data_type: "string",
                    placeholder: "cf_ko_kontrollstelle",
                    value: "DE-ÖKO-007",
                    is_dependent_field: false,
                  },
                ],
                quantity_invoiced: 1.0,
                quantity_packed: 1.0,
                quantity_shipped: 1.0,
                quantity_backordered: 0,
                quantity_dropshipped: 0.0,
                quantity_cancelled: 0.0,
                package_details: {
                  length: "",
                  width: "",
                  height: "",
                  weight: "",
                  weight_unit: "kg",
                  dimension_unit: "cm",
                },
                quantity_invoiced_cancelled: 0.0,
                quantity_returned: 0.0,
              },
              {
                line_item_id: "98644000012567305",
                variant_id: "98644000002131324",
                item_id: "98644000002131324",
                product_id: "98644000002131324",
                attribute_name1: "",
                attribute_name2: "",
                attribute_name3: "",
                attribute_option_name1: "",
                attribute_option_name2: "",
                attribute_option_name3: "",
                attribute_option_data1: "",
                attribute_option_data2: "",
                attribute_option_data3: "",
                is_combo_product: false,
                warehouse_id: "98644000000108128",
                warehouse_name: "GIGATEC GmbH",
                sku: "granola-2010-peanutpower",
                name: 'BIO Hafer-Granola mit Erdnüssen "Peanut Power"',
                group_name: 'BIO Granola Erdnuss "Peanut Power"',
                description: "",
                item_order: 3,
                bcy_rate: 6.72,
                rate: 6.72,
                quantity: 1.0,
                quantity_manuallyfulfilled: 0.0,
                unit: "Stück",
                pricebook_id: "",
                header_id: "",
                header_name: "",
                discount: 0.0,
                discounts: [],
                tax_id: "98644000003254506",
                tax_name: "USt. reduziert",
                tax_type: "tax",
                tax_percentage: 7,
                item_total: 6.28,
                item_sub_total: 6.28,
                item_total_inclusive_of_tax: 6.72,
                product_type: "goods",
                line_item_type: "goods",
                item_type: "inventory",
                is_invoiced: true,
                is_unconfirmed_product: false,
                tags: [],
                image_name: "heyho_granola_glas_PeanutPower.jpg",
                image_type: "jpg",
                image_document_id: "98644000002158245",
                document_id: "98644000002158245",
                item_custom_fields: [
                  {
                    field_id: "98644000002082020",
                    customfield_id: "98644000002082020",

                    show_in_portal: false,

                    index: 1,
                    label: "Öko-Kontrollstelle",
                    show_on_pdf: false,
                    edit_on_portal: false,
                    edit_on_store: false,
                    api_name: "cf_ko_kontrollstelle",
                    show_in_all_pdf: false,
                    value_formatted: "DE-ÖKO-007",
                    search_entity: "item",
                    data_type: "string",
                    placeholder: "cf_ko_kontrollstelle",
                    value: "DE-ÖKO-007",
                    is_dependent_field: false,
                  },
                ],
                quantity_invoiced: 1.0,
                quantity_packed: 1.0,
                quantity_shipped: 1.0,
                quantity_backordered: 0,
                quantity_dropshipped: 0.0,
                quantity_cancelled: 0.0,
                package_details: {
                  length: "",
                  width: "",
                  height: "",
                  weight: 0.29,
                  weight_unit: "kg",
                  dimension_unit: "cm",
                },
                quantity_invoiced_cancelled: 0.0,
                quantity_returned: 0.0,
              },
            ],
            submitter_id: "",
            approver_id: "",
            submitted_date: "",
            submitted_by: "",
            price_precision: 2,
            is_emailed: false,
            has_unconfirmed_line_item: false,
            picklists: [],
            purchaseorders: [],
            warehouses: [
              {
                warehouse_id: "98644000000108128",
                warehouse_name: "GIGATEC GmbH",
                address: "Siegelsdorfer Str. 30",
                city: "Fürth",
                state: "",
                country: "Germany",
                zip: "90768",
                phone: "",
                email: "",
                is_primary: true,
                status: "active",
                sales_channels: [],
              },
              {
                warehouse_id: "98644000003868314",
                warehouse_name: "trieb.work",
                address: "",
                city: "",
                state: "",
                country: "Germany",
                zip: "",
                phone: "",
                email: "",
                is_primary: false,
                status: "active",
                sales_channels: [],
              },
            ],
            billing_address_id: "98644000006355002",
            billing_address: {
              address: "Goerke Impulse, Hofstraße 1",
              street2: "",
              city: "WETTER RUHR",
              state: "",
              zip: "58300",
              country: "Deutschland",
              country_code: "DE",
              state_code: "",
              fax: "",
              phone: "",
              attention: "Andre Goerke",
            },
            shipping_address_id: "98644000012566462",
            shipping_address: {
              address: "Berliner Straße 11",
              street2: "FGR GmbH",
              city: "HAGEN",
              state: "",
              zip: "58135",
              country: "Deutschland",
              country_code: "DE",
              state_code: "",
              fax: "",
              phone: "",
              attention: "Jörg Kluth",
            },
            is_test_order: false,
            notes: "",
            terms: "",
            payment_terms: "",
            payment_terms_label: "",
            custom_fields: [
              {
                field_id: "98644000000161049",
                customfield_id: "98644000000161049",
                show_in_portal: false,
                index: 1,
                label: "Ready to fulfill",
                show_on_pdf: false,
                edit_on_portal: false,
                edit_on_store: false,
                api_name: "cf_ready_to_fulfill",
                show_in_all_pdf: false,
                value_formatted: "false",
                search_entity: "salesorder",
                data_type: "check_box",
                placeholder: "cf_ready_to_fulfill",
                value: false,
                is_dependent_field: false,
              },
              {
                field_id: "98644000000971306",
                customfield_id: "98644000000971306",
                show_in_portal: false,
                index: 2,
                label: "Anmerkung",
                show_on_pdf: false,
                edit_on_portal: false,
                edit_on_store: false,
                api_name: "cf_anmerkung",
                show_in_all_pdf: false,
                value_formatted:
                  "Vielen Dank Herr Kluth für Ihre Zeit und die wertvollen Impulse. Gruß Andre Goerke",
                search_entity: "salesorder",
                data_type: "string",
                placeholder: "cf_anmerkung",
                value:
                  "Vielen Dank Herr Kluth für Ihre Zeit und die wertvollen Impulse. Gruß Andre Goerke",
                is_dependent_field: false,
              },
              {
                field_id: "98644000005854934",
                customfield_id: "98644000005854934",
                show_in_portal: false,
                index: 3,
                label: "preferred-language",
                show_on_pdf: false,
                edit_on_portal: false,
                edit_on_store: false,
                api_name: "cf_preferred_language",
                show_in_all_pdf: false,
                selected_option_id: "98644000005854936",
                value_formatted: "de",
                search_entity: "salesorder",
                data_type: "dropdown",
                placeholder: "cf_preferred_language",
                value: "de",
                is_dependent_field: false,
              },
            ],
            custom_field_hash: {
              cf_ready_to_fulfill: "false",
              cf_ready_to_fulfill_unformatted: false,
              cf_anmerkung:
                "Vielen Dank Herr Kluth für Ihre Zeit und die wertvollen Impulse. Gruß Andre Goerke",
              cf_anmerkung_unformatted:
                "Vielen Dank Herr Kluth für Ihre Zeit und die wertvollen Impulse. Gruß Andre Goerke",
              cf_preferred_language: "de",
              cf_preferred_language_unformatted: "de",
            },
            template_id: "98644000000000111",
            template_name: "Standard Template",
            page_width: "8.27in",
            page_height: "11.69in",
            orientation: "portrait",
            template_type: "standard",
            created_time: "2022-05-12T22:38:04+0200",
            last_modified_time: "2022-05-18T12:54:27+0200",
            created_by_id: "98644000000032001",
            created_date: "2022-05-12",
            last_modified_by_id: "",
            attachment_name: "",
            can_send_in_mail: false,
            salesperson_id: "",
            salesperson_name: "",
            merchant_id: "",
            merchant_name: "",
            pickup_location_id: "",
            discount_amount: 0.0,
            discount: 0.0,
            discount_applied_on_amount: 0.0,
            is_adv_tracking_in_package: false,
            shipping_charges: {
              description: "Versandkosten",
              bcy_rate: 5.9,
              rate: 5.9,
              tax_id: "98644000003254506",
              tax_name: "USt. reduziert",
              tax_type: "tax",
              tax_percentage: 7,
              tax_total_fcy: 0.39,
              item_total: 5.51,
            },
            shipping_charge_tax_id: "98644000003254506",
            shipping_charge_tax_name: "USt. reduziert (7%)",
            shipping_charge_tax_type: "tax",
            shipping_charge_tax_percentage: 7.0,
            shipping_charge_tax: 0.39,
            bcy_shipping_charge_tax: 0.39,
            shipping_charge_exclusive_of_tax: 5.51,
            shipping_charge_inclusive_of_tax: 5.9,
            shipping_charge_tax_formatted: "€0,39",
            bcy_shipping_charge_tax_formatted: "€0,39",
            shipping_charge_exclusive_of_tax_formatted: "€5,51",
            shipping_charge_inclusive_of_tax_formatted: "€5,90",
            shipping_charge: 5.9,
            bcy_shipping_charge: 5.9,
            adjustment: 0.0,
            bcy_adjustment: 0.0,
            adjustment_description: "",
            roundoff_value: 0.0,
            transaction_rounding_type: "no_rounding",
            sub_total: 12.56,
            bcy_sub_total: 12.56,
            sub_total_inclusive_of_tax: 0.0,
            sub_total_exclusive_of_discount: 12.56,
            discount_total: 0.0,
            bcy_discount_total: 0.0,
            discount_percent: 0.0,
            tax_total: 1.27,
            bcy_tax_total: 1.27,
            total: 19.34,
            bcy_total: 19.34,
            taxes: [
              {
                tax_name: "USt. reduziert (7%)",
                tax_amount: 1.27,
              },
            ],
            packages: [
              {
                package_id: "98644000012853277",
                package_number: "PKG-04682",
                date: "2022-05-16",
                status: "delivered",
                detailed_status: "delivered",
                status_message: "",
                shipment_id: "98644000012853306",
                shipment_number: "SHP-04653",
                shipment_status: "3",
                carrier: "DPD",
                service: "DPDCLASSIC",
                tracking_number: "01906000684097",
                shipment_date: "2022-05-16",
                delivery_days: "",
                delivery_guarantee: false,
                delivery_method: "DPD",
                quantity: 1,
                is_tracking_enabled: false,
                shipment_order: {
                  shipment_id: "98644000012853306",
                  shipment_number: "SHP-04653",
                  shipment_date: "2022-05-16",
                  shipment_date_with_time: "2022-05-16 00:00",
                  tracking_number: "01906000684097",
                  delivery_date: "2022-05-18",
                  delivery_date_with_time: "2022-05-18 11:12",
                  shipment_type: "single_piece_shipment",
                  associated_packages_count: 1,
                  carrier: "DPD",
                  service: "DPDCLASSIC",
                  delivery_days: "",
                  delivery_guarantee: false,
                  tracking_url: "",
                  is_carrier_shipment: true,
                },
              },
            ],
            so_cycle_preference: {
              is_feature_enabled: false,
              socycle_status: "not_triggered",
              can_create_invoice: false,
              can_create_package: false,
              can_create_shipment: false,
              shipment_preference: {
                default_carrier: "",
                send_notification: false,
                deliver_shipments: false,
              },
            },
            invoices: [
              {
                invoice_id: "98644000012566488",
                invoice_number: "INV-003055",
                reference_number: "STORE-3139",
                status: "paid",
                date: "2022-05-12",
                due_date: "2022-05-12",
                total: 19.34,
                balance: 0.0,
              },
            ],
            salesreturns: [],
            payments: [
              {
                payment_id: "98644000012566562",
                payment_mode: "onlinepayment",
                payment_mode_id: "",
                amount: 19.34,
                date: "2022-05-12",
                offline_created_date_with_time: "",
                description: "",
                reference_number: "",
                account_id: "98644000002101083",
                account_name: "Braintree Pfeffer & Frost",
                payment_type: "Kundenrechnungszahlungen",
              },
            ],
            creditnotes: [],
            refunds: [],
            balance: 19.34,
            approvers_list: [],
          },
          "98644000005009739": {
            salesorder_id: "98644000005009739",
            documents: [],
            zcrm_potential_id: "",
            zcrm_potential_name: "",
            salesorder_number: "SO-00451",
            date: "2021-12-17",
            offline_created_date_with_time: "",
            tracking_url: "",
            has_discount: false,
            status: "fulfilled",
            color_code: "",
            current_sub_status_id: "",
            current_sub_status: "closed",
            sub_statuses: [],
            shipment_date: "",
            reference_number: "",
            customer_id: "98644000003917351",
            customer_name: "herzla - Laden",
            contact_persons: ["98644000003917353"],
            contact_person_details: [
              {
                phone: "",
                mobile: "015114264964",
                last_name: "Siegel",
                contact_person_id: "98644000003917353",
                first_name: "Tabea",
                email: "tabeasiegel@googlemail.com",
              },
            ],
            source: "Client",
            shipping_charges: {
              description: "Versandkosten",
              bcy_rate: 2.75,
              rate: 2.75,
              tax_id: "98644000003254506",
              tax_name: "USt. reduziert",
              tax_type: "tax",
              tax_percentage: 7,
              tax_total_fcy: 0.19,
              item_total: 2.75,
            },
            contact_category: "",
            currency_id: "98644000000000071",
            currency_code: "EUR",
            currency_symbol: "€",
            exchange_rate: 1.0,
            is_discount_before_tax: true,
            discount_type: "entity_level",
            estimate_id: "",
            delivery_method: "Abholung",
            delivery_method_id: "98644000000181065",
            is_inclusive_tax: false,
            tax_rounding: "entity_level",
            order_status: "closed",
            invoiced_status: "invoiced",
            paid_status: "paid",
            shipped_status: "fulfilled",
            sales_channel: "direct_sales",
            sales_channel_formatted: "Direktverkauf",
            account_identifier: "",
            integration_id: "",
            is_dropshipped: false,
            is_backordered: false,
            is_manually_fulfilled: false,
            can_manually_fulfill: false,
            has_qty_cancelled: false,
            shipping_details: {},
            created_by_email: "jannik@trieb.work",
            total_quantity: 15.0,
            line_items: [
              {
                line_item_id: "98644000005009744",
                variant_id: "98644000002985861",
                track_batch_number: false,
                item_id: "98644000002985861",
                is_returnable: true,
                product_id: "98644000002985861",
                attribute_name1: "",
                attribute_name2: "",
                attribute_name3: "",
                attribute_option_name1: "",
                attribute_option_name2: "",
                attribute_option_name3: "",
                attribute_option_data1: "",
                attribute_option_data2: "",
                attribute_option_data3: "",
                is_combo_product: true,
                warehouse_id: "98644000000108128",
                warehouse_name: "GIGATEC GmbH",
                sku: "pf-dose-5-bio-ms-gemischt",
                name: "Dose - Maya Stepien - Gemischt BIO VEGAN",
                group_name: "Dose - Maya Stepien - Gemischt BIO VEGAN",
                description: "HS tariff no. / Zolltarif Nr.: 19052030",
                item_order: 0,
                bcy_rate: 15.9,
                rate: 15.9,
                quantity: 5.0,
                quantity_manuallyfulfilled: 0.0,
                unit: "Stück",
                pricebook_id: "",
                header_id: "",
                header_name: "",
                discount: 0.0,
                discounts: [],
                tax_id: "98644000003254506",
                tax_name: "USt. reduziert",
                tax_type: "tax",
                tax_percentage: 7,
                item_total: 79.5,
                item_sub_total: 79.5,
                product_type: "goods",
                line_item_type: "goods",
                item_type: "inventory",
                is_invoiced: true,
                is_unconfirmed_product: false,
                tags: [],
                image_name: "MayaStepien_BIO.jpg",
                image_type: "jpg",
                image_document_id: "98644000003392175",
                document_id: "98644000003392175",
                item_custom_fields: [
                  {
                    field_id: "98644000002082020",
                    customfield_id: "98644000002082020",
                    show_in_store: false,
                    show_in_portal: false,
                    is_active: true,
                    index: 1,
                    label: "Öko-Kontrollstelle",
                    show_on_pdf: false,
                    edit_on_portal: false,
                    edit_on_store: false,
                    api_name: "cf_ko_kontrollstelle",
                    show_in_all_pdf: false,
                    value_formatted: "DE-ÖKO-003",
                    search_entity: "item",
                    data_type: "string",
                    placeholder: "cf_ko_kontrollstelle",
                    value: "DE-ÖKO-003",
                    is_dependent_field: false,
                  },
                ],
                quantity_invoiced: 5.0,
                quantity_packed: 5.0,
                quantity_shipped: 5.0,
                quantity_backordered: 0,
                quantity_dropshipped: 0.0,
                quantity_cancelled: 0.0,
                package_details: {
                  length: "",
                  width: "",
                  height: "",
                  weight: 0.5,
                  weight_unit: "kg",
                  dimension_unit: "cm",
                },
                quantity_invoiced_cancelled: 0.0,
                quantity_returned: 0.0,
              },
              {
                line_item_id: "98644000005009748",
                variant_id: "98644000000108356",
                track_batch_number: false,
                item_id: "98644000000108356",
                is_returnable: true,
                product_id: "98644000000108356",
                attribute_name1: "",
                attribute_name2: "",
                attribute_name3: "",
                attribute_option_name1: "",
                attribute_option_name2: "",
                attribute_option_name3: "",
                attribute_option_data1: "",
                attribute_option_data2: "",
                attribute_option_data3: "",
                is_combo_product: true,
                warehouse_id: "98644000000108128",
                warehouse_name: "GIGATEC GmbH",
                sku: "pf-dose-5-cj-gemischt",
                name: "Dose - Cachetejack - Gemischt",
                group_name: "Dose - Cachetejack - Gemischt",
                description:
                  "Wer verdreht Dir zu Weihnachten den Kopf? Es sind die sagenhaften Sorten in unserer bunten Dose! Das traumhaft illustrierte Bergpanorama vom spanischen Illustratoren-Duo Cachetejack erinnert uns an Alpen-Urlaub im Indian Summer: Wanderfans treffen Murmeltiere auf dem weißen Zuckerguss-Gipfel oder Relaxen bei einer Runde Goat-Yoga.\nHS tariff no. / Zolltarif Nr.: 19052030",
                item_order: 1,
                bcy_rate: 15.0,
                rate: 15.0,
                quantity: 5.0,
                quantity_manuallyfulfilled: 0.0,
                unit: "Stück",
                pricebook_id: "",
                header_id: "",
                header_name: "",
                discount: 0.0,
                discounts: [],
                tax_id: "98644000003254506",
                tax_name: "USt. reduziert",
                tax_type: "tax",
                tax_percentage: 7,
                item_total: 75.0,
                item_sub_total: 75.0,
                product_type: "goods",
                line_item_type: "goods",
                item_type: "inventory",
                is_invoiced: true,
                is_unconfirmed_product: false,
                tags: [],
                image_name: "pundf_cachetejack_gemischt Kopie.jpg",
                image_type: "jpg",
                image_document_id: "98644000000633047",
                document_id: "98644000000633047",
                item_custom_fields: [],
                quantity_invoiced: 5.0,
                quantity_packed: 5.0,
                quantity_shipped: 5.0,
                quantity_backordered: 0,
                quantity_dropshipped: 0.0,
                quantity_cancelled: 0.0,
                package_details: {
                  length: 12.0,
                  width: 12.0,
                  height: 15.0,
                  weight: 0.5,
                  weight_unit: "kg",
                  dimension_unit: "cm",
                },
                quantity_invoiced_cancelled: 0.0,
                quantity_returned: 0.0,
              },
              {
                line_item_id: "98644000005009746",
                variant_id: "98644000002743070",
                track_batch_number: false,
                item_id: "98644000002743070",
                is_returnable: true,
                product_id: "98644000002743070",
                attribute_name1: "",
                attribute_name2: "",
                attribute_name3: "",
                attribute_option_name1: "",
                attribute_option_name2: "",
                attribute_option_name3: "",
                attribute_option_data1: "",
                attribute_option_data2: "",
                attribute_option_data3: "",
                is_combo_product: true,
                warehouse_id: "98644000000108128",
                warehouse_name: "GIGATEC GmbH",
                sku: "pf-brief-natur",
                name: "Bio Lebkuchenbrief vegan natur",
                group_name: "Bio Lebkuchenbrief vegan natur",
                description: "HS tariff no. / Zolltarif Nr.: 19052030",
                item_order: 2,
                bcy_rate: 4.9,
                rate: 4.9,
                quantity: 5.0,
                quantity_manuallyfulfilled: 0.0,
                unit: "Stück",
                pricebook_id: "",
                header_id: "",
                header_name: "",
                discount: 0.0,
                discounts: [],
                tax_id: "98644000003254506",
                tax_name: "USt. reduziert",
                tax_type: "tax",
                tax_percentage: 7,
                item_total: 24.5,
                item_sub_total: 24.5,
                product_type: "goods",
                line_item_type: "goods",
                item_type: "inventory",
                is_invoiced: true,
                is_unconfirmed_product: false,
                tags: [],
                image_name:
                  "pfefferundfrost_lebkuchenbrief_natur_vegan_n_de.jpeg",
                image_type: "jpeg",
                image_document_id: "98644000003235288",
                document_id: "98644000003235288",
                item_custom_fields: [
                  {
                    field_id: "98644000002082020",
                    customfield_id: "98644000002082020",
                    show_in_store: false,
                    show_in_portal: false,
                    is_active: true,
                    index: 1,
                    label: "Öko-Kontrollstelle",
                    show_on_pdf: false,
                    edit_on_portal: false,
                    edit_on_store: false,
                    api_name: "cf_ko_kontrollstelle",
                    show_in_all_pdf: false,
                    value_formatted: "DE-ÖKO-003",
                    search_entity: "item",
                    data_type: "string",
                    placeholder: "cf_ko_kontrollstelle",
                    value: "DE-ÖKO-003",
                    is_dependent_field: false,
                  },
                ],
                quantity_invoiced: 5.0,
                quantity_packed: 5.0,
                quantity_shipped: 5.0,
                quantity_backordered: 0,
                quantity_dropshipped: 0.0,
                quantity_cancelled: 0.0,
                package_details: {
                  length: "",
                  width: "",
                  height: "",
                  weight: 0.1,
                  weight_unit: "kg",
                  dimension_unit: "cm",
                },
                quantity_invoiced_cancelled: 0.0,
                quantity_returned: 0.0,
              },
            ],
            submitter_id: "",
            approver_id: "",
            submitted_date: "",
            submitted_by: "",
            price_precision: 2,
            is_emailed: false,
            has_unconfirmed_line_item: false,
            picklists: [],
            purchaseorders: [],
            warehouses: [
              {
                warehouse_id: "98644000000108128",
                warehouse_name: "GIGATEC GmbH",
                address: "Siegelsdorfer Str. 30",
                city: "Fürth",
                state: "",
                country: "Germany",
                zip: "90768",
                phone: "",
                email: "",
                is_primary: true,
                status: "active",
                sales_channels: [],
              },
              {
                warehouse_id: "98644000003868314",
                warehouse_name: "Pfeffer & Frost GmbH",
                address: "Karl-Grillenberger-Straße 1",
                city: "Nürnberg",
                state: "",
                country: "Germany",
                zip: "90402",
                phone: "",
                email: "",
                is_primary: false,
                status: "active",
                sales_channels: [],
              },
              {
                warehouse_id: "98644000014852145",
                warehouse_name: "Bananeira GmbH & Co. KG",
                address: "Wetterkreuz 11",
                city: "Erlangen",
                state: "",
                country: "Germany",
                zip: "91058",
                phone: "+49 9131 61020-0",
                email: "",
                is_primary: false,
                status: "active",
                sales_channels: [],
              },
            ],
            billing_address_id: "98644000003917354",
            billing_address: {
              address: "Maxstr. 8",
              street2: "",
              city: "Fürth",
              state: "",
              zip: "90762",
              country: "Deutschland",
              country_code: "DE",
              state_code: "",
              fax: "",
              phone: "",
              attention: "",
            },
            shipping_address_id: "98644000003917356",
            shipping_address: {
              address: "",
              street2: "",
              city: "",
              state: "",
              zip: "",
              country: "",
              country_code: "",
              state_code: "",
              fax: "",
              phone: "",
              attention: "",
            },
            is_test_order: false,
            notes: "",
            terms: "",
            payment_terms: 15,
            payment_terms_label: "15 Tage",
            custom_fields: [
              {
                field_id: "98644000000161049",
                customfield_id: "98644000000161049",
                show_in_store: false,
                show_in_portal: false,
                is_active: true,
                index: 1,
                label: "Ready to fulfill",
                show_on_pdf: false,
                edit_on_portal: false,
                edit_on_store: false,
                api_name: "cf_ready_to_fulfill",
                show_in_all_pdf: false,
                value_formatted: "false",
                search_entity: "salesorder",
                data_type: "check_box",
                placeholder: "cf_ready_to_fulfill",
                value: false,
                is_dependent_field: false,
              },
            ],
            custom_field_hash: {
              cf_ready_to_fulfill: "false",
              cf_ready_to_fulfill_unformatted: false,
            },
            template_id: "98644000000000111",
            template_name: "Standard Template",
            page_width: "8.27in",
            page_height: "11.69in",
            orientation: "portrait",
            template_type: "standard",
            created_time: "2021-12-17T14:12:57+0100",
            last_modified_time: "2022-01-12T16:59:17+0100",
            created_by_id: "98644000000032001",
            created_date: "2021-12-17",
            last_modified_by_id: "98644000000470474",
            attachment_name: "",
            can_send_in_mail: false,
            salesperson_id: "98644000000116041",
            salesperson_name: "Jannik Zinkl",
            merchant_id: "",
            merchant_name: "",
            pickup_location_id: "",
            discount_amount: 0.0,
            discount: 0.0,
            discount_applied_on_amount: 0.0,
            is_adv_tracking_in_package: false,
            shipping_charge_tax_id: "",
            shipping_charge_tax_name: "",
            shipping_charge_tax_type: "",
            shipping_charge_tax_percentage: 0,
            shipping_charge_tax: "",
            bcy_shipping_charge_tax: "",
            shipping_charge_exclusive_of_tax: 0.0,
            shipping_charge_inclusive_of_tax: 0.0,
            shipping_charge_tax_formatted: "",
            shipping_charge_exclusive_of_tax_formatted: "€0,00",
            shipping_charge_inclusive_of_tax_formatted: "€0,00",
            shipping_charge: 0.0,
            bcy_shipping_charge: 0.0,
            adjustment: 0.0,
            bcy_adjustment: 0.0,
            adjustment_description: "Anpassung",
            roundoff_value: 0.0,
            transaction_rounding_type: "no_rounding",
            sub_total: 179.0,
            bcy_sub_total: 179.0,
            sub_total_inclusive_of_tax: 0.0,
            sub_total_exclusive_of_discount: 179.0,
            discount_total: 0.0,
            bcy_discount_total: 0.0,
            discount_percent: 0.0,
            tax_total: 12.53,
            bcy_tax_total: 12.53,
            total: 191.53,
            bcy_total: 191.53,
            taxes: [
              {
                tax_name: "USt. reduziert (7%)",
                tax_amount: 12.53,
              },
            ],
            packages: [
              {
                package_id: "98644000005013469",
                package_number: "PKG-04173",
                date: "2021-12-17",
                status: "delivered",
                detailed_status: "",
                status_message: "",
                shipment_id: "98644000005013632",
                shipment_number: "SHP-04120",
                shipment_status: "delivered",
                carrier: "Abholung",
                service: "",
                tracking_number: "",
                shipment_date: "2021-12-17",
                delivery_days: "",
                delivery_guarantee: false,
                delivery_method: "Abholung",
                quantity: 15.0,
                is_tracking_enabled: false,
                shipment_order: {
                  shipment_id: "98644000005013632",
                  shipment_number: "SHP-04120",
                  shipment_date: "2021-12-17",
                  shipment_date_with_time: "2021-12-17 00:00",
                  tracking_number: "",
                  delivery_date: "",
                  delivery_date_with_time: "",
                  shipment_type: "single_piece_shipment",
                  associated_packages_count: 1,
                  carrier: "Abholung",
                  service: "",
                  delivery_days: "",
                  delivery_guarantee: false,
                  tracking_url: "",
                  is_carrier_shipment: false,
                },
              },
            ],
            so_cycle_preference: {
              is_feature_enabled: false,
              socycle_status: "not_triggered",
              can_create_invoice: false,
              can_create_package: false,
              can_create_shipment: false,
              shipment_preference: {
                default_carrier: "",
                send_notification: false,
                deliver_shipments: false,
              },
            },
            invoices: [
              {
                invoice_id: "98644000005130803",
                invoice_number: "INV-002553",
                reference_number: "SO-00451",
                status: "paid",
                date: "2021-12-21",
                due_date: "2022-01-05",
                total: 191.53,
                balance: 0.0,
              },
            ],
            salesreturns: [],
            payments: [
              {
                payment_id: "98644000005515987",
                payment_mode: "Bank Geldüberweisung",
                payment_mode_id: "98644000000000208",
                amount: 191.53,
                date: "2022-01-03",
                offline_created_date_with_time: "",
                description: "",
                reference_number: "",
                account_id: "98644000002469016",
                account_name: "Sparkasse Nürnberg Sichteinlagen",
                payment_type: "Kundenrechnungszahlungen",
              },
            ],
            creditnotes: [],
            refunds: [],
            balance: 0.0,
            approvers_list: [],
          },
          "116240000001637008": {
            salesorder_id: "116240000001637008",
            documents: [],
            zcrm_potential_id: "",
            zcrm_potential_name: "",
            salesorder_number: "SO-00060",
            date: "2022-08-23",
            offline_created_date_with_time: "",
            tracking_url: "",
            has_discount: false,
            status: "confirmed",
            color_code: "",
            current_sub_status_id: "",
            current_sub_status: "confirmed",
            sub_statuses: [],
            shipment_date: "",
            reference_number: "",
            customer_id: "116240000000631001",
            customer_name: "Christina Lang",
            contact_persons: ["116240000000631003"],
            contact_person_details: [
              {
                phone: "",
                mobile: "",
                last_name: "Lang",
                contact_person_id: "116240000000631003",
                first_name: "Christina",
                email: "zinkljannik+chri@gmail.com",
              },
            ],
            source: "Client",
            contact_category: "",
            currency_id: "116240000000000071",
            currency_code: "EUR",
            currency_symbol: "€",
            exchange_rate: 1.0,
            is_discount_before_tax: true,
            discount_type: "item_level",
            estimate_id: "",
            delivery_method: "",
            delivery_method_id: "",
            is_inclusive_tax: false,
            tax_rounding: "entity_level",
            order_status: "confirmed",
            invoiced_status: "not_invoiced",
            paid_status: "unpaid",
            shipped_status: "pending",
            sales_channel: "direct_sales",
            sales_channel_formatted: "Direct Sales",
            account_identifier: "",
            integration_id: "",
            is_dropshipped: false,
            is_backordered: false,
            is_manually_fulfilled: false,
            can_manually_fulfill: true,
            has_qty_cancelled: false,
            shipping_details: {},
            created_by_email: "jannik@trieb.work",
            total_quantity: 1.0,
            line_items: [
              {
                line_item_id: "116240000001637012",
                variant_id: "116240000000037071",
                item_id: "116240000000037071",
                is_returnable: true,
                product_id: "116240000000037071",
                attribute_name1: "",
                attribute_name2: "",
                attribute_name3: "",
                attribute_option_name1: "",
                attribute_option_name2: "",
                attribute_option_name3: "",
                attribute_option_data1: "",
                attribute_option_data2: "",
                attribute_option_data3: "",
                is_combo_product: false,
                warehouse_id: "116240000000067007",
                warehouse_name: "GIGATEC GmbH",
                sku: "leerdose_charlotte_dumortier",
                name: "Leerdose Charlotte Dumortier",
                group_name: "Leerdose Charlotte Dumortier",
                description: "",
                item_order: 0,
                bcy_rate: 2.5,
                rate: 2.5,
                quantity: 1.0,
                quantity_manuallyfulfilled: 0.0,
                unit: "box",
                pricebook_id: "",
                header_id: "",
                header_name: "",
                discount_amount: 0.0,
                discount: 0.0,
                discounts: [],
                tax_id: "116240000001634022",
                tax_name: "Reduziert",
                tax_type: "tax",
                tax_percentage: 7,
                item_total: 2.5,
                item_sub_total: 2.5,
                product_type: "goods",
                line_item_type: "goods",
                item_type: "inventory",
                is_invoiced: false,
                is_unconfirmed_product: false,
                tags: [],
                image_name: "",
                image_type: "",
                image_document_id: "",
                document_id: "",
                item_custom_fields: [],
                quantity_invoiced: 0.0,
                quantity_packed: 0.0,
                quantity_shipped: 0.0,
                quantity_backordered: 0,
                quantity_dropshipped: 0.0,
                quantity_cancelled: 0.0,
                package_details: {
                  length: "",
                  width: "",
                  height: "",
                  weight: 0.2,
                  weight_unit: "kg",
                  dimension_unit: "cm",
                },
                quantity_invoiced_cancelled: 0.0,
                quantity_returned: 0.0,
              },
            ],
            submitter_id: "",
            approver_id: "",
            submitted_date: "",
            submitted_by: "",
            price_precision: 2,
            is_emailed: false,
            has_unconfirmed_line_item: false,
            picklists: [],
            purchaseorders: [],
            warehouses: [
              {
                warehouse_id: "116240000000067007",
                warehouse_name: "GIGATEC GmbH",
                address: "Siegelsdorfer Str. 30",
                city: "Fürth",
                state: "",
                country: "Germany",
                zip: "90768",
                phone: "",
                email: "jannik@trieb.work",
                is_primary: true,
                status: "active",
                sales_channels: [],
              },
            ],
            billing_address_id: "116240000000631004",
            billing_address: {
              address: "Httoz 22",
              street2: "",
              city: "Prag",
              state: "",
              zip: "09548",
              country: "Czech Republic",
              country_code: "CZ",
              state_code: "",
              fax: "",
              phone: "",
              attention: "Other user",
            },
            shipping_address_id: "116240000000631006",
            shipping_address: {
              address: "Bielefelder Str. 24",
              street2: "",
              city: "Nürnberg",
              state: "",
              zip: "90425",
              country: "Germany",
              country_code: "DE",
              state_code: "",
              fax: "",
              phone: "015151183272",
              attention: "",
            },
            is_test_order: false,
            notes: "",
            terms: "",
            payment_terms: 0,
            payment_terms_label: "Due on Receipt",
            custom_fields: [
              {
                field_id: "116240000000112068",
                customfield_id: "116240000000112068",
                show_in_store: false,
                show_in_portal: false,
                is_active: true,
                index: 1,
                label: "Ready to fulfill",
                show_on_pdf: false,
                edit_on_portal: false,
                edit_on_store: false,
                api_name: "cf_ready_to_fulfill",
                show_in_all_pdf: false,
                value_formatted: "false",
                search_entity: "salesorder",
                data_type: "check_box",
                placeholder: "cf_ready_to_fulfill",
                value: false,
                is_dependent_field: false,
              },
              {
                field_id: "116240000001342366",
                customfield_id: "116240000001342366",
                show_in_store: false,
                show_in_portal: false,
                is_active: true,
                index: 2,
                label: "preferred-language",
                show_on_pdf: false,
                edit_on_portal: false,
                edit_on_store: false,
                api_name: "cf_language",
                show_in_all_pdf: false,
                selected_option_id: "116240000001342370",
                value_formatted: "en",
                search_entity: "salesorder",
                data_type: "dropdown",
                placeholder: "cf_language",
                value: "en",
                is_dependent_field: false,
              },
            ],
            custom_field_hash: {
              cf_ready_to_fulfill: "false",
              cf_ready_to_fulfill_unformatted: false,
              cf_language: "en",
              cf_language_unformatted: "en",
            },
            template_id: "116240000000000111",
            template_name: "Standard Template",
            page_width: "8.27in",
            page_height: "11.69in",
            orientation: "portrait",
            template_type: "standard",
            created_time: "2022-08-23T17:18:39+0200",
            last_modified_time: "2022-08-23T17:18:41+0200",
            created_by_id: "116240000000032001",
            created_date: "2022-08-23",
            last_modified_by_id: "116240000000032001",
            attachment_name: "",
            can_send_in_mail: false,
            salesperson_id: "",
            salesperson_name: "",
            merchant_id: "",
            merchant_name: "",
            pickup_location_id: "",
            discount: 0.0,
            discount_applied_on_amount: 0.0,
            is_adv_tracking_in_package: false,
            shipping_charge_tax_id: "",
            shipping_charge_tax_name: "",
            shipping_charge_tax_type: "",
            shipping_charge_tax_percentage: "",
            shipping_charge_tax: "",
            bcy_shipping_charge_tax: "",
            shipping_charge_exclusive_of_tax: 0.0,
            shipping_charge_inclusive_of_tax: 0.0,
            shipping_charge_tax_formatted: "",
            shipping_charge_exclusive_of_tax_formatted: "€0,00",
            shipping_charge_inclusive_of_tax_formatted: "€0,00",
            shipping_charge: 0.0,
            bcy_shipping_charge: 0.0,
            adjustment: 0.0,
            bcy_adjustment: 0.0,
            adjustment_description: "Adjustment",
            roundoff_value: 0.0,
            transaction_rounding_type: "no_rounding",
            sub_total: 2.5,
            bcy_sub_total: 2.5,
            sub_total_inclusive_of_tax: 0.0,
            sub_total_exclusive_of_discount: 2.5,
            discount_total: 0.0,
            bcy_discount_total: 0.0,
            discount_percent: 0.0,
            tax_total: 0.18,
            bcy_tax_total: 0.18,
            total: 2.68,
            bcy_total: 2.68,
            taxes: [
              {
                tax_name: "Reduziert (7%)",
                tax_amount: 0.18,
              },
            ],
            packages: [],
            so_cycle_preference: {
              is_feature_enabled: false,
              socycle_status: "not_triggered",
              can_create_invoice: false,
              can_create_package: false,
              can_create_shipment: false,
              shipment_preference: {
                default_carrier: "",
                send_notification: false,
                deliver_shipments: false,
              },
            },
            invoices: [],
            salesreturns: [],
            payments: [],
            creditnotes: [],
            refunds: [],
            balance: 2.68,
            approvers_list: [],
          },
        };
        return await Promise.resolve(mapping[salesorderid]);
      },
    },
    util: new Zoho(zohoClient).util,
  } as unknown as Zoho;

  beforeAll(async () => {
    zohoApp = await prismaClient.zohoApp.findUnique({
      where: {
        id: "test",
      },
      include: { tenant: true },
    });
    if (!zohoApp) throw new Error("No testing Zoho App found!");
  });

  test("It should work to sync Zoho Sales Order to internal ECI DB", async () => {
    const xx = new ZohoSalesOrdersSyncService({
      zoho: mockedZohoClient,
      logger: new NoopLogger(),
      db: new PrismaClient(),
      zohoApp,
    });
    await xx.syncToECI();
  }, 90000);

});
