/* eslint-disable max-len */
import { NoopLogger } from "@eci/pkg/logger";
import { PrismaClient } from "@eci/pkg/prisma";
import { beforeEach, describe, jest, test, beforeAll } from "@jest/globals";
import { SalesOrder, Zoho, ZohoApiClient } from "@trieb.work/zoho-ts";
import { ZohoSalesOrdersSyncService } from ".";

let zohoApp: any;

beforeEach(() => {
  jest.clearAllMocks();
});

describe("Zoho Inventory SalesOrders Sync", () => {
  const prismaClient = new PrismaClient();

  const zohoClient = undefined as unknown as ZohoApiClient;
  const mockedZohoClient = {
    salesOrder: {
      list: async () =>
        await Promise.resolve([
          {
            salesorder_id: "116240000001637008",
            zcrm_potential_id: "",
            zcrm_potential_name: "",
            customer_name: "Christina Lang",
            customer_id: "116240000000631001",
            email: "zinkljannik+chri@gmail.com",
            delivery_date: "",
            company_name: "",
            color_code: "",
            current_sub_status_id: "",
            current_sub_status: "confirmed",
            pickup_location_id: "",
            salesorder_number: "SO-00060",
            reference_number: "",
            date: "2022-08-23",
            shipment_date: "",
            shipment_days: "",
            due_by_days: "",
            due_in_days: "",
            currency_id: "116240000000000071",
            source: "Client",
            currency_code: "EUR",
            total: 2.68,
            bcy_total: 2.68,
            total_invoiced_amount: 0.0,
            created_time: "2022-08-23T17:18:39+0200",
            last_modified_time: "2022-08-23T17:18:41+0200",
            is_emailed: false,
            quantity: 1.0,
            quantity_invoiced: 0.0,
            quantity_packed: 0.0,
            quantity_shipped: 0.0,
            order_status: "confirmed",
            invoiced_status: "not_invoiced",
            paid_status: "unpaid",
            shipped_status: "pending",
            status: "confirmed",
            is_drop_shipment: false,
            is_backorder: false,
            is_manually_fulfilled: false,
            sales_channel: "direct_sales",
            sales_channel_formatted: "Direct Sales",
            salesperson_name: "",
            has_attachment: false,
            cf_ready_to_fulfill: "false",
            cf_ready_to_fulfill_unformatted: false,
            cf_language: "en",
            cf_language_unformatted: "en",
            balance: 2.68,
            delivery_method: "",
            delivery_method_id: "",
          },
          {
            salesorder_id: "116240000001580015",
            zcrm_potential_id: "",
            zcrm_potential_name: "",
            customer_name: "Jannik Zinkl",
            customer_id: "116240000001504002",
            email: "zinkljannik@gmail.com",
            delivery_date: "",
            company_name: "",
            color_code: "",
            current_sub_status_id: "",
            current_sub_status: "draft",
            pickup_location_id: "",
            salesorder_number: "SO-00059",
            reference_number: "",
            date: "2022-06-07",
            shipment_date: "",
            shipment_days: "",
            due_by_days: "",
            due_in_days: "",
            currency_id: "116240000000000071",
            source: "Client",
            currency_code: "EUR",
            total: 19.62,
            bcy_total: 19.62,
            total_invoiced_amount: 0.0,
            created_time: "2022-06-07T14:16:42+0200",
            last_modified_time: "2022-06-07T14:16:42+0200",
            is_emailed: false,
            quantity: 2.0,
            quantity_invoiced: 0.0,
            quantity_packed: 0.0,
            quantity_shipped: 0.0,
            order_status: "draft",
            invoiced_status: "",
            paid_status: "",
            shipped_status: "",
            status: "draft",
            is_drop_shipment: false,
            is_backorder: false,
            is_manually_fulfilled: false,
            sales_channel: "direct_sales",
            sales_channel_formatted: "Direct Sales",
            salesperson_name: "",
            has_attachment: false,
            cf_ready_to_fulfill: "false",
            cf_ready_to_fulfill_unformatted: false,
            cf_language: "en",
            cf_language_unformatted: "en",
            balance: 19.62,
            delivery_method: "",
            delivery_method_id: "",
          },
          {
            salesorder_id: "116240000001532575",
            zcrm_potential_id: "",
            zcrm_potential_name: "",
            customer_name: "Christina Lang",
            customer_id: "116240000000631001",
            email: "zinkljannik+chri@gmail.com",
            delivery_date: "",
            company_name: "",
            color_code: "",
            current_sub_status_id: "",
            current_sub_status: "confirmed",
            pickup_location_id: "",
            salesorder_number: "SO-00057",
            reference_number: "",
            date: "2022-05-12",
            shipment_date: "",
            shipment_days: "",
            due_by_days: "",
            due_in_days: "",
            currency_id: "116240000000000071",
            source: "Client",
            currency_code: "EUR",
            total: 1.07,
            bcy_total: 1.07,
            total_invoiced_amount: 0.0,
            created_time: "2022-05-12T17:44:41+0200",
            last_modified_time: "2022-07-21T14:13:49+0200",
            is_emailed: false,
            quantity: 2.0,
            quantity_invoiced: 0.0,
            quantity_packed: 0.0,
            quantity_shipped: 0.0,
            order_status: "confirmed",
            invoiced_status: "not_invoiced",
            paid_status: "unpaid",
            shipped_status: "pending",
            status: "confirmed",
            is_drop_shipment: false,
            is_backorder: false,
            is_manually_fulfilled: false,
            sales_channel: "direct_sales",
            sales_channel_formatted: "Direct Sales",
            salesperson_name: "",
            has_attachment: false,
            cf_ready_to_fulfill: "false",
            cf_ready_to_fulfill_unformatted: false,
            cf_language: "en",
            cf_language_unformatted: "en",
            balance: 0.0,
            delivery_method: "",
            delivery_method_id: "",
          },
          {
            salesorder_id: "116240000001504271",
            zcrm_potential_id: "",
            zcrm_potential_name: "",
            customer_name: "Jannik Zinkl",
            customer_id: "116240000001504002",
            email: "zinkljannik@gmail.com",
            delivery_date: "",
            company_name: "",
            color_code: "",
            current_sub_status_id: "",
            current_sub_status: "confirmed",
            pickup_location_id: "",
            salesorder_number: "STORE-1992",
            reference_number: "T3JkZXI6MTk5Mg==",
            date: "2022-04-20",
            shipment_date: "",
            shipment_days: "",
            due_by_days: "",
            due_in_days: "",
            currency_id: "116240000000000071",
            source: "Api",
            currency_code: "EUR",
            total: 12.21,
            bcy_total: 12.21,
            total_invoiced_amount: 12.21,
            created_time: "2022-04-20T11:08:15+0200",
            last_modified_time: "2022-05-12T11:27:11+0200",
            is_emailed: false,
            quantity: 1.0,
            quantity_invoiced: 1.0,
            quantity_packed: 0.0,
            quantity_shipped: 0.0,
            order_status: "confirmed",
            invoiced_status: "invoiced",
            paid_status: "paid",
            shipped_status: "pending",
            status: "confirmed",
            is_drop_shipment: false,
            is_backorder: false,
            is_manually_fulfilled: false,
            sales_channel: "direct_sales",
            sales_channel_formatted: "Direct Sales",
            salesperson_name: "",
            has_attachment: false,
            cf_ready_to_fulfill: "true",
            cf_ready_to_fulfill_unformatted: true,
            cf_language: "en",
            cf_language_unformatted: "en",
            balance: 12.21,
            delivery_method: "DPD Germany",
            delivery_method_id: "116240000000037235",
          },
          {
            salesorder_id: "116240000001500001",
            zcrm_potential_id: "",
            zcrm_potential_name: "",
            customer_name: "Linda Thomas",
            customer_id: "116240000001499002",
            email: "megan.chang@example.com",
            delivery_date: "",
            company_name: "",
            color_code: "",
            current_sub_status_id: "",
            current_sub_status: "confirmed",
            pickup_location_id: "",
            salesorder_number: "STORE-1990",
            reference_number: "T3JkZXI6MTk5MA==",
            date: "2022-04-19",
            shipment_date: "",
            shipment_days: "",
            due_by_days: "",
            due_in_days: "",
            currency_id: "116240000000000071",
            source: "Api",
            currency_code: "EUR",
            total: 20.21,
            bcy_total: 20.21,
            total_invoiced_amount: 0.0,
            created_time: "2022-04-19T16:16:21+0200",
            last_modified_time: "2022-06-24T20:03:21+0200",
            is_emailed: false,
            quantity: 2.0,
            quantity_invoiced: 0.0,
            quantity_packed: 0.0,
            quantity_shipped: 0.0,
            order_status: "confirmed",
            invoiced_status: "not_invoiced",
            paid_status: "unpaid",
            shipped_status: "pending",
            status: "confirmed",
            is_drop_shipment: false,
            is_backorder: false,
            is_manually_fulfilled: false,
            sales_channel: "direct_sales",
            sales_channel_formatted: "Direct Sales",
            salesperson_name: "",
            has_attachment: false,
            cf_ready_to_fulfill: "true",
            cf_ready_to_fulfill_unformatted: true,
            cf_language: "en",
            cf_language_unformatted: "en",
            balance: 20.21,
            delivery_method: "DPD Germany",
            delivery_method_id: "116240000000037235",
          },
        ]),
      get: async (salesorderid: string) => {
        const mapping: { [key: string]: SalesOrder } = {};
        return await Promise.resolve(mapping[salesorderid]);
      },
    },
    util: new Zoho(zohoClient).util,
  } as unknown as Zoho;

  beforeAll(async () => {
    zohoApp = await prismaClient.zohoApp.findUnique({
      where: {
        id: "test",
      },
      include: { tenant: true },
    });
    if (!zohoApp) throw new Error("No testing Zoho App found!");
  });

  test("It should work to sync Zoho Sales Order to internal ECI DB", async () => {
    const xx = new ZohoSalesOrdersSyncService({
      zoho: mockedZohoClient,
      logger: new NoopLogger(),
      db: new PrismaClient(),
      zohoApp,
      createdTimeOffset: 1,
    });
    await xx.syncToECI();
  }, 90000);
});
