# The Environment, where the Worker should register to
eciEnv: development

image:
  imageName: registry.gitlab.com/trieb.work/ecommerce-integrations/worker

replicas: 1
databaseUrl: postgres://
databaseUrlPool: postgres://
signingKey: wrgkpw35ipo2i5p

imagePullSecret: regreced

redis:
  host: redis.test.de
  port: 6379
  password: 24ß5f-2345f-245

elasticsearch:
  host: elastic.test.com
  username: elastic
  password: elastic

kafka:
  brokerUrl: kafka:9092
  saslMechanism: scram-sha-256
  username: kafka
  password: kafka

sendgridApiKey: abc
resources:
  limits:

    memory: 600Mi
  requests:
    cpu: 100m
    memory: 128Mi

secretKey: