fragment categoryValues on Category {
  id
  name
  slug
  description
  seoTitle
  seoDescription
  backgroundImage {
    url
  }
  children(first: 100) {
    edges {
      node {
        id
      }
    }
  }
  parent {
    id
  }
  products(first: 100) {
    edges {
      node {
        id
      }
    }
  }
}

query saleorCronCategories($first: Int, $last: Int) {
  categories(first: $first, last: $last) {
    pageInfo {
      hasNextPage
      startCursor
      endCursor
    }
    edges {
      node {
        ...categoryValues
      }
    }
  }
}
