fragment standardAddressValues on Address {
  firstName
  lastName
  phone
  postalCode
  streetAddress1
  streetAddress2
  city
  companyName
  country {
    code
  }
}

query saleorCronOrdersOverview($createdGte: Date, $after: String, $first: Int) {
  orders(
    first: $first
    after: $after
    filter: { created: { gte: $createdGte } }
  ) {
    pageInfo {
      hasNextPage
      startCursor
      endCursor
    }
    edges {
      node {
        id
        created
        status
        userEmail
        billingAddress {
          ...standardAddressValues
        }
        shippingAddress {
          ...standardAddressValues
        }
        paymentStatus
        number
        total {
          currency
          gross {
            amount
          }
        }
      }
    }
  }
}

query saleorCronOrderDetails($id: ID!) {
  order(id: $id) {
    id
    created
    number
    voucher {
      id
      code
      type
    }
    shippingPrice {
      currency
      tax {
        amount
      }
      net {
        amount
      }
      gross {
        amount
      }
    }
    lines {
      id
      variant {
        sku
      }
      allocations {
        warehouse {
          id
          name
        }
      }
      quantity
      unitDiscountType
      unitDiscountValue
      undiscountedUnitPrice {
        currency
        gross {
          amount
        }
        net {
          amount
        }
      }
      taxRate
      totalPrice {
        gross {
          amount
        }
        net {
          amount
        }
        currency
      }
    }
    undiscountedTotal {
      net {
        amount
      }
      gross {
        amount
      }
    }
    total {
      currency
      gross {
        amount
      }
      net {
        amount
      }
    }
    paymentStatus
  }
}