fragment standardAddressValues on Address {
    firstName
    lastName
    phone
    postalCode
    streetAddress1
    streetAddress2
    city
    companyName
    country {
        code
    }
    countryArea
}

query saleorCronOrdersOverview(
    $createdGte: Date
    $after: String
    $first: Int
    $updatedAtGte: DateTime
) {
    orders(
        first: $first
        after: $after
        filter: {
            created: { gte: $createdGte }
            updatedAt: { gte: $updatedAtGte }
        }
    ) {
        pageInfo {
            hasNextPage
            startCursor
            endCursor
        }
        edges {
            node {
                id
                created
                status
                userEmail
                billingAddress {
                    ...standardAddressValues
                }
                shippingAddress {
                    ...standardAddressValues
                }
                shippingPrice {
                    gross {
                        amount
                    }
                }
                voucher {
                    id
                    code
                    type
                }
                languageCodeEnum
                shippingMethodName
                deliveryMethod {
                    __typename
                    ... on ShippingMethod {
                        __typename
                        id
                        name
                    }
                }
                paymentStatus
                isPaid
                number
                externalReference
                total {
                    currency
                    gross {
                        amount
                    }
                }
            }
        }
    }
}

query saleorCronOrderDetails($id: ID!) {
    order(id: $id) {
        id
        created
        number
        shippingPrice {
            currency
            tax {
                amount
            }
            net {
                amount
            }
            gross {
                amount
            }
        }
        lines {
            id
            productSku
            skuFromMetadata: metafield(key: "sku")
            variant {
                id
                sku
            }
            quantity
            unitDiscountType
            unitDiscount {
                amount
            }
            undiscountedUnitPrice {
                currency
                gross {
                    amount
                }
                net {
                    amount
                }
            }
            taxRate
            totalPrice {
                gross {
                    amount
                }
                net {
                    amount
                }
                currency
            }
        }
        undiscountedTotal {
            net {
                amount
            }
            gross {
                amount
            }
        }
        total {
            currency
            gross {
                amount
            }
            net {
                amount
            }
        }
        paymentStatus
    }
}

query orderByReference($externalReference: String!) {
    order(externalReference: $externalReference) {
        id
    }
}
