query saleorCronPackagesOverview(
  $createdGte: Date
  $after: String
  $first: Int
) {
  orders(
    first: $first
    after: $after
    filter: { created: { gte: $createdGte } }
  ) {
    pageInfo {
      hasNextPage
      startCursor
      endCursor
    }
    edges {
      node {
        id
        number
        fulfillments {
          id
          created
          fulfillmentOrder
          lines {
            quantity
            orderLine {
              productSku
            }
          }
          trackingNumber
          status
        }
      }
    }
  }
}
