query saleorCronPayments(
    $createdGte: Date
    $after: String
    $updatedAtGte: DateTime
    $first: Int
) {
    orders(
        first: $first
        after: $after
        filter: {
            created: { gte: $createdGte }
            updatedAt: { gte: $updatedAtGte }
        }
    ) {
        totalCount
        pageInfo {
            hasNextPage
            endCursor
            startCursor
        }
        edges {
            node {
                id
                channel {
                    id
                    name
                }
                payments {
                    id
                    gateway
                    created
                    modified
                    isActive
                    chargeStatus
                    creditCard {
                        brand
                        lastDigits
                    }
                    order {
                        id
                        created
                        number
                        userEmail
                    }
                    paymentMethodType
                    transactions {
                        id
                        isSuccess
                        # token is the Braintree Transaction ID
                        token
                        # only with kind, we can filter out "AUTH" transactions for pre-payments
                        kind
                    }
                    total {
                        currency
                        amount
                    }
                }
                transactions {
                    id
                    name
                    createdAt
                    actions
                    authorizedAmount {
                        currency
                        amount
                    }
                    authorizePendingAmount {
                        currency
                        amount
                    }
                    chargePendingAmount {
                        currency
                        amount
                    }
                    chargedAmount {
                        currency
                        amount
                    }
                    events {
                        type
                        amount {
                            amount
                        }
                    }
                    message
                    createdBy {
                        ... on App {
                            id
                            name
                        }
                    }
                    pspReference
                    privateMetadata {
                        key
                        value
                    }
                    order {
                        id
                        created
                        number
                        userEmail
                    }
                }
            }
        }
    }
}
