query products($first: Int!, $channel: String) {
  products(first: $first, channel: $channel) {
    edges {
      node {
        seoDescription
        name
        seoTitle
        isAvailableForPurchase
        description
        slug
        weight {
          unit
          value
        }
        images {
          id
          url
        }
        metadata {
          key
          value
        }
        attributes {
          attribute {
            id
            name
          }
          values {
            id
            name
          }
        }
        productType {
          name
          id
          hasVariants
        }
        variants {
          id
          name
          sku
          quantityAvailable
          weight {
            unit
            value
          }
          metadata {
            key
            value
          }
          pricing {
            priceUndiscounted {
              gross {
                amount
                currency
              }
            }
            price {
              gross {
                amount
                currency
              }
              net {
                amount
              }
            }
            onSale
            discount {
              gross {
                amount
              }
            }
          }
          images {
            url
          }
        }
      }
    }
  }
}

query saleorEntitySyncProducts($first: Int!, $channel: String, $after: String) {
  products(first: $first, after: $after, channel: $channel) {
    pageInfo {
      hasNextPage
      hasPreviousPage
      startCursor
      endCursor
    }
    edges {
      node {
        id
        name
        updatedAt
        variants {
          id
          name
          sku
          metadata {
            key
            value
          }
          stocks {
            warehouse {
              name
              id
            }
          }
          variantAttributes: attributes(variantSelection: VARIANT_SELECTION) {
            attribute {
              name
            }
            values {
              id
              name
            }
          }
        }
      }
    }
  }
}

query saleorProductVariantBasicData($id: ID!) {
  productVariant(id: $id) {
    id
    name
    product {
      id
      name
    }
    metadata {
      key
      value
    }
    stocks {
      warehouse {
        id
        name
      }
      quantity
      quantityAllocated
    }
  }
}
