query products($first: Int!, $channel: String) {
    products(first: $first, channel: $channel) {
        edges {
            node {
                seoDescription
                name
                seoTitle
                isAvailableForPurchase
                description
                slug
                weight {
                    unit
                    value
                }
                images {
                    id
                    url
                }
                metadata {
                    key
                    value
                }
                attributes {
                    attribute {
                        id
                        name
                    }
                    values {
                        id
                        name
                    }
                }
                productType {
                    name
                    id
                    hasVariants
                }
                variants {
                    id
                    name
                    sku
                    quantityAvailable
                    weight {
                        unit
                        value
                    }
                    metadata {
                        key
                        value
                    }
                    pricing {
                        priceUndiscounted {
                            gross {
                                amount
                                currency
                            }
                        }
                        price {
                            gross {
                                amount
                                currency
                            }
                            net {
                                amount
                            }
                        }
                        onSale
                        discount {
                            gross {
                                amount
                            }
                        }
                    }
                    images {
                        url
                    }
                }
            }
        }
    }
}

fragment variant on ProductVariant {
    id
    name
    sku
    metadata {
        key
        value
    }
    stocks {
        warehouse {
            name
            id
        }
    }
    variantAttributes: attributes(variantSelection: VARIANT_SELECTION) {
        attribute {
            name
        }
        values {
            id
            name
        }
    }
}

fragment productType on ProductType {
    id
    name
    hasVariants
    productAttributes {
        id
        name
    }
    assignedVariantAttributes {
        attribute {
            id
            name
        }
        variantSelection
    }
}

query saleorEntitySyncProducts(
    $first: Int!
    $channel: String
    $after: String
    $updatedAtGte: DateTime
    $ids: [ID!]
) {
    products(
        first: $first
        after: $after
        channel: $channel
        filter: { updatedAt: { gte: $updatedAtGte }, ids: $ids }
    ) {
        pageInfo {
            hasNextPage
            hasPreviousPage
            startCursor
            endCursor
        }
        edges {
            node {
                id
                name
                updatedAt
                created
                productType {
                    ...productType
                }
                category {
                    id
                }
                updatedAt
                media {
                    id
                    schemabaseMediaId: metafield(key: "schemabase-media-id")
                    url
                }
                variants {
                    ...variant
                }
            }
        }
    }
}

query saleorProductVariantsBasicData(
    $ids: [ID!]!
    $first: Int
    $after: String
) {
    productVariants(ids: $ids, first: $first, after: $after) {
        pageInfo {
            hasNextPage
            hasPreviousPage
            startCursor
            endCursor
        }
        edges {
            node {
                id
                name
                product {
                    id
                    name
                }
                metadata {
                    key
                    value
                }
                stocks {
                    warehouse {
                        id
                        name
                    }
                    quantity
                    quantityAllocated
                }
            }
        }
    }
}

query saleorProductVariantBasicData($id: ID!) {
    productVariant(id: $id) {
        id
        name
        product {
            id
            name
        }
        metadata {
            key
            value
        }
        stocks {
            warehouse {
                id
                name
            }
            quantity
            quantityAllocated
        }
    }
}

query productWithAttributes($id: ID!) {
    product(id: $id) {
        attributes {
            attribute {
                id
                name
            }
            values {
                name
                id
            }
        }
    }
}

query productTest($first: Int, $after: String) {
    products(first: $first, after: $after) {
        pageInfo {
            hasNextPage
            hasPreviousPage
            startCursor
            endCursor
        }
        edges {
            node {
                id
                name
                variants {
                    id
                    sku
                }
                channelListings {
                    id
                    channel {
                        id
                    }
                }
            }
        }
    }
}

query productAndVariantsToCompare($id: ID!) {
    product(id: $id) {
        id
        name
        seoTitle
        seoDescription
        category {
            id
            name
        }
        taxClass {
            id
        }
        media {
            ...SaleorProductMedia
        }
        description
        attributes {
            values {
                externalReference
                boolean
                value
                file {
                    url
                }
            }
            attribute {
                id
            }
        }
        variants {
            id
            media {
                id
            }
            sku
        }
    }
}
