import { AssertionLogger, NoopLogger } from "@eci/pkg/logger";
import { PrismaClient, ZohoApp } from "@eci/pkg/prisma";
import { beforeEach, describe, jest, test, beforeAll } from "@jest/globals";
import { Zoho, ZohoApiClient } from "@trieb.work/zoho-ts";
import { ZohoPaymentSyncService } from ".";
import "@eci/pkg/jest-utils/consoleFormatter";

beforeEach(() => {
    jest.clearAllMocks();
});

describe("Zoho Inventory payment Sync", () => {
    const prismaClient = new PrismaClient();

    let zoho: Zoho;
    let zohoApp: ZohoApp;
    let zohoPaymentLogger: AssertionLogger;
    // let zohoPaymentSyncService: ZohoPaymentSyncService;

    const mockedZohoClient = {
        payment: {
            list: async () =>
                Promise.resolve([
                    {
                        payment_id: "98644000014006109",
                        payment_number: "2711",
                        retainerinvoice_id: "",
                        invoice_numbers: "INV-003053",
                        date: "2022-05-30",
                        date_formatted: "30 Mai 2022",
                        payment_mode: "Banküberweisung",
                        payment_mode_formatted: "Banküberweisung",
                        amount: 61.74,
                        amount_formatted: "€61,74",
                        bcy_amount: 61.74,
                        bcy_amount_formatted: "€61,74",
                        unused_amount: 0.0,
                        unused_amount_formatted: "€0,00",
                        bcy_unused_amount: 0.0,
                        bcy_unused_amount_formatted: "€0,00",
                        account_id: "98644000002469016",
                        account_name: "Sparkasse Nürnberg Sichteinlagen",
                        description: "",
                        reference_number: "",
                        customer_id: "98644000002836094",
                        customer_name: "Profi Engineering AG",
                        created_time: "2022-05-30T07:39:46+0200",
                        last_modified_time: "2022-05-30T07:39:46+0200",
                        last_four_digits: "",
                        gateway_transaction_id: "",
                        payment_gateway: "",
                        payment_gateway_formatted: "",
                        bcy_refunded_amount: 0.0,
                        bcy_refunded_amount_formatted: "€0,00",
                        applied_invoices: [],
                        has_attachment: false,
                        documents: "",
                        custom_fields_list: "",
                        tax_account_id: "",
                        tax_account_name: "",
                        tax_amount_withheld: 0.0,
                        tax_amount_withheld_formatted: "€0,00",
                        payment_type: "Rechnungszahlung",
                        settlement_status: "",
                        settlement_status_formatted: "",
                    },
                    {
                        payment_id: "98644000013425881",
                        payment_number: "2710",
                        retainerinvoice_id: "",
                        invoice_numbers: "INV-003056",
                        date: "2022-05-23",
                        date_formatted: "23 Mai 2022",
                        payment_mode: "Banküberweisung",
                        payment_mode_formatted: "Banküberweisung",
                        amount: 9.63,
                        amount_formatted: "€9,63",
                        bcy_amount: 9.63,
                        bcy_amount_formatted: "€9,63",
                        unused_amount: 0.0,
                        unused_amount_formatted: "€0,00",
                        bcy_unused_amount: 0.0,
                        bcy_unused_amount_formatted: "€0,00",
                        account_id: "98644000002469016",
                        account_name: "Sparkasse Nürnberg Sichteinlagen",
                        description: "",
                        reference_number: "",
                        customer_id: "98644000012853360",
                        customer_name: "der buchladen - Bad Wurzach",
                        created_time: "2022-05-23T09:49:34+0200",
                        last_modified_time: "2022-05-23T09:49:34+0200",
                        last_four_digits: "",
                        gateway_transaction_id: "",
                        payment_gateway: "",
                        payment_gateway_formatted: "",
                        bcy_refunded_amount: 0.0,
                        bcy_refunded_amount_formatted: "€0,00",
                        applied_invoices: [],
                        has_attachment: false,
                        documents: "",
                        custom_fields_list: "",
                        tax_account_id: "",
                        tax_account_name: "",
                        tax_amount_withheld: 0.0,
                        tax_amount_withheld_formatted: "€0,00",
                        payment_type: "Rechnungszahlung",
                        settlement_status: "",
                        settlement_status_formatted: "",
                    },
                    {
                        payment_id: "98644000012856605",
                        payment_number: "2709",
                        retainerinvoice_id: "",
                        invoice_numbers: "INV-003047",
                        date: "2022-05-13",
                        date_formatted: "13 Mai 2022",
                        payment_mode: "Bar",
                        payment_mode_formatted: "Bar",
                        amount: 113.85,
                        amount_formatted: "€113,85",
                        bcy_amount: 113.85,
                        bcy_amount_formatted: "€113,85",
                        unused_amount: 0.0,
                        unused_amount_formatted: "€0,00",
                        bcy_unused_amount: 0.0,
                        bcy_unused_amount_formatted: "€0,00",
                        account_id: "98644000002469016",
                        account_name: "Sparkasse Nürnberg Sichteinlagen",
                        description:
                            "AWV-MELDEPFLICHT BEACHTEN HOTLINE BUNDESBANK (0800) 1234-111",
                        reference_number: "",
                        customer_id: "98644000010930001",
                        customer_name: "Qualifyze Spain S.L.",
                        created_time: "2022-05-16T11:06:55+0200",
                        last_modified_time: "2022-05-16T11:06:55+0200",
                        last_four_digits: "",
                        gateway_transaction_id: "",
                        payment_gateway: "",
                        payment_gateway_formatted: "",
                        bcy_refunded_amount: 0.0,
                        bcy_refunded_amount_formatted: "€0,00",
                        applied_invoices: [],
                        has_attachment: false,
                        documents: "",
                        custom_fields_list: "",
                        tax_account_id: "",
                        tax_account_name: "",
                        tax_amount_withheld: 0.0,
                        tax_amount_withheld_formatted: "€0,00",
                        payment_type: "Rechnungszahlung",
                        settlement_status: "",
                        settlement_status_formatted: "",
                    },
                    {
                        payment_id: "98644000012566562",
                        payment_number: "2708",
                        retainerinvoice_id: "",
                        invoice_numbers: "INV-003055",
                        date: "2022-05-12",
                        date_formatted: "12 Mai 2022",
                        payment_mode: "onlinepayment",
                        payment_mode_formatted: "onlinepayment",
                        amount: 19.34,
                        amount_formatted: "€19,34",
                        bcy_amount: 19.34,
                        bcy_amount_formatted: "€19,34",
                        unused_amount: 0.0,
                        unused_amount_formatted: "€0,00",
                        bcy_unused_amount: 0.0,
                        bcy_unused_amount_formatted: "€0,00",
                        account_id: "98644000002101083",
                        account_name: "Braintree Pfeffer & Frost",
                        description: "",
                        reference_number: "",
                        customer_id: "98644000003798974",
                        customer_name: "Goerke Impulse",
                        created_time: "2022-05-12T22:38:13+0200",
                        last_modified_time: "2022-05-12T22:38:13+0200",
                        last_four_digits: "",
                        gateway_transaction_id: "",
                        payment_gateway: "",
                        payment_gateway_formatted: "",
                        bcy_refunded_amount: 0.0,
                        bcy_refunded_amount_formatted: "€0,00",
                        applied_invoices: [],
                        has_attachment: false,
                        documents: "",
                        custom_fields_list: "",
                        cf_gateway_transaction_id: "7sd1zfv4",
                        cf_gateway_transaction_id_unformatted: "7sd1zfv4",
                        tax_account_id: "",
                        tax_account_name: "",
                        tax_amount_withheld: 0.0,
                        tax_amount_withheld_formatted: "€0,00",
                        payment_type: "Rechnungszahlung",
                        settlement_status: "",
                        settlement_status_formatted: "",
                    },
                    {
                        payment_id: "98644000012441745",
                        payment_number: "2707",
                        retainerinvoice_id: "",
                        invoice_numbers: "INV-003054",
                        date: "2022-05-11",
                        date_formatted: "11 Mai 2022",
                        payment_mode: "onlinepayment",
                        payment_mode_formatted: "onlinepayment",
                        amount: 19.34,
                        amount_formatted: "€19,34",
                        bcy_amount: 19.34,
                        bcy_amount_formatted: "€19,34",
                        unused_amount: 0.0,
                        unused_amount_formatted: "€0,00",
                        bcy_unused_amount: 0.0,
                        bcy_unused_amount_formatted: "€0,00",
                        account_id: "98644000002101083",
                        account_name: "Braintree Pfeffer & Frost",
                        description: "",
                        reference_number: "",
                        customer_id: "98644000003798974",
                        customer_name: "Goerke Impulse",
                        created_time: "2022-05-11T10:25:50+0200",
                        last_modified_time: "2022-05-11T10:25:50+0200",
                        last_four_digits: "",
                        gateway_transaction_id: "",
                        payment_gateway: "",
                        payment_gateway_formatted: "",
                        bcy_refunded_amount: 0.0,
                        bcy_refunded_amount_formatted: "€0,00",
                        applied_invoices: [],
                        has_attachment: false,
                        documents: "",
                        custom_fields_list: "",
                        cf_gateway_transaction_id: "rpq20mx3",
                        cf_gateway_transaction_id_unformatted: "rpq20mx3",
                        tax_account_id: "",
                        tax_account_name: "",
                        tax_amount_withheld: 0.0,
                        tax_amount_withheld_formatted: "€0,00",
                        payment_type: "Rechnungszahlung",
                        settlement_status: "",
                        settlement_status_formatted: "",
                    },
                    {
                        payment_id: "98644000012277013",
                        payment_number: "2706",
                        retainerinvoice_id: "",
                        invoice_numbers: "INV-003052",
                        date: "2022-05-09",
                        date_formatted: "09 Mai 2022",
                        payment_mode: "PayPal",
                        payment_mode_formatted: "PayPal",
                        amount: 161.62,
                        amount_formatted: "€161,62",
                        bcy_amount: 161.62,
                        bcy_amount_formatted: "€161,62",
                        unused_amount: 0.0,
                        unused_amount_formatted: "€0,00",
                        bcy_unused_amount: 0.0,
                        bcy_unused_amount_formatted: "€0,00",
                        account_id: "98644000001621195",
                        account_name: "PayPal Pfeffer + Frost",
                        description: "",
                        reference_number: "",
                        customer_id: "98644000003715337",
                        customer_name: "Telekom Deutschland GmbH",
                        created_time: "2022-05-09T11:25:40+0200",
                        last_modified_time: "2022-05-09T19:09:24+0200",
                        last_four_digits: "",
                        gateway_transaction_id: "",
                        payment_gateway: "",
                        payment_gateway_formatted: "",
                        bcy_refunded_amount: 0.0,
                        bcy_refunded_amount_formatted: "€0,00",
                        applied_invoices: [],
                        has_attachment: false,
                        documents: "",
                        custom_fields_list: "",
                        tax_account_id: "",
                        tax_account_name: "",
                        tax_amount_withheld: 0.0,
                        tax_amount_withheld_formatted: "€0,00",
                        payment_type: "Rechnungszahlung",
                        settlement_status: "",
                        settlement_status_formatted: "",
                    },
                    {
                        payment_id: "98644000012132550",
                        payment_number: "2705",
                        retainerinvoice_id: "",
                        invoice_numbers: "INV-003050",
                        date: "2022-05-07",
                        date_formatted: "07 Mai 2022",
                        payment_mode: "onlinepayment",
                        payment_mode_formatted: "onlinepayment",
                        amount: 52.8,
                        amount_formatted: "€52,80",
                        bcy_amount: 52.8,
                        bcy_amount_formatted: "€52,80",
                        unused_amount: 0.0,
                        unused_amount_formatted: "€0,00",
                        bcy_unused_amount: 0.0,
                        bcy_unused_amount_formatted: "€0,00",
                        account_id: "98644000001621195",
                        account_name: "PayPal Pfeffer + Frost",
                        description: "",
                        reference_number: "",
                        customer_id: "98644000004786380",
                        customer_name: "Monique Maume",
                        created_time: "2022-05-07T16:10:36+0200",
                        last_modified_time: "2022-05-07T16:10:36+0200",
                        last_four_digits: "",
                        gateway_transaction_id: "",
                        payment_gateway: "",
                        payment_gateway_formatted: "",
                        bcy_refunded_amount: 0.0,
                        bcy_refunded_amount_formatted: "€0,00",
                        applied_invoices: [],
                        has_attachment: false,
                        documents: "",
                        custom_fields_list: "",
                        cf_gateway_transaction_id: "cwqd1vg3",
                        cf_gateway_transaction_id_unformatted: "cwqd1vg3",
                        tax_account_id: "",
                        tax_account_name: "",
                        tax_amount_withheld: 0.0,
                        tax_amount_withheld_formatted: "€0,00",
                        payment_type: "Rechnungszahlung",
                        settlement_status: "",
                        settlement_status_formatted: "",
                    },
                    {
                        payment_id: "98644000012132438",
                        payment_number: "2704",
                        retainerinvoice_id: "",
                        invoice_numbers: "INV-003049",
                        date: "2022-05-07",
                        date_formatted: "07 Mai 2022",
                        payment_mode: "onlinepayment",
                        payment_mode_formatted: "onlinepayment",
                        amount: 40.9,
                        amount_formatted: "€40,90",
                        bcy_amount: 40.9,
                        bcy_amount_formatted: "€40,90",
                        unused_amount: 0.0,
                        unused_amount_formatted: "€0,00",
                        bcy_unused_amount: 0.0,
                        bcy_unused_amount_formatted: "€0,00",
                        account_id: "98644000001621195",
                        account_name: "PayPal Pfeffer + Frost",
                        description: "",
                        reference_number: "",
                        customer_id: "98644000004362319",
                        customer_name: "Rebecca Hedenkamp",
                        created_time: "2022-05-07T13:41:12+0200",
                        last_modified_time: "2022-05-07T13:41:12+0200",
                        last_four_digits: "",
                        gateway_transaction_id: "",
                        payment_gateway: "",
                        payment_gateway_formatted: "",
                        bcy_refunded_amount: 0.0,
                        bcy_refunded_amount_formatted: "€0,00",
                        applied_invoices: [],
                        has_attachment: false,
                        documents: "",
                        custom_fields_list: "",
                        cf_gateway_transaction_id: "nhk5kmzj",
                        cf_gateway_transaction_id_unformatted: "nhk5kmzj",
                        tax_account_id: "",
                        tax_account_name: "",
                        tax_amount_withheld: 0.0,
                        tax_amount_withheld_formatted: "€0,00",
                        payment_type: "Rechnungszahlung",
                        settlement_status: "",
                        settlement_status_formatted: "",
                    },
                    {
                        payment_id: "98644000011319272",
                        payment_number: "2703",
                        retainerinvoice_id: "",
                        invoice_numbers: "INV-003045",
                        date: "2022-04-27",
                        date_formatted: "27 April 2022",
                        payment_mode: "Banküberweisung",
                        payment_mode_formatted: "Banküberweisung",
                        amount: 75.0,
                        amount_formatted: "€75,00",
                        bcy_amount: 75.0,
                        bcy_amount_formatted: "€75,00",
                        unused_amount: 0.0,
                        unused_amount_formatted: "€0,00",
                        bcy_unused_amount: 0.0,
                        bcy_unused_amount_formatted: "€0,00",
                        account_id: "98644000002469016",
                        account_name: "Sparkasse Nürnberg Sichteinlagen",
                        description: "",
                        reference_number: "",
                        customer_id: "98644000003496428",
                        customer_name: "Ursula Karl",
                        created_time: "2022-04-27T15:15:50+0200",
                        last_modified_time: "2022-04-27T15:15:50+0200",
                        last_four_digits: "",
                        gateway_transaction_id: "",
                        payment_gateway: "",
                        payment_gateway_formatted: "",
                        bcy_refunded_amount: 0.0,
                        bcy_refunded_amount_formatted: "€0,00",
                        applied_invoices: [],
                        has_attachment: false,
                        documents: "",
                        custom_fields_list: "",
                        tax_account_id: "",
                        tax_account_name: "",
                        tax_amount_withheld: 0.0,
                        tax_amount_withheld_formatted: "€0,00",
                        payment_type: "Rechnungszahlung",
                        settlement_status: "",
                        settlement_status_formatted: "",
                    },
                    {
                        payment_id: "98644000011316311",
                        payment_number: "2702",
                        retainerinvoice_id: "",
                        invoice_numbers: "INV-003046",
                        date: "2022-04-27",
                        date_formatted: "27 April 2022",
                        payment_mode: "onlinepayment",
                        payment_mode_formatted: "onlinepayment",
                        amount: 40.9,
                        amount_formatted: "€40,90",
                        bcy_amount: 40.9,
                        bcy_amount_formatted: "€40,90",
                        unused_amount: 0.0,
                        unused_amount_formatted: "€0,00",
                        bcy_unused_amount: 0.0,
                        bcy_unused_amount_formatted: "€0,00",
                        account_id: "98644000002101083",
                        account_name: "Braintree Pfeffer & Frost",
                        description: "",
                        reference_number: "",
                        customer_id: "98644000011315482",
                        customer_name: "Sigrid Kaufmann",
                        created_time: "2022-04-27T11:13:59+0200",
                        last_modified_time: "2022-04-27T11:13:59+0200",
                        last_four_digits: "",
                        gateway_transaction_id: "",
                        payment_gateway: "",
                        payment_gateway_formatted: "",
                        bcy_refunded_amount: 0.0,
                        bcy_refunded_amount_formatted: "€0,00",
                        applied_invoices: [],
                        has_attachment: false,
                        documents: "",
                        custom_fields_list: "",
                        cf_gateway_transaction_id: "nm9bhbkb",
                        cf_gateway_transaction_id_unformatted: "nm9bhbkb",
                        tax_account_id: "",
                        tax_account_name: "",
                        tax_amount_withheld: 0.0,
                        tax_amount_withheld_formatted: "€0,00",
                        payment_type: "Rechnungszahlung",
                        settlement_status: "",
                        settlement_status_formatted: "",
                    },
                    {
                        payment_id: "98644000010930163",
                        payment_number: "2701",
                        retainerinvoice_id: "",
                        invoice_numbers: "INV-003038",
                        date: "2022-04-20",
                        date_formatted: "20 April 2022",
                        payment_mode: "Bar",
                        payment_mode_formatted: "Bar",
                        amount: 223.6,
                        amount_formatted: "€223,60",
                        bcy_amount: 223.6,
                        bcy_amount_formatted: "€223,60",
                        unused_amount: 0.0,
                        unused_amount_formatted: "€0,00",
                        bcy_unused_amount: 0.0,
                        bcy_unused_amount_formatted: "€0,00",
                        account_id: "98644000002469016",
                        account_name: "Sparkasse Nürnberg Sichteinlagen",
                        description: "R-Nr. INV-003038 v. 11.04.2022",
                        reference_number: "",
                        customer_id: "98644000002653676",
                        customer_name: "innotech Vertriebs GmbH",
                        created_time: "2022-04-22T12:04:31+0200",
                        last_modified_time: "2022-04-22T12:04:31+0200",
                        last_four_digits: "",
                        gateway_transaction_id: "",
                        payment_gateway: "",
                        payment_gateway_formatted: "",
                        bcy_refunded_amount: 0.0,
                        bcy_refunded_amount_formatted: "€0,00",
                        applied_invoices: [],
                        has_attachment: false,
                        documents: "",
                        custom_fields_list: "",
                        tax_account_id: "",
                        tax_account_name: "",
                        tax_amount_withheld: 0.0,
                        tax_amount_withheld_formatted: "€0,00",
                        payment_type: "Rechnungszahlung",
                        settlement_status: "",
                        settlement_status_formatted: "",
                    },
                    {
                        payment_id: "98644000010180054",
                        payment_number: "2700",
                        retainerinvoice_id: "",
                        invoice_numbers: "INV-003043",
                        date: "2022-04-12",
                        date_formatted: "12 April 2022",
                        payment_mode: "onlinepayment",
                        payment_mode_formatted: "onlinepayment",
                        amount: 35.8,
                        amount_formatted: "€35,80",
                        bcy_amount: 35.8,
                        bcy_amount_formatted: "€35,80",
                        unused_amount: 0.0,
                        unused_amount_formatted: "€0,00",
                        bcy_unused_amount: 0.0,
                        bcy_unused_amount_formatted: "€0,00",
                        account_id: "98644000001621195",
                        account_name: "PayPal Pfeffer + Frost",
                        description: "",
                        reference_number: "",
                        customer_id: "98644000010183001",
                        customer_name: "Sigrun Hannemann",
                        created_time: "2022-04-12T23:31:09+0200",
                        last_modified_time: "2022-04-12T23:31:09+0200",
                        last_four_digits: "",
                        gateway_transaction_id: "",
                        payment_gateway: "",
                        payment_gateway_formatted: "",
                        bcy_refunded_amount: 0.0,
                        bcy_refunded_amount_formatted: "€0,00",
                        applied_invoices: [],
                        has_attachment: false,
                        documents: "",
                        custom_fields_list: "",
                        cf_gateway_transaction_id: "re6q07c6",
                        cf_gateway_transaction_id_unformatted: "re6q07c6",
                        tax_account_id: "",
                        tax_account_name: "",
                        tax_amount_withheld: 0.0,
                        tax_amount_withheld_formatted: "€0,00",
                        payment_type: "Rechnungszahlung",
                        settlement_status: "",
                        settlement_status_formatted: "",
                    },
                    {
                        payment_id: "98644000009790271",
                        payment_number: "2699",
                        retainerinvoice_id: "",
                        invoice_numbers: "INV-003042",
                        date: "2022-04-08",
                        date_formatted: "08 April 2022",
                        payment_mode: "Bar",
                        payment_mode_formatted: "Bar",
                        amount: 102.89,
                        amount_formatted: "€102,89",
                        bcy_amount: 102.89,
                        bcy_amount_formatted: "€102,89",
                        unused_amount: 0.0,
                        unused_amount_formatted: "€0,00",
                        bcy_unused_amount: 0.0,
                        bcy_unused_amount_formatted: "€0,00",
                        account_id: "98644000002469016",
                        account_name: "Sparkasse Nürnberg Sichteinlagen",
                        description: "RefNr. EST-000055 Bestellnr. SO-00513",
                        reference_number: "",
                        customer_id: "98644000009548049",
                        customer_name: "Stefan Nüssing",
                        created_time: "2022-04-12T17:57:00+0200",
                        last_modified_time: "2022-04-12T17:57:00+0200",
                        last_four_digits: "",
                        gateway_transaction_id: "",
                        payment_gateway: "",
                        payment_gateway_formatted: "",
                        bcy_refunded_amount: 0.0,
                        bcy_refunded_amount_formatted: "€0,00",
                        applied_invoices: [],
                        has_attachment: false,
                        documents: "",
                        custom_fields_list: "",
                        tax_account_id: "",
                        tax_account_name: "",
                        tax_amount_withheld: 0.0,
                        tax_amount_withheld_formatted: "€0,00",
                        payment_type: "Rechnungszahlung",
                        settlement_status: "",
                        settlement_status_formatted: "",
                    },
                    {
                        payment_id: "98644000010140627",
                        payment_number: "2698",
                        retainerinvoice_id: "",
                        invoice_numbers: "INV-003040",
                        date: "2022-04-12",
                        date_formatted: "12 April 2022",
                        payment_mode: "Banküberweisung",
                        payment_mode_formatted: "Banküberweisung",
                        amount: 23.9,
                        amount_formatted: "€23,90",
                        bcy_amount: 23.9,
                        bcy_amount_formatted: "€23,90",
                        unused_amount: 0.0,
                        unused_amount_formatted: "€0,00",
                        bcy_unused_amount: 0.0,
                        bcy_unused_amount_formatted: "€0,00",
                        account_id: "98644000002469016",
                        account_name: "Sparkasse Nürnberg Sichteinlagen",
                        description: "",
                        reference_number: "",
                        customer_id: "98644000010071552",
                        customer_name: "Panayota Stavreva",
                        created_time: "2022-04-12T11:42:29+0200",
                        last_modified_time: "2022-04-12T11:42:29+0200",
                        last_four_digits: "",
                        gateway_transaction_id: "",
                        payment_gateway: "",
                        payment_gateway_formatted: "",
                        bcy_refunded_amount: 0.0,
                        bcy_refunded_amount_formatted: "€0,00",
                        applied_invoices: [],
                        has_attachment: false,
                        documents: "",
                        custom_fields_list: "",
                        tax_account_id: "",
                        tax_account_name: "",
                        tax_amount_withheld: 0.0,
                        tax_amount_withheld_formatted: "€0,00",
                        payment_type: "Rechnungszahlung",
                        settlement_status: "",
                        settlement_status_formatted: "",
                    },
                    {
                        payment_id: "98644000010119088",
                        payment_number: "2697",
                        retainerinvoice_id: "",
                        invoice_numbers: "INV-003041",
                        date: "2022-04-12",
                        date_formatted: "12 April 2022",
                        payment_mode: "onlinepayment",
                        payment_mode_formatted: "onlinepayment",
                        amount: 23.9,
                        amount_formatted: "€23,90",
                        bcy_amount: 23.9,
                        bcy_amount_formatted: "€23,90",
                        unused_amount: 0.0,
                        unused_amount_formatted: "€0,00",
                        bcy_unused_amount: 0.0,
                        bcy_unused_amount_formatted: "€0,00",
                        account_id: "98644000001621195",
                        account_name: "PayPal Pfeffer + Frost",
                        description: "",
                        reference_number: "",
                        customer_id: "98644000010120001",
                        customer_name: "Verena Strey",
                        created_time: "2022-04-12T10:39:50+0200",
                        last_modified_time: "2022-04-12T10:39:50+0200",
                        last_four_digits: "",
                        gateway_transaction_id: "",
                        payment_gateway: "",
                        payment_gateway_formatted: "",
                        bcy_refunded_amount: 0.0,
                        bcy_refunded_amount_formatted: "€0,00",
                        applied_invoices: [],
                        has_attachment: false,
                        documents: "",
                        custom_fields_list: "",
                        cf_gateway_transaction_id: "ktm4kyz5",
                        cf_gateway_transaction_id_unformatted: "ktm4kyz5",
                        tax_account_id: "",
                        tax_account_name: "",
                        tax_amount_withheld: 0.0,
                        tax_amount_withheld_formatted: "€0,00",
                        payment_type: "Rechnungszahlung",
                        settlement_status: "",
                        settlement_status_formatted: "",
                    },
                    {
                        payment_id: "98644000009844110",
                        payment_number: "2696",
                        retainerinvoice_id: "",
                        invoice_numbers: "INV-003037",
                        date: "2022-04-08",
                        date_formatted: "08 April 2022",
                        payment_mode: "onlinepayment",
                        payment_mode_formatted: "onlinepayment",
                        amount: 17.8,
                        amount_formatted: "€17,80",
                        bcy_amount: 17.8,
                        bcy_amount_formatted: "€17,80",
                        unused_amount: 0.0,
                        unused_amount_formatted: "€0,00",
                        bcy_unused_amount: 0.0,
                        bcy_unused_amount_formatted: "€0,00",
                        account_id: "98644000001621195",
                        account_name: "PayPal Pfeffer + Frost",
                        description: "",
                        reference_number: "",
                        customer_id: "98644000009844001",
                        customer_name: "Patrick Linke",
                        created_time: "2022-04-08T21:14:21+0200",
                        last_modified_time: "2022-04-08T21:14:21+0200",
                        last_four_digits: "",
                        gateway_transaction_id: "",
                        payment_gateway: "",
                        payment_gateway_formatted: "",
                        bcy_refunded_amount: 0.0,
                        bcy_refunded_amount_formatted: "€0,00",
                        applied_invoices: [],
                        has_attachment: false,
                        documents: "",
                        custom_fields_list: "",
                        cf_gateway_transaction_id: "7e3byw0t",
                        cf_gateway_transaction_id_unformatted: "7e3byw0t",
                        tax_account_id: "",
                        tax_account_name: "",
                        tax_amount_withheld: 0.0,
                        tax_amount_withheld_formatted: "€0,00",
                        payment_type: "Rechnungszahlung",
                        settlement_status: "",
                        settlement_status_formatted: "",
                    },
                    {
                        payment_id: "98644000009665153",
                        payment_number: "2695",
                        retainerinvoice_id: "",
                        invoice_numbers: "INV-003035",
                        date: "2022-04-06",
                        date_formatted: "06 April 2022",
                        payment_mode: "onlinepayment",
                        payment_mode_formatted: "onlinepayment",
                        amount: 50.4,
                        amount_formatted: "€50,40",
                        bcy_amount: 50.4,
                        bcy_amount_formatted: "€50,40",
                        unused_amount: 0.0,
                        unused_amount_formatted: "€0,00",
                        bcy_unused_amount: 0.0,
                        bcy_unused_amount_formatted: "€0,00",
                        account_id: "98644000001621195",
                        account_name: "PayPal Pfeffer + Frost",
                        description: "",
                        reference_number: "",
                        customer_id: "98644000003496978",
                        customer_name: "Vera Bauer",
                        created_time: "2022-04-06T21:33:20+0200",
                        last_modified_time: "2022-04-06T21:33:20+0200",
                        last_four_digits: "",
                        gateway_transaction_id: "",
                        payment_gateway: "",
                        payment_gateway_formatted: "",
                        bcy_refunded_amount: 0.0,
                        bcy_refunded_amount_formatted: "€0,00",
                        applied_invoices: [],
                        has_attachment: false,
                        documents: "",
                        custom_fields_list: "",
                        cf_gateway_transaction_id: "40c175yx",
                        cf_gateway_transaction_id_unformatted: "40c175yx",
                        tax_account_id: "",
                        tax_account_name: "",
                        tax_amount_withheld: 0.0,
                        tax_amount_withheld_formatted: "€0,00",
                        payment_type: "Rechnungszahlung",
                        settlement_status: "",
                        settlement_status_formatted: "",
                    },
                    {
                        payment_id: "98644000009587764",
                        payment_number: "2694",
                        retainerinvoice_id: "",
                        invoice_numbers: "INV-003034",
                        date: "2022-04-05",
                        date_formatted: "05 April 2022",
                        payment_mode: "onlinepayment",
                        payment_mode_formatted: "onlinepayment",
                        amount: 62.8,
                        amount_formatted: "€62,80",
                        bcy_amount: 62.8,
                        bcy_amount_formatted: "€62,80",
                        unused_amount: 0.0,
                        unused_amount_formatted: "€0,00",
                        bcy_unused_amount: 0.0,
                        bcy_unused_amount_formatted: "€0,00",
                        account_id: "98644000001621195",
                        account_name: "PayPal Pfeffer + Frost",
                        description: "",
                        reference_number: "",
                        customer_id: "98644000009589230",
                        customer_name: "Hafner & Kohl",
                        created_time: "2022-04-05T21:27:48+0200",
                        last_modified_time: "2022-04-05T21:27:48+0200",
                        last_four_digits: "",
                        gateway_transaction_id: "",
                        payment_gateway: "",
                        payment_gateway_formatted: "",
                        bcy_refunded_amount: 0.0,
                        bcy_refunded_amount_formatted: "€0,00",
                        applied_invoices: [],
                        has_attachment: false,
                        documents: "",
                        custom_fields_list: "",
                        cf_gateway_transaction_id: "k6s1qa17",
                        cf_gateway_transaction_id_unformatted: "k6s1qa17",
                        tax_account_id: "",
                        tax_account_name: "",
                        tax_amount_withheld: 0.0,
                        tax_amount_withheld_formatted: "€0,00",
                        payment_type: "Rechnungszahlung",
                        settlement_status: "",
                        settlement_status_formatted: "",
                    },
                    {
                        payment_id: "98644000009546368",
                        payment_number: "2693",
                        retainerinvoice_id: "",
                        invoice_numbers: "INV-003033",
                        date: "2022-01-19",
                        date_formatted: "19 Januar 2022",
                        payment_mode: "PayPal",
                        payment_mode_formatted: "PayPal",
                        amount: 19.3,
                        amount_formatted: "€19,30",
                        bcy_amount: 19.3,
                        bcy_amount_formatted: "€19,30",
                        unused_amount: 0.0,
                        unused_amount_formatted: "€0,00",
                        bcy_unused_amount: 0.0,
                        bcy_unused_amount_formatted: "€0,00",
                        account_id: "98644000001621195",
                        account_name: "PayPal Pfeffer + Frost",
                        description: "",
                        reference_number: "",
                        customer_id: "98644000005632353",
                        customer_name: "Angelika Ley",
                        created_time: "2022-04-05T15:47:00+0200",
                        last_modified_time: "2022-04-05T15:47:00+0200",
                        last_four_digits: "",
                        gateway_transaction_id: "",
                        payment_gateway: "",
                        payment_gateway_formatted: "",
                        bcy_refunded_amount: 0.0,
                        bcy_refunded_amount_formatted: "€0,00",
                        applied_invoices: [],
                        has_attachment: false,
                        documents: "",
                        custom_fields_list: "",
                        cf_gateway_transaction_id: "mjja6e33",
                        cf_gateway_transaction_id_unformatted: "mjja6e33",
                        tax_account_id: "",
                        tax_account_name: "",
                        tax_amount_withheld: 0.0,
                        tax_amount_withheld_formatted: "€0,00",
                        payment_type: "Rechnungszahlung",
                        settlement_status: "",
                        settlement_status_formatted: "",
                    },
                    {
                        payment_id: "98644000009546215",
                        payment_number: "2692",
                        retainerinvoice_id: "",
                        invoice_numbers: "INV-003032",
                        date: "2021-12-02",
                        date_formatted: "02 Dezember 2021",
                        payment_mode: "Braintree",
                        payment_mode_formatted: "Braintree",
                        amount: 36.35,
                        amount_formatted: "€36,35",
                        bcy_amount: 36.35,
                        bcy_amount_formatted: "€36,35",
                        unused_amount: 0.0,
                        unused_amount_formatted: "€0,00",
                        bcy_unused_amount: 0.0,
                        bcy_unused_amount_formatted: "€0,00",
                        account_id: "98644000002101083",
                        account_name: "Braintree Pfeffer & Frost",
                        description: "",
                        reference_number: "",
                        customer_id: "98644000004217431",
                        customer_name: "Wiltrud Krempchen",
                        created_time: "2022-04-05T14:16:36+0200",
                        last_modified_time: "2022-04-05T14:16:50+0200",
                        last_four_digits: "",
                        gateway_transaction_id: "",
                        payment_gateway: "",
                        payment_gateway_formatted: "",
                        bcy_refunded_amount: 0.0,
                        bcy_refunded_amount_formatted: "€0,00",
                        applied_invoices: [],
                        has_attachment: false,
                        documents: "",
                        custom_fields_list: "",
                        cf_gateway_transaction_id: "r4jr3ztv",
                        cf_gateway_transaction_id_unformatted: "r4jr3ztv",
                        tax_account_id: "",
                        tax_account_name: "",
                        tax_amount_withheld: 0.0,
                        tax_amount_withheld_formatted: "€0,00",
                        payment_type: "Rechnungszahlung",
                        settlement_status: "",
                        settlement_status_formatted: "",
                    },
                    {
                        payment_id: "98644000009546099",
                        payment_number: "2691",
                        retainerinvoice_id: "",
                        invoice_numbers: "INV-003031",
                        date: "2021-12-02",
                        date_formatted: "02 Dezember 2021",
                        payment_mode: "PayPal",
                        payment_mode_formatted: "PayPal",
                        amount: 59.11,
                        amount_formatted: "€59,11",
                        bcy_amount: 59.11,
                        bcy_amount_formatted: "€59,11",
                        unused_amount: 0.0,
                        unused_amount_formatted: "€0,00",
                        bcy_unused_amount: 0.0,
                        bcy_unused_amount_formatted: "€0,00",
                        account_id: "98644000001621195",
                        account_name: "PayPal Pfeffer + Frost",
                        description: "",
                        reference_number: "",
                        customer_id: "98644000004232865",
                        customer_name: "Natascha Fischer",
                        created_time: "2022-04-05T14:15:04+0200",
                        last_modified_time: "2022-04-05T14:15:04+0200",
                        last_four_digits: "",
                        gateway_transaction_id: "",
                        payment_gateway: "",
                        payment_gateway_formatted: "",
                        bcy_refunded_amount: 0.0,
                        bcy_refunded_amount_formatted: "€0,00",
                        applied_invoices: [],
                        has_attachment: false,
                        documents: "",
                        custom_fields_list: "",
                        tax_account_id: "",
                        tax_account_name: "",
                        tax_amount_withheld: 0.0,
                        tax_amount_withheld_formatted: "€0,00",
                        payment_type: "Rechnungszahlung",
                        settlement_status: "",
                        settlement_status_formatted: "",
                    },
                    {
                        payment_id: "98644000009498208",
                        payment_number: "2690",
                        retainerinvoice_id: "",
                        invoice_numbers: "INV-002049",
                        date: "2021-12-06",
                        date_formatted: "06 Dezember 2021",
                        payment_mode: "PayPal",
                        payment_mode_formatted: "PayPal",
                        amount: 64.36,
                        amount_formatted: "€64,36",
                        bcy_amount: 64.36,
                        bcy_amount_formatted: "€64,36",
                        unused_amount: 0.0,
                        unused_amount_formatted: "€0,00",
                        bcy_unused_amount: 0.0,
                        bcy_unused_amount_formatted: "€0,00",
                        account_id: "98644000001621195",
                        account_name: "PayPal Pfeffer + Frost",
                        description: "",
                        reference_number: "",
                        customer_id: "98644000004404609",
                        customer_name: "Nina Schönenborn",
                        created_time: "2022-04-05T13:05:07+0200",
                        last_modified_time: "2022-04-05T13:05:07+0200",
                        last_four_digits: "",
                        gateway_transaction_id: "",
                        payment_gateway: "",
                        payment_gateway_formatted: "",
                        bcy_refunded_amount: 0.0,
                        bcy_refunded_amount_formatted: "€0,00",
                        applied_invoices: [],
                        has_attachment: false,
                        documents: "",
                        custom_fields_list: "",
                        tax_account_id: "",
                        tax_account_name: "",
                        tax_amount_withheld: 0.0,
                        tax_amount_withheld_formatted: "€0,00",
                        payment_type: "Rechnungszahlung",
                        settlement_status: "",
                        settlement_status_formatted: "",
                    },
                    {
                        payment_id: "98644000009498112",
                        payment_number: "2689",
                        retainerinvoice_id: "",
                        invoice_numbers: "INV-002160",
                        date: "2021-12-09",
                        date_formatted: "09 Dezember 2021",
                        payment_mode: "Braintree",
                        payment_mode_formatted: "Braintree",
                        amount: 24.84,
                        amount_formatted: "€24,84",
                        bcy_amount: 24.84,
                        bcy_amount_formatted: "€24,84",
                        unused_amount: 0.0,
                        unused_amount_formatted: "€0,00",
                        bcy_unused_amount: 0.0,
                        bcy_unused_amount_formatted: "€0,00",
                        account_id: "98644000002101083",
                        account_name: "Braintree Pfeffer & Frost",
                        description: "",
                        reference_number: "",
                        customer_id: "98644000004588413",
                        customer_name: "Ashlyn Benn",
                        created_time: "2022-04-05T13:03:15+0200",
                        last_modified_time: "2022-04-05T13:03:15+0200",
                        last_four_digits: "",
                        gateway_transaction_id: "",
                        payment_gateway: "",
                        payment_gateway_formatted: "",
                        bcy_refunded_amount: 0.0,
                        bcy_refunded_amount_formatted: "€0,00",
                        applied_invoices: [],
                        has_attachment: false,
                        documents: "",
                        custom_fields_list: "",
                        cf_gateway_transaction_id: "5edzetwk",
                        cf_gateway_transaction_id_unformatted: "5edzetwk",
                        tax_account_id: "",
                        tax_account_name: "",
                        tax_amount_withheld: 0.0,
                        tax_amount_withheld_formatted: "€0,00",
                        payment_type: "Rechnungszahlung",
                        settlement_status: "",
                        settlement_status_formatted: "",
                    },
                    {
                        payment_id: "98644000009453387",
                        payment_number: "2688",
                        retainerinvoice_id: "",
                        invoice_numbers: "INV-003030",
                        date: "2022-04-04",
                        date_formatted: "04 April 2022",
                        payment_mode: "onlinepayment",
                        payment_mode_formatted: "onlinepayment",
                        amount: 40.9,
                        amount_formatted: "€40,90",
                        bcy_amount: 40.9,
                        bcy_amount_formatted: "€40,90",
                        unused_amount: 0.0,
                        unused_amount_formatted: "€0,00",
                        bcy_unused_amount: 0.0,
                        bcy_unused_amount_formatted: "€0,00",
                        account_id: "98644000001621195",
                        account_name: "PayPal Pfeffer + Frost",
                        description: "",
                        reference_number: "",
                        customer_id: "98644000009451653",
                        customer_name: "Jana Wollschlaeger",
                        created_time: "2022-04-04T22:35:35+0200",
                        last_modified_time: "2022-04-04T22:35:35+0200",
                        last_four_digits: "",
                        gateway_transaction_id: "",
                        payment_gateway: "",
                        payment_gateway_formatted: "",
                        bcy_refunded_amount: 0.0,
                        bcy_refunded_amount_formatted: "€0,00",
                        applied_invoices: [],
                        has_attachment: false,
                        documents: "",
                        custom_fields_list: "",
                        cf_gateway_transaction_id: "frgx851s",
                        cf_gateway_transaction_id_unformatted: "frgx851s",
                        tax_account_id: "",
                        tax_account_name: "",
                        tax_amount_withheld: 0.0,
                        tax_amount_withheld_formatted: "€0,00",
                        payment_type: "Rechnungszahlung",
                        settlement_status: "",
                        settlement_status_formatted: "",
                    },
                    {
                        payment_id: "98644000009423126",
                        payment_number: "2687",
                        retainerinvoice_id: "",
                        invoice_numbers: "INV-003028",
                        date: "2022-04-04",
                        date_formatted: "04 April 2022",
                        payment_mode: "onlinepayment",
                        payment_mode_formatted: "onlinepayment",
                        amount: 82.7,
                        amount_formatted: "€82,70",
                        bcy_amount: 82.7,
                        bcy_amount_formatted: "€82,70",
                        unused_amount: 0.0,
                        unused_amount_formatted: "€0,00",
                        bcy_unused_amount: 0.0,
                        bcy_unused_amount_formatted: "€0,00",
                        account_id: "98644000001621195",
                        account_name: "PayPal Pfeffer + Frost",
                        description: "",
                        reference_number: "",
                        customer_id: "98644000009422304",
                        customer_name: "Christopher Hauswald",
                        created_time: "2022-04-04T10:40:03+0200",
                        last_modified_time: "2022-04-04T10:40:03+0200",
                        last_four_digits: "",
                        gateway_transaction_id: "",
                        payment_gateway: "",
                        payment_gateway_formatted: "",
                        bcy_refunded_amount: 0.0,
                        bcy_refunded_amount_formatted: "€0,00",
                        applied_invoices: [],
                        has_attachment: false,
                        documents: "",
                        custom_fields_list: "",
                        cf_gateway_transaction_id: "8z27qcdq",
                        cf_gateway_transaction_id_unformatted: "8z27qcdq",
                        tax_account_id: "",
                        tax_account_name: "",
                        tax_amount_withheld: 0.0,
                        tax_amount_withheld_formatted: "€0,00",
                        payment_type: "Rechnungszahlung",
                        settlement_status: "",
                        settlement_status_formatted: "",
                    },
                ]),
        },
    } as unknown as Zoho;

    beforeAll(async () => {
        zohoApp = (await prismaClient.zohoApp.findUnique({
            where: {
                id: "test",
            },
            include: { tenant: true },
        }))!;
        if (!zohoApp) throw new Error("No testing Zoho App found!");
        if (!zohoApp.tenantId)
            throw new Error("No tenant configured for Zoho App!");
        zoho = new Zoho(
            await ZohoApiClient.fromOAuth({
                orgId: zohoApp.orgId,
                client: { id: zohoApp.clientId, secret: zohoApp.clientSecret },
            }),
        );
        zohoPaymentLogger = new AssertionLogger();
        // eslint-disable-next-line @typescript-eslint/no-unused-vars, no-new
        new ZohoPaymentSyncService({
            zoho,
            logger: zohoPaymentLogger,
            db: new PrismaClient(),
            zohoApp,
            createdTimeOffset: 1,
        });
    });

    test("It should work to sync Zoho Payments with internal ECI DB", async () => {
        const xx = new ZohoPaymentSyncService({
            zoho: mockedZohoClient,
            logger: new NoopLogger(),
            db: new PrismaClient(),
            zohoApp,
            createdTimeOffset: 1,
        });
        await xx.syncToECI();
    }, 90000);

    // Hard to test in isolation because of the many dependecies.
    // Therefore see ../test/index.test.ts for a Test of zohoPaymentSyncService with other dependend services
    // zohoPaymentSyncService.syncFromECI();
});
