apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
spec:
  clusterIP: None
  ports:
    - name: web
      port: 3000
      protocol: TCP
      targetPort: 3000
  selector:
    {{- include "schemabase-api.selectorLabels" . | nindent 4 }}
  sessionAffinity: None
  type: ClusterIP