query products($first: Int!, $channel: String) {
  products(first: $first, channel: $channel) {
    edges {
      node {
        seoDescription
        name
        seoTitle
        isAvailableForPurchase
        descriptionJson
        slug
        weight {
          unit
          value
        }
        images {
          id
          url
        }
        metadata {
          key
          value
        }
        attributes {
          attribute {
            id
            name
          }
          values {
            id
            name
          }
        }
        productType {
          name
          id
          hasVariants
        }
        variants {
          id
          name
          sku
          quantityAvailable
          weight {
            unit
            value
          }
          metadata {
            key
            value
          }
          pricing {
            priceUndiscounted {
              gross {
                amount
                currency
              }
            }
            price {
              gross {
                amount
                currency
              }
              net {
                amount
              }
            }
            onSale
            discount {
              gross {
                amount
              }
            }
          }
          images {
            url
          }
        }
      }
    }
  }
}
