apiVersion: v1
kind: Secret
metadata:
  name: eci-logdrain-secrets
type: Opaque
data:
  DATABASE_URL: {{ .Values.databaseUrl | b64enc | quote }}
  DATABASE_URL_POOL: {{ .Values.databaseUrlPool | b64enc | quote }}
  REDIS_HOST: {{ .Values.redis.host | b64enc | quote }}
  REDIS_PORT: {{ .Values.redis.port | toString | b64enc | quote }}
  REDIS_PASSWORD: {{ .Values.redis.password | b64enc | quote }}
  ELASTIC_LOGGING_SERVER: {{ .Values.elasticsearch.host | b64enc | quote }}
  ELASTIC_LOGGING_USERNAME: {{ .Values.elasticsearch.username | b64enc | quote }}
  ELASTIC_LOGGING_PASSWORD: {{ .Values.elasticsearch.password | b64enc | quote }}
  LOGDRAIN_CLIENT_ID: {{ .Values.logdrain.client.id | b64enc | quote}}
  LOGDRAIN_CLIENT_SECRET: {{ .Values.logdrain.client.secret | b64enc | quote}}
  LOGDRAIN_REDIRECT_URI: {{ .Values.logdrain.redirectUri | b64enc | quote }}