apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
spec:
  clusterIP: None
  ports:
    - name: web
      port: 13000
      protocol: TCP
      targetPort: 13000
  selector:
    {{- include "bullboard.selectorLabels" . | nindent 4 }}
  sessionAffinity: None
  type: ClusterIP