import { NoopLogger } from "@eci/pkg/logger";
import { PrismaClient } from "@eci/pkg/prisma";
import { beforeEach, describe, jest, test, beforeAll } from "@jest/globals";
import { Zoho } from "@trieb.work/zoho-ts";
import { ZohoContactSyncService } from "./contacts";

let zohoApp: any;

beforeEach(() => {
  jest.clearAllMocks();
});

describe("Zoho Inventory Contact Sync", () => {
  const prismaClient = new PrismaClient();

  const mockedZohoClient = {
    contact: {
      list: async () =>
        await Promise.resolve([
          {
            "contact_id": "116240000000631001",
            "contact_name": "Christina Lang",
            "customer_name": "Christina Lang",
            "company_name": "",
            "website": "",
            "language_code": "en",
            "language_code_formatted": "English",
            "contact_type": "customer",
            "contact_type_formatted": "Customer",
            "status": "active",
            "status_formatted": "Active",
            "customer_sub_type": "individual",
            "customer_sub_type_formatted": "Individual",
            "source": "user",
            "source_formatted": "User",
            "is_linked_with_zohocrm": false,
            "payment_terms": 0,
            "payment_terms_label": "Due on Receipt",
            "currency_id": "116240000000000071",
            "twitter": "",
            "facebook": "",
            "currency_code": "EUR",
            "outstanding_receivable_amount": 0,
            "outstanding_receivable_amount_formatted": "€0,00",
            "outstanding_receivable_amount_bcy": 0,
            "outstanding_receivable_amount_bcy_formatted": "€0,00",
            "unused_credits_receivable_amount": 0,
            "unused_credits_receivable_amount_formatted": "€0,00",
            "unused_credits_receivable_amount_bcy": 0,
            "unused_credits_receivable_amount_bcy_formatted": "€0,00",
            "first_name": "Christina",
            "last_name": "Lang",
            "email": "zinkljannik+chri@gmail.com",
            "phone": "",
            "mobile": "",
            "is_portal_enabled": false,
            "portal_status": "disabled",
            "created_time": "2021-05-18T15:53:49+0200",
            "created_time_formatted": "18-05-2021",
            "last_modified_time": "2022-08-23T17:18:31+0200",
            "last_modified_time_formatted": "23-08-2022",
            "custom_fields": [
              {
                "field_id": "116240000000356070",
                "customfield_id": "116240000000356070",
                "show_in_store": false,
                "show_in_portal": false,
                "is_active": true,
                "index": 1,
                "label": "Shipment Notifications disabled",
                "show_on_pdf": false,
                "edit_on_portal": false,
                "edit_on_store": false,
                "api_name": "cf_shipment_notifications_disa",
                "show_in_all_pdf": false,
                "value_formatted": "false",
                "search_entity": "contact",
                "data_type": "check_box",
                "placeholder": "cf_shipment_notifications_disa",
                "value": false,
                "is_dependent_field": false
              }
            ],
            "cf_shipment_notifications_disa": "false",
            "cf_shipment_notifications_disa_unformatted": false,
            "custom_field_hash": {
              "cf_shipment_notifications_disa": "false",
              "cf_shipment_notifications_disa_unformatted": false
            },
            "ach_supported": false,
            "has_attachment": false
          },
          {
            "contact_id": "116240000001504002",
            "contact_name": "Jannik Zinkl",
            "customer_name": "Jannik Zinkl",
            "company_name": "",
            "website": "",
            "language_code": "en",
            "language_code_formatted": "English",
            "contact_type": "customer",
            "contact_type_formatted": "Customer",
            "status": "active",
            "status_formatted": "Active",
            "customer_sub_type": "individual",
            "customer_sub_type_formatted": "Individual",
            "source": "api",
            "source_formatted": "API",
            "is_linked_with_zohocrm": false,
            "payment_terms": 0,
            "payment_terms_label": "Due On Receipt",
            "currency_id": "116240000000000071",
            "twitter": "",
            "facebook": "",
            "currency_code": "EUR",
            "outstanding_receivable_amount": 0,
            "outstanding_receivable_amount_formatted": "€0,00",
            "outstanding_receivable_amount_bcy": 0,
            "outstanding_receivable_amount_bcy_formatted": "€0,00",
            "unused_credits_receivable_amount": 0,
            "unused_credits_receivable_amount_formatted": "€0,00",
            "unused_credits_receivable_amount_bcy": 0,
            "unused_credits_receivable_amount_bcy_formatted": "€0,00",
            "first_name": "Jannik",
            "last_name": "Zinkl",
            "email": "zinkljannik@gmail.com",
            "phone": "",
            "mobile": "",
            "is_portal_enabled": false,
            "portal_status": "disabled",
            "created_time": "2022-04-20T10:39:57+0200",
            "created_time_formatted": "20-04-2022",
            "last_modified_time": "2022-04-20T11:08:35+0200",
            "last_modified_time_formatted": "20-04-2022",
            "custom_fields": [
              {
                "field_id": "116240000000356070",
                "customfield_id": "116240000000356070",
                "show_in_store": false,
                "show_in_portal": false,
                "is_active": true,
                "index": 1,
                "label": "Shipment Notifications disabled",
                "show_on_pdf": false,
                "edit_on_portal": false,
                "edit_on_store": false,
                "api_name": "cf_shipment_notifications_disa",
                "show_in_all_pdf": false,
                "value_formatted": "false",
                "search_entity": "contact",
                "data_type": "check_box",
                "placeholder": "cf_shipment_notifications_disa",
                "value": false,
                "is_dependent_field": false
              }
            ],
            "cf_shipment_notifications_disa": "false",
            "cf_shipment_notifications_disa_unformatted": false,
            "custom_field_hash": {
              "cf_shipment_notifications_disa": "false",
              "cf_shipment_notifications_disa_unformatted": false
            },
            "ach_supported": false,
            "has_attachment": false
          },
          {
            "contact_id": "116240000001499002",
            "contact_name": "Linda Thomas",
            "customer_name": "Linda Thomas",
            "company_name": "",
            "website": "",
            "language_code": "en",
            "language_code_formatted": "English",
            "contact_type": "customer",
            "contact_type_formatted": "Customer",
            "status": "active",
            "status_formatted": "Active",
            "customer_sub_type": "individual",
            "customer_sub_type_formatted": "Individual",
            "source": "api",
            "source_formatted": "API",
            "is_linked_with_zohocrm": false,
            "payment_terms": 0,
            "payment_terms_label": "Due on Receipt",
            "currency_id": "116240000000000071",
            "twitter": "",
            "facebook": "",
            "currency_code": "EUR",
            "outstanding_receivable_amount": 0,
            "outstanding_receivable_amount_formatted": "€0,00",
            "outstanding_receivable_amount_bcy": 0,
            "outstanding_receivable_amount_bcy_formatted": "€0,00",
            "unused_credits_receivable_amount": 40,
            "unused_credits_receivable_amount_formatted": "€40,00",
            "unused_credits_receivable_amount_bcy": 40,
            "unused_credits_receivable_amount_bcy_formatted": "€40,00",
            "first_name": "Linda",
            "last_name": "Thomas",
            "email": "megan.chang@example.com",
            "phone": "",
            "mobile": "",
            "is_portal_enabled": false,
            "portal_status": "disabled",
            "created_time": "2022-04-19T15:59:37+0200",
            "created_time_formatted": "19-04-2022",
            "last_modified_time": "2022-06-01T15:37:24+0200",
            "last_modified_time_formatted": "01-06-2022",
            "custom_fields": [
              {
                "field_id": "116240000000356070",
                "customfield_id": "116240000000356070",
                "show_in_store": false,
                "show_in_portal": false,
                "is_active": true,
                "index": 1,
                "label": "Shipment Notifications disabled",
                "show_on_pdf": false,
                "edit_on_portal": false,
                "edit_on_store": false,
                "api_name": "cf_shipment_notifications_disa",
                "show_in_all_pdf": false,
                "value_formatted": "false",
                "search_entity": "contact",
                "data_type": "check_box",
                "placeholder": "cf_shipment_notifications_disa",
                "value": false,
                "is_dependent_field": false
              }
            ],
            "cf_shipment_notifications_disa": "false",
            "cf_shipment_notifications_disa_unformatted": false,
            "custom_field_hash": {
              "cf_shipment_notifications_disa": "false",
              "cf_shipment_notifications_disa_unformatted": false
            },
            "ach_supported": false,
            "has_attachment": false
          },
          {
            "contact_id": "116240000001558532",
            "contact_name": "Test Run User Zoho TS",
            "customer_name": "Test Run User Zoho TS",
            "company_name": "",
            "website": "",
            "language_code": "",
            "language_code_formatted": "",
            "contact_type": "customer",
            "contact_type_formatted": "Customer",
            "status": "active",
            "status_formatted": "Active",
            "customer_sub_type": "individual",
            "customer_sub_type_formatted": "Individual",
            "source": "api",
            "source_formatted": "API",
            "is_linked_with_zohocrm": false,
            "payment_terms": 0,
            "payment_terms_label": "Due On Receipt",
            "currency_id": "116240000000000071",
            "twitter": "",
            "facebook": "",
            "currency_code": "EUR",
            "outstanding_receivable_amount": 0,
            "outstanding_receivable_amount_formatted": "€0,00",
            "outstanding_receivable_amount_bcy": 0,
            "outstanding_receivable_amount_bcy_formatted": "€0,00",
            "unused_credits_receivable_amount": 0,
            "unused_credits_receivable_amount_formatted": "€0,00",
            "unused_credits_receivable_amount_bcy": 0,
            "unused_credits_receivable_amount_bcy_formatted": "€0,00",
            "first_name": "",
            "last_name": "",
            "email": "",
            "phone": "",
            "mobile": "",
            "is_portal_enabled": false,
            "portal_status": "disabled",
            "created_time": "2022-06-01T16:01:11+0200",
            "created_time_formatted": "01-06-2022",
            "last_modified_time": "2022-06-01T16:01:11+0200",
            "last_modified_time_formatted": "01-06-2022",
            "custom_fields": [
              {
                "field_id": "116240000000356070",
                "customfield_id": "116240000000356070",
                "show_in_store": false,
                "show_in_portal": false,
                "is_active": true,
                "index": 1,
                "label": "Shipment Notifications disabled",
                "show_on_pdf": false,
                "edit_on_portal": false,
                "edit_on_store": false,
                "api_name": "cf_shipment_notifications_disa",
                "show_in_all_pdf": false,
                "value_formatted": "false",
                "search_entity": "contact",
                "data_type": "check_box",
                "placeholder": "cf_shipment_notifications_disa",
                "value": false,
                "is_dependent_field": false
              }
            ],
            "cf_shipment_notifications_disa": "false",
            "cf_shipment_notifications_disa_unformatted": false,
            "custom_field_hash": {
              "cf_shipment_notifications_disa": "false",
              "cf_shipment_notifications_disa_unformatted": false
            },
            "ach_supported": false,
            "has_attachment": false
          },
          {
            "contact_id": "116240000001562160",
            "contact_name": "Test Run User Zoho TS",
            "customer_name": "Test Run User Zoho TS",
            "company_name": "",
            "website": "",
            "language_code": "",
            "language_code_formatted": "",
            "contact_type": "customer",
            "contact_type_formatted": "Customer",
            "status": "active",
            "status_formatted": "Active",
            "customer_sub_type": "individual",
            "customer_sub_type_formatted": "Individual",
            "source": "api",
            "source_formatted": "API",
            "is_linked_with_zohocrm": false,
            "payment_terms": 0,
            "payment_terms_label": "Due On Receipt",
            "currency_id": "116240000000000071",
            "twitter": "",
            "facebook": "",
            "currency_code": "EUR",
            "outstanding_receivable_amount": 78.23,
            "outstanding_receivable_amount_formatted": "€78,23",
            "outstanding_receivable_amount_bcy": 78.23,
            "outstanding_receivable_amount_bcy_formatted": "€78,23",
            "unused_credits_receivable_amount": 0,
            "unused_credits_receivable_amount_formatted": "€0,00",
            "unused_credits_receivable_amount_bcy": 0,
            "unused_credits_receivable_amount_bcy_formatted": "€0,00",
            "first_name": "",
            "last_name": "",
            "email": "",
            "phone": "",
            "mobile": "",
            "is_portal_enabled": false,
            "portal_status": "disabled",
            "created_time": "2022-06-01T16:08:48+0200",
            "created_time_formatted": "01-06-2022",
            "last_modified_time": "2022-06-01T16:08:52+0200",
            "last_modified_time_formatted": "01-06-2022",
            "custom_fields": [
              {
                "field_id": "116240000000356070",
                "customfield_id": "116240000000356070",
                "show_in_store": false,
                "show_in_portal": false,
                "is_active": true,
                "index": 1,
                "label": "Shipment Notifications disabled",
                "show_on_pdf": false,
                "edit_on_portal": false,
                "edit_on_store": false,
                "api_name": "cf_shipment_notifications_disa",
                "show_in_all_pdf": false,
                "value_formatted": "false",
                "search_entity": "contact",
                "data_type": "check_box",
                "placeholder": "cf_shipment_notifications_disa",
                "value": false,
                "is_dependent_field": false
              }
            ],
            "cf_shipment_notifications_disa": "false",
            "cf_shipment_notifications_disa_unformatted": false,
            "custom_field_hash": {
              "cf_shipment_notifications_disa": "false",
              "cf_shipment_notifications_disa_unformatted": false
            },
            "ach_supported": false,
            "has_attachment": false
          },
          {
            "contact_id": "116240000001557330",
            "contact_name": "Test Run User Zoho TS",
            "customer_name": "Test Run User Zoho TS",
            "company_name": "",
            "website": "",
            "language_code": "",
            "language_code_formatted": "",
            "contact_type": "customer",
            "contact_type_formatted": "Customer",
            "status": "active",
            "status_formatted": "Active",
            "customer_sub_type": "individual",
            "customer_sub_type_formatted": "Individual",
            "source": "api",
            "source_formatted": "API",
            "is_linked_with_zohocrm": false,
            "payment_terms": 0,
            "payment_terms_label": "Due On Receipt",
            "currency_id": "116240000000000071",
            "twitter": "",
            "facebook": "",
            "currency_code": "EUR",
            "outstanding_receivable_amount": 0,
            "outstanding_receivable_amount_formatted": "€0,00",
            "outstanding_receivable_amount_bcy": 0,
            "outstanding_receivable_amount_bcy_formatted": "€0,00",
            "unused_credits_receivable_amount": 0,
            "unused_credits_receivable_amount_formatted": "€0,00",
            "unused_credits_receivable_amount_bcy": 0,
            "unused_credits_receivable_amount_bcy_formatted": "€0,00",
            "first_name": "",
            "last_name": "",
            "email": "",
            "phone": "",
            "mobile": "",
            "is_portal_enabled": false,
            "portal_status": "disabled",
            "created_time": "2022-06-01T15:39:56+0200",
            "created_time_formatted": "01-06-2022",
            "last_modified_time": "2022-06-01T15:39:56+0200",
            "last_modified_time_formatted": "01-06-2022",
            "custom_fields": [
              {
                "field_id": "116240000000356070",
                "customfield_id": "116240000000356070",
                "show_in_store": false,
                "show_in_portal": false,
                "is_active": true,
                "index": 1,
                "label": "Shipment Notifications disabled",
                "show_on_pdf": false,
                "edit_on_portal": false,
                "edit_on_store": false,
                "api_name": "cf_shipment_notifications_disa",
                "show_in_all_pdf": false,
                "value_formatted": "false",
                "search_entity": "contact",
                "data_type": "check_box",
                "placeholder": "cf_shipment_notifications_disa",
                "value": false,
                "is_dependent_field": false
              }
            ],
            "cf_shipment_notifications_disa": "false",
            "cf_shipment_notifications_disa_unformatted": false,
            "custom_field_hash": {
              "cf_shipment_notifications_disa": "false",
              "cf_shipment_notifications_disa_unformatted": false
            },
            "ach_supported": false,
            "has_attachment": false
          },
          {
            "contact_id": "116240000001558376",
            "contact_name": "Test Run User Zoho TS",
            "customer_name": "Test Run User Zoho TS",
            "company_name": "",
            "website": "",
            "language_code": "",
            "language_code_formatted": "",
            "contact_type": "customer",
            "contact_type_formatted": "Customer",
            "status": "active",
            "status_formatted": "Active",
            "customer_sub_type": "individual",
            "customer_sub_type_formatted": "Individual",
            "source": "api",
            "source_formatted": "API",
            "is_linked_with_zohocrm": false,
            "payment_terms": 0,
            "payment_terms_label": "Due On Receipt",
            "currency_id": "116240000000000071",
            "twitter": "",
            "facebook": "",
            "currency_code": "EUR",
            "outstanding_receivable_amount": 0,
            "outstanding_receivable_amount_formatted": "€0,00",
            "outstanding_receivable_amount_bcy": 0,
            "outstanding_receivable_amount_bcy_formatted": "€0,00",
            "unused_credits_receivable_amount": 0,
            "unused_credits_receivable_amount_formatted": "€0,00",
            "unused_credits_receivable_amount_bcy": 0,
            "unused_credits_receivable_amount_bcy_formatted": "€0,00",
            "first_name": "",
            "last_name": "",
            "email": "",
            "phone": "",
            "mobile": "",
            "is_portal_enabled": false,
            "portal_status": "disabled",
            "created_time": "2022-06-01T15:52:22+0200",
            "created_time_formatted": "01-06-2022",
            "last_modified_time": "2022-06-01T15:52:22+0200",
            "last_modified_time_formatted": "01-06-2022",
            "custom_fields": [
              {
                "field_id": "116240000000356070",
                "customfield_id": "116240000000356070",
                "show_in_store": false,
                "show_in_portal": false,
                "is_active": true,
                "index": 1,
                "label": "Shipment Notifications disabled",
                "show_on_pdf": false,
                "edit_on_portal": false,
                "edit_on_store": false,
                "api_name": "cf_shipment_notifications_disa",
                "show_in_all_pdf": false,
                "value_formatted": "false",
                "search_entity": "contact",
                "data_type": "check_box",
                "placeholder": "cf_shipment_notifications_disa",
                "value": false,
                "is_dependent_field": false
              }
            ],
            "cf_shipment_notifications_disa": "false",
            "cf_shipment_notifications_disa_unformatted": false,
            "custom_field_hash": {
              "cf_shipment_notifications_disa": "false",
              "cf_shipment_notifications_disa_unformatted": false
            },
            "ach_supported": false,
            "has_attachment": false
          },
          {
            "contact_id": "116240000001557878",
            "contact_name": "Test Run User Zoho TS",
            "customer_name": "Test Run User Zoho TS",
            "company_name": "",
            "website": "",
            "language_code": "",
            "language_code_formatted": "",
            "contact_type": "customer",
            "contact_type_formatted": "Customer",
            "status": "active",
            "status_formatted": "Active",
            "customer_sub_type": "individual",
            "customer_sub_type_formatted": "Individual",
            "source": "api",
            "source_formatted": "API",
            "is_linked_with_zohocrm": false,
            "payment_terms": 0,
            "payment_terms_label": "Due On Receipt",
            "currency_id": "116240000000000071",
            "twitter": "",
            "facebook": "",
            "currency_code": "EUR",
            "outstanding_receivable_amount": 0,
            "outstanding_receivable_amount_formatted": "€0,00",
            "outstanding_receivable_amount_bcy": 0,
            "outstanding_receivable_amount_bcy_formatted": "€0,00",
            "unused_credits_receivable_amount": 0,
            "unused_credits_receivable_amount_formatted": "€0,00",
            "unused_credits_receivable_amount_bcy": 0,
            "unused_credits_receivable_amount_bcy_formatted": "€0,00",
            "first_name": "",
            "last_name": "",
            "email": "",
            "phone": "",
            "mobile": "",
            "is_portal_enabled": false,
            "portal_status": "disabled",
            "created_time": "2022-06-01T16:02:04+0200",
            "created_time_formatted": "01-06-2022",
            "last_modified_time": "2022-06-01T16:02:04+0200",
            "last_modified_time_formatted": "01-06-2022",
            "custom_fields": [
              {
                "field_id": "116240000000356070",
                "customfield_id": "116240000000356070",
                "show_in_store": false,
                "show_in_portal": false,
                "is_active": true,
                "index": 1,
                "label": "Shipment Notifications disabled",
                "show_on_pdf": false,
                "edit_on_portal": false,
                "edit_on_store": false,
                "api_name": "cf_shipment_notifications_disa",
                "show_in_all_pdf": false,
                "value_formatted": "false",
                "search_entity": "contact",
                "data_type": "check_box",
                "placeholder": "cf_shipment_notifications_disa",
                "value": false,
                "is_dependent_field": false
              }
            ],
            "cf_shipment_notifications_disa": "false",
            "cf_shipment_notifications_disa_unformatted": false,
            "custom_field_hash": {
              "cf_shipment_notifications_disa": "false",
              "cf_shipment_notifications_disa_unformatted": false
            },
            "ach_supported": false,
            "has_attachment": false
          },
          {
            "contact_id": "116240000001562009",
            "contact_name": "Test Run User Zoho TS",
            "customer_name": "Test Run User Zoho TS",
            "company_name": "",
            "website": "",
            "language_code": "",
            "language_code_formatted": "",
            "contact_type": "customer",
            "contact_type_formatted": "Customer",
            "status": "active",
            "status_formatted": "Active",
            "customer_sub_type": "individual",
            "customer_sub_type_formatted": "Individual",
            "source": "api",
            "source_formatted": "API",
            "is_linked_with_zohocrm": false,
            "payment_terms": 0,
            "payment_terms_label": "Due On Receipt",
            "currency_id": "116240000000000071",
            "twitter": "",
            "facebook": "",
            "currency_code": "EUR",
            "outstanding_receivable_amount": 77.23,
            "outstanding_receivable_amount_formatted": "€77,23",
            "outstanding_receivable_amount_bcy": 77.23,
            "outstanding_receivable_amount_bcy_formatted": "€77,23",
            "unused_credits_receivable_amount": 0,
            "unused_credits_receivable_amount_formatted": "€0,00",
            "unused_credits_receivable_amount_bcy": 0,
            "unused_credits_receivable_amount_bcy_formatted": "€0,00",
            "first_name": "",
            "last_name": "",
            "email": "",
            "phone": "",
            "mobile": "",
            "is_portal_enabled": false,
            "portal_status": "disabled",
            "created_time": "2022-06-01T16:06:00+0200",
            "created_time_formatted": "01-06-2022",
            "last_modified_time": "2022-06-01T16:06:03+0200",
            "last_modified_time_formatted": "01-06-2022",
            "custom_fields": [
              {
                "field_id": "116240000000356070",
                "customfield_id": "116240000000356070",
                "show_in_store": false,
                "show_in_portal": false,
                "is_active": true,
                "index": 1,
                "label": "Shipment Notifications disabled",
                "show_on_pdf": false,
                "edit_on_portal": false,
                "edit_on_store": false,
                "api_name": "cf_shipment_notifications_disa",
                "show_in_all_pdf": false,
                "value_formatted": "false",
                "search_entity": "contact",
                "data_type": "check_box",
                "placeholder": "cf_shipment_notifications_disa",
                "value": false,
                "is_dependent_field": false
              }
            ],
            "cf_shipment_notifications_disa": "false",
            "cf_shipment_notifications_disa_unformatted": false,
            "custom_field_hash": {
              "cf_shipment_notifications_disa": "false",
              "cf_shipment_notifications_disa_unformatted": false
            },
            "ach_supported": false,
            "has_attachment": false
          },
          {
            "contact_id": "116240000001572002",
            "contact_name": "Test Run User Zoho TS",
            "customer_name": "Test Run User Zoho TS",
            "company_name": "",
            "website": "",
            "language_code": "",
            "language_code_formatted": "",
            "contact_type": "customer",
            "contact_type_formatted": "Customer",
            "status": "active",
            "status_formatted": "Active",
            "customer_sub_type": "individual",
            "customer_sub_type_formatted": "Individual",
            "source": "api",
            "source_formatted": "API",
            "is_linked_with_zohocrm": false,
            "payment_terms": 0,
            "payment_terms_label": "Due On Receipt",
            "currency_id": "116240000000000071",
            "twitter": "",
            "facebook": "",
            "currency_code": "EUR",
            "outstanding_receivable_amount": 0,
            "outstanding_receivable_amount_formatted": "€0,00",
            "outstanding_receivable_amount_bcy": 0,
            "outstanding_receivable_amount_bcy_formatted": "€0,00",
            "unused_credits_receivable_amount": 0,
            "unused_credits_receivable_amount_formatted": "€0,00",
            "unused_credits_receivable_amount_bcy": 0,
            "unused_credits_receivable_amount_bcy_formatted": "€0,00",
            "first_name": "",
            "last_name": "",
            "email": "",
            "phone": "",
            "mobile": "",
            "is_portal_enabled": false,
            "portal_status": "disabled",
            "created_time": "2022-06-03T09:10:37+0200",
            "created_time_formatted": "03-06-2022",
            "last_modified_time": "2022-06-03T09:10:37+0200",
            "last_modified_time_formatted": "03-06-2022",
            "custom_fields": [
              {
                "field_id": "116240000000356070",
                "customfield_id": "116240000000356070",
                "show_in_store": false,
                "show_in_portal": false,
                "is_active": true,
                "index": 1,
                "label": "Shipment Notifications disabled",
                "show_on_pdf": false,
                "edit_on_portal": false,
                "edit_on_store": false,
                "api_name": "cf_shipment_notifications_disa",
                "show_in_all_pdf": false,
                "value_formatted": "false",
                "search_entity": "contact",
                "data_type": "check_box",
                "placeholder": "cf_shipment_notifications_disa",
                "value": false,
                "is_dependent_field": false
              }
            ],
            "cf_shipment_notifications_disa": "false",
            "cf_shipment_notifications_disa_unformatted": false,
            "custom_field_hash": {
              "cf_shipment_notifications_disa": "false",
              "cf_shipment_notifications_disa_unformatted": false
            },
            "ach_supported": false,
            "has_attachment": false
          },
          {
            "contact_id": "116240000001557199",
            "contact_name": "Test Run User Zoho TS",
            "customer_name": "Test Run User Zoho TS",
            "company_name": "",
            "website": "",
            "language_code": "",
            "language_code_formatted": "",
            "contact_type": "customer",
            "contact_type_formatted": "Customer",
            "status": "active",
            "status_formatted": "Active",
            "customer_sub_type": "individual",
            "customer_sub_type_formatted": "Individual",
            "source": "api",
            "source_formatted": "API",
            "is_linked_with_zohocrm": false,
            "payment_terms": 0,
            "payment_terms_label": "Due On Receipt",
            "currency_id": "116240000000000071",
            "twitter": "",
            "facebook": "",
            "currency_code": "EUR",
            "outstanding_receivable_amount": 0,
            "outstanding_receivable_amount_formatted": "€0,00",
            "outstanding_receivable_amount_bcy": 0,
            "outstanding_receivable_amount_bcy_formatted": "€0,00",
            "unused_credits_receivable_amount": 0,
            "unused_credits_receivable_amount_formatted": "€0,00",
            "unused_credits_receivable_amount_bcy": 0,
            "unused_credits_receivable_amount_bcy_formatted": "€0,00",
            "first_name": "",
            "last_name": "",
            "email": "",
            "phone": "",
            "mobile": "",
            "is_portal_enabled": false,
            "portal_status": "disabled",
            "created_time": "2022-06-01T15:36:05+0200",
            "created_time_formatted": "01-06-2022",
            "last_modified_time": "2022-06-01T15:36:05+0200",
            "last_modified_time_formatted": "01-06-2022",
            "custom_fields": [
              {
                "field_id": "116240000000356070",
                "customfield_id": "116240000000356070",
                "show_in_store": false,
                "show_in_portal": false,
                "is_active": true,
                "index": 1,
                "label": "Shipment Notifications disabled",
                "show_on_pdf": false,
                "edit_on_portal": false,
                "edit_on_store": false,
                "api_name": "cf_shipment_notifications_disa",
                "show_in_all_pdf": false,
                "value_formatted": "false",
                "search_entity": "contact",
                "data_type": "check_box",
                "placeholder": "cf_shipment_notifications_disa",
                "value": false,
                "is_dependent_field": false
              }
            ],
            "cf_shipment_notifications_disa": "false",
            "cf_shipment_notifications_disa_unformatted": false,
            "custom_field_hash": {
              "cf_shipment_notifications_disa": "false",
              "cf_shipment_notifications_disa_unformatted": false
            },
            "ach_supported": false,
            "has_attachment": false
          },
          {
            "contact_id": "116240000001570002",
            "contact_name": "Test Run User Zoho TS",
            "customer_name": "Test Run User Zoho TS",
            "company_name": "",
            "website": "",
            "language_code": "",
            "language_code_formatted": "",
            "contact_type": "customer",
            "contact_type_formatted": "Customer",
            "status": "active",
            "status_formatted": "Active",
            "customer_sub_type": "individual",
            "customer_sub_type_formatted": "Individual",
            "source": "api",
            "source_formatted": "API",
            "is_linked_with_zohocrm": false,
            "payment_terms": 0,
            "payment_terms_label": "Due On Receipt",
            "currency_id": "116240000000000071",
            "twitter": "",
            "facebook": "",
            "currency_code": "EUR",
            "outstanding_receivable_amount": 0,
            "outstanding_receivable_amount_formatted": "€0,00",
            "outstanding_receivable_amount_bcy": 0,
            "outstanding_receivable_amount_bcy_formatted": "€0,00",
            "unused_credits_receivable_amount": 0,
            "unused_credits_receivable_amount_formatted": "€0,00",
            "unused_credits_receivable_amount_bcy": 0,
            "unused_credits_receivable_amount_bcy_formatted": "€0,00",
            "first_name": "",
            "last_name": "",
            "email": "",
            "phone": "",
            "mobile": "",
            "is_portal_enabled": false,
            "portal_status": "disabled",
            "created_time": "2022-06-03T09:10:37+0200",
            "created_time_formatted": "03-06-2022",
            "last_modified_time": "2022-06-03T09:10:37+0200",
            "last_modified_time_formatted": "03-06-2022",
            "custom_fields": [
              {
                "field_id": "116240000000356070",
                "customfield_id": "116240000000356070",
                "show_in_store": false,
                "show_in_portal": false,
                "is_active": true,
                "index": 1,
                "label": "Shipment Notifications disabled",
                "show_on_pdf": false,
                "edit_on_portal": false,
                "edit_on_store": false,
                "api_name": "cf_shipment_notifications_disa",
                "show_in_all_pdf": false,
                "value_formatted": "false",
                "search_entity": "contact",
                "data_type": "check_box",
                "placeholder": "cf_shipment_notifications_disa",
                "value": false,
                "is_dependent_field": false
              }
            ],
            "cf_shipment_notifications_disa": "false",
            "cf_shipment_notifications_disa_unformatted": false,
            "custom_field_hash": {
              "cf_shipment_notifications_disa": "false",
              "cf_shipment_notifications_disa_unformatted": false
            },
            "ach_supported": false,
            "has_attachment": false
          },
          {
            "contact_id": "116240000001557463",
            "contact_name": "Test Run User Zoho TS",
            "customer_name": "Test Run User Zoho TS",
            "company_name": "",
            "website": "",
            "language_code": "",
            "language_code_formatted": "",
            "contact_type": "customer",
            "contact_type_formatted": "Customer",
            "status": "active",
            "status_formatted": "Active",
            "customer_sub_type": "individual",
            "customer_sub_type_formatted": "Individual",
            "source": "api",
            "source_formatted": "API",
            "is_linked_with_zohocrm": false,
            "payment_terms": 0,
            "payment_terms_label": "Due On Receipt",
            "currency_id": "116240000000000071",
            "twitter": "",
            "facebook": "",
            "currency_code": "EUR",
            "outstanding_receivable_amount": 0,
            "outstanding_receivable_amount_formatted": "€0,00",
            "outstanding_receivable_amount_bcy": 0,
            "outstanding_receivable_amount_bcy_formatted": "€0,00",
            "unused_credits_receivable_amount": 0,
            "unused_credits_receivable_amount_formatted": "€0,00",
            "unused_credits_receivable_amount_bcy": 0,
            "unused_credits_receivable_amount_bcy_formatted": "€0,00",
            "first_name": "",
            "last_name": "",
            "email": "",
            "phone": "",
            "mobile": "",
            "is_portal_enabled": false,
            "portal_status": "disabled",
            "created_time": "2022-06-01T15:49:43+0200",
            "created_time_formatted": "01-06-2022",
            "last_modified_time": "2022-06-01T15:49:43+0200",
            "last_modified_time_formatted": "01-06-2022",
            "custom_fields": [
              {
                "field_id": "116240000000356070",
                "customfield_id": "116240000000356070",
                "show_in_store": false,
                "show_in_portal": false,
                "is_active": true,
                "index": 1,
                "label": "Shipment Notifications disabled",
                "show_on_pdf": false,
                "edit_on_portal": false,
                "edit_on_store": false,
                "api_name": "cf_shipment_notifications_disa",
                "show_in_all_pdf": false,
                "value_formatted": "false",
                "search_entity": "contact",
                "data_type": "check_box",
                "placeholder": "cf_shipment_notifications_disa",
                "value": false,
                "is_dependent_field": false
              }
            ],
            "cf_shipment_notifications_disa": "false",
            "cf_shipment_notifications_disa_unformatted": false,
            "custom_field_hash": {
              "cf_shipment_notifications_disa": "false",
              "cf_shipment_notifications_disa_unformatted": false
            },
            "ach_supported": false,
            "has_attachment": false
          },
          {
            "contact_id": "116240000001557723",
            "contact_name": "Test Run User Zoho TS",
            "customer_name": "Test Run User Zoho TS",
            "company_name": "",
            "website": "",
            "language_code": "",
            "language_code_formatted": "",
            "contact_type": "customer",
            "contact_type_formatted": "Customer",
            "status": "active",
            "status_formatted": "Active",
            "customer_sub_type": "individual",
            "customer_sub_type_formatted": "Individual",
            "source": "api",
            "source_formatted": "API",
            "is_linked_with_zohocrm": false,
            "payment_terms": 0,
            "payment_terms_label": "Due On Receipt",
            "currency_id": "116240000000000071",
            "twitter": "",
            "facebook": "",
            "currency_code": "EUR",
            "outstanding_receivable_amount": 0,
            "outstanding_receivable_amount_formatted": "€0,00",
            "outstanding_receivable_amount_bcy": 0,
            "outstanding_receivable_amount_bcy_formatted": "€0,00",
            "unused_credits_receivable_amount": 0,
            "unused_credits_receivable_amount_formatted": "€0,00",
            "unused_credits_receivable_amount_bcy": 0,
            "unused_credits_receivable_amount_bcy_formatted": "€0,00",
            "first_name": "",
            "last_name": "",
            "email": "",
            "phone": "",
            "mobile": "",
            "is_portal_enabled": false,
            "portal_status": "disabled",
            "created_time": "2022-06-01T16:01:01+0200",
            "created_time_formatted": "01-06-2022",
            "last_modified_time": "2022-06-01T16:01:01+0200",
            "last_modified_time_formatted": "01-06-2022",
            "custom_fields": [
              {
                "field_id": "116240000000356070",
                "customfield_id": "116240000000356070",
                "show_in_store": false,
                "show_in_portal": false,
                "is_active": true,
                "index": 1,
                "label": "Shipment Notifications disabled",
                "show_on_pdf": false,
                "edit_on_portal": false,
                "edit_on_store": false,
                "api_name": "cf_shipment_notifications_disa",
                "show_in_all_pdf": false,
                "value_formatted": "false",
                "search_entity": "contact",
                "data_type": "check_box",
                "placeholder": "cf_shipment_notifications_disa",
                "value": false,
                "is_dependent_field": false
              }
            ],
            "cf_shipment_notifications_disa": "false",
            "cf_shipment_notifications_disa_unformatted": false,
            "custom_field_hash": {
              "cf_shipment_notifications_disa": "false",
              "cf_shipment_notifications_disa_unformatted": false
            },
            "ach_supported": false,
            "has_attachment": false
          },
          {
            "contact_id": "116240000001558510",
            "contact_name": "Test Run User Zoho TS",
            "customer_name": "Test Run User Zoho TS",
            "company_name": "",
            "website": "",
            "language_code": "",
            "language_code_formatted": "",
            "contact_type": "customer",
            "contact_type_formatted": "Customer",
            "status": "active",
            "status_formatted": "Active",
            "customer_sub_type": "individual",
            "customer_sub_type_formatted": "Individual",
            "source": "api",
            "source_formatted": "API",
            "is_linked_with_zohocrm": false,
            "payment_terms": 0,
            "payment_terms_label": "Due On Receipt",
            "currency_id": "116240000000000071",
            "twitter": "",
            "facebook": "",
            "currency_code": "EUR",
            "outstanding_receivable_amount": 0,
            "outstanding_receivable_amount_formatted": "€0,00",
            "outstanding_receivable_amount_bcy": 0,
            "outstanding_receivable_amount_bcy_formatted": "€0,00",
            "unused_credits_receivable_amount": 0,
            "unused_credits_receivable_amount_formatted": "€0,00",
            "unused_credits_receivable_amount_bcy": 0,
            "unused_credits_receivable_amount_bcy_formatted": "€0,00",
            "first_name": "",
            "last_name": "",
            "email": "",
            "phone": "",
            "mobile": "",
            "is_portal_enabled": false,
            "portal_status": "disabled",
            "created_time": "2022-06-01T16:01:00+0200",
            "created_time_formatted": "01-06-2022",
            "last_modified_time": "2022-06-01T16:01:00+0200",
            "last_modified_time_formatted": "01-06-2022",
            "custom_fields": [
              {
                "field_id": "116240000000356070",
                "customfield_id": "116240000000356070",
                "show_in_store": false,
                "show_in_portal": false,
                "is_active": true,
                "index": 1,
                "label": "Shipment Notifications disabled",
                "show_on_pdf": false,
                "edit_on_portal": false,
                "edit_on_store": false,
                "api_name": "cf_shipment_notifications_disa",
                "show_in_all_pdf": false,
                "value_formatted": "false",
                "search_entity": "contact",
                "data_type": "check_box",
                "placeholder": "cf_shipment_notifications_disa",
                "value": false,
                "is_dependent_field": false
              }
            ],
            "cf_shipment_notifications_disa": "false",
            "cf_shipment_notifications_disa_unformatted": false,
            "custom_field_hash": {
              "cf_shipment_notifications_disa": "false",
              "cf_shipment_notifications_disa_unformatted": false
            },
            "ach_supported": false,
            "has_attachment": false
          },
          {
            "contact_id": "116240000001604619",
            "contact_name": "Test User Lastname",
            "customer_name": "Test User Lastname",
            "company_name": "",
            "website": "",
            "language_code": "en",
            "language_code_formatted": "English",
            "contact_type": "customer",
            "contact_type_formatted": "Customer",
            "status": "active",
            "status_formatted": "Active",
            "customer_sub_type": "individual",
            "customer_sub_type_formatted": "Individual",
            "source": "api",
            "source_formatted": "API",
            "is_linked_with_zohocrm": false,
            "payment_terms": 0,
            "payment_terms_label": "Due on Receipt",
            "currency_id": "116240000000000071",
            "twitter": "",
            "facebook": "",
            "currency_code": "EUR",
            "outstanding_receivable_amount": 0,
            "outstanding_receivable_amount_formatted": "€0,00",
            "outstanding_receivable_amount_bcy": 0,
            "outstanding_receivable_amount_bcy_formatted": "€0,00",
            "unused_credits_receivable_amount": 0,
            "unused_credits_receivable_amount_formatted": "€0,00",
            "unused_credits_receivable_amount_bcy": 0,
            "unused_credits_receivable_amount_bcy_formatted": "€0,00",
            "first_name": "Test User",
            "last_name": "Lastname",
            "email": "test44@gmail.com",
            "phone": "",
            "mobile": "",
            "is_portal_enabled": false,
            "portal_status": "disabled",
            "created_time": "2022-06-10T16:48:32+0200",
            "created_time_formatted": "10-06-2022",
            "last_modified_time": "2022-08-24T11:20:37+0200",
            "last_modified_time_formatted": "24-08-2022",
            "custom_fields": [
              {
                "field_id": "116240000000356070",
                "customfield_id": "116240000000356070",
                "show_in_store": false,
                "show_in_portal": false,
                "is_active": true,
                "index": 1,
                "label": "Shipment Notifications disabled",
                "show_on_pdf": false,
                "edit_on_portal": false,
                "edit_on_store": false,
                "api_name": "cf_shipment_notifications_disa",
                "show_in_all_pdf": false,
                "value_formatted": "false",
                "search_entity": "contact",
                "data_type": "check_box",
                "placeholder": "cf_shipment_notifications_disa",
                "value": false,
                "is_dependent_field": false
              }
            ],
            "cf_shipment_notifications_disa": "false",
            "cf_shipment_notifications_disa_unformatted": false,
            "custom_field_hash": {
              "cf_shipment_notifications_disa": "false",
              "cf_shipment_notifications_disa_unformatted": false
            },
            "ach_supported": false,
            "has_attachment": false
          },
          {
            "contact_id": "116240000001604650",
            "contact_name": "Test User Lastname",
            "customer_name": "Test User Lastname",
            "company_name": "",
            "website": "",
            "language_code": "",
            "language_code_formatted": "",
            "contact_type": "customer",
            "contact_type_formatted": "Customer",
            "status": "active",
            "status_formatted": "Active",
            "customer_sub_type": "individual",
            "customer_sub_type_formatted": "Individual",
            "source": "api",
            "source_formatted": "API",
            "is_linked_with_zohocrm": false,
            "payment_terms": 0,
            "payment_terms_label": "Due On Receipt",
            "currency_id": "116240000000000071",
            "twitter": "",
            "facebook": "",
            "currency_code": "EUR",
            "outstanding_receivable_amount": 0,
            "outstanding_receivable_amount_formatted": "€0,00",
            "outstanding_receivable_amount_bcy": 0,
            "outstanding_receivable_amount_bcy_formatted": "€0,00",
            "unused_credits_receivable_amount": 0,
            "unused_credits_receivable_amount_formatted": "€0,00",
            "unused_credits_receivable_amount_bcy": 0,
            "unused_credits_receivable_amount_bcy_formatted": "€0,00",
            "first_name": "Test User",
            "last_name": "Lastname",
            "email": "",
            "phone": "",
            "mobile": "",
            "is_portal_enabled": false,
            "portal_status": "disabled",
            "created_time": "2022-06-10T16:51:26+0200",
            "created_time_formatted": "10-06-2022",
            "last_modified_time": "2022-06-10T16:51:27+0200",
            "last_modified_time_formatted": "10-06-2022",
            "custom_fields": [
              {
                "field_id": "116240000000356070",
                "customfield_id": "116240000000356070",
                "show_in_store": false,
                "show_in_portal": false,
                "is_active": true,
                "index": 1,
                "label": "Shipment Notifications disabled",
                "show_on_pdf": false,
                "edit_on_portal": false,
                "edit_on_store": false,
                "api_name": "cf_shipment_notifications_disa",
                "show_in_all_pdf": false,
                "value_formatted": "false",
                "search_entity": "contact",
                "data_type": "check_box",
                "placeholder": "cf_shipment_notifications_disa",
                "value": false,
                "is_dependent_field": false
              }
            ],
            "cf_shipment_notifications_disa": "false",
            "cf_shipment_notifications_disa_unformatted": false,
            "custom_field_hash": {
              "cf_shipment_notifications_disa": "false",
              "cf_shipment_notifications_disa_unformatted": false
            },
            "ach_supported": false,
            "has_attachment": false
          },
          {
            "contact_id": "116240000001605234",
            "contact_name": "Test User Lastname",
            "customer_name": "Test User Lastname",
            "company_name": "",
            "website": "",
            "language_code": "",
            "language_code_formatted": "",
            "contact_type": "customer",
            "contact_type_formatted": "Customer",
            "status": "active",
            "status_formatted": "Active",
            "customer_sub_type": "individual",
            "customer_sub_type_formatted": "Individual",
            "source": "api",
            "source_formatted": "API",
            "is_linked_with_zohocrm": false,
            "payment_terms": 0,
            "payment_terms_label": "Due On Receipt",
            "currency_id": "116240000000000071",
            "twitter": "",
            "facebook": "",
            "currency_code": "EUR",
            "outstanding_receivable_amount": 0,
            "outstanding_receivable_amount_formatted": "€0,00",
            "outstanding_receivable_amount_bcy": 0,
            "outstanding_receivable_amount_bcy_formatted": "€0,00",
            "unused_credits_receivable_amount": 0,
            "unused_credits_receivable_amount_formatted": "€0,00",
            "unused_credits_receivable_amount_bcy": 0,
            "unused_credits_receivable_amount_bcy_formatted": "€0,00",
            "first_name": "Test User",
            "last_name": "Lastname",
            "email": "",
            "phone": "",
            "mobile": "",
            "is_portal_enabled": false,
            "portal_status": "disabled",
            "created_time": "2022-06-10T16:45:38+0200",
            "created_time_formatted": "10-06-2022",
            "last_modified_time": "2022-06-10T16:45:38+0200",
            "last_modified_time_formatted": "10-06-2022",
            "custom_fields": [
              {
                "field_id": "116240000000356070",
                "customfield_id": "116240000000356070",
                "show_in_store": false,
                "show_in_portal": false,
                "is_active": true,
                "index": 1,
                "label": "Shipment Notifications disabled",
                "show_on_pdf": false,
                "edit_on_portal": false,
                "edit_on_store": false,
                "api_name": "cf_shipment_notifications_disa",
                "show_in_all_pdf": false,
                "value_formatted": "false",
                "search_entity": "contact",
                "data_type": "check_box",
                "placeholder": "cf_shipment_notifications_disa",
                "value": false,
                "is_dependent_field": false
              }
            ],
            "cf_shipment_notifications_disa": "false",
            "cf_shipment_notifications_disa_unformatted": false,
            "custom_field_hash": {
              "cf_shipment_notifications_disa": "false",
              "cf_shipment_notifications_disa_unformatted": false
            },
            "ach_supported": false,
            "has_attachment": false
          },
          {
            "contact_id": "116240000001605287",
            "contact_name": "Test User Lastname",
            "customer_name": "Test User Lastname",
            "company_name": "",
            "website": "",
            "language_code": "",
            "language_code_formatted": "",
            "contact_type": "customer",
            "contact_type_formatted": "Customer",
            "status": "active",
            "status_formatted": "Active",
            "customer_sub_type": "individual",
            "customer_sub_type_formatted": "Individual",
            "source": "api",
            "source_formatted": "API",
            "is_linked_with_zohocrm": false,
            "payment_terms": 0,
            "payment_terms_label": "Due On Receipt",
            "currency_id": "116240000000000071",
            "twitter": "",
            "facebook": "",
            "currency_code": "EUR",
            "outstanding_receivable_amount": 0,
            "outstanding_receivable_amount_formatted": "€0,00",
            "outstanding_receivable_amount_bcy": 0,
            "outstanding_receivable_amount_bcy_formatted": "€0,00",
            "unused_credits_receivable_amount": 0,
            "unused_credits_receivable_amount_formatted": "€0,00",
            "unused_credits_receivable_amount_bcy": 0,
            "unused_credits_receivable_amount_bcy_formatted": "€0,00",
            "first_name": "Test User",
            "last_name": "Lastname",
            "email": "",
            "phone": "",
            "mobile": "",
            "is_portal_enabled": false,
            "portal_status": "disabled",
            "created_time": "2022-06-10T16:46:59+0200",
            "created_time_formatted": "10-06-2022",
            "last_modified_time": "2022-06-10T16:47:00+0200",
            "last_modified_time_formatted": "10-06-2022",
            "custom_fields": [
              {
                "field_id": "116240000000356070",
                "customfield_id": "116240000000356070",
                "show_in_store": false,
                "show_in_portal": false,
                "is_active": true,
                "index": 1,
                "label": "Shipment Notifications disabled",
                "show_on_pdf": false,
                "edit_on_portal": false,
                "edit_on_store": false,
                "api_name": "cf_shipment_notifications_disa",
                "show_in_all_pdf": false,
                "value_formatted": "false",
                "search_entity": "contact",
                "data_type": "check_box",
                "placeholder": "cf_shipment_notifications_disa",
                "value": false,
                "is_dependent_field": false
              }
            ],
            "cf_shipment_notifications_disa": "false",
            "cf_shipment_notifications_disa_unformatted": false,
            "custom_field_hash": {
              "cf_shipment_notifications_disa": "false",
              "cf_shipment_notifications_disa_unformatted": false
            },
            "ach_supported": false,
            "has_attachment": false
          },
          {
            "contact_id": "116240000001604592",
            "contact_name": "Test User Lastname",
            "customer_name": "Test User Lastname",
            "company_name": "",
            "website": "",
            "language_code": "",
            "language_code_formatted": "",
            "contact_type": "customer",
            "contact_type_formatted": "Customer",
            "status": "active",
            "status_formatted": "Active",
            "customer_sub_type": "individual",
            "customer_sub_type_formatted": "Individual",
            "source": "api",
            "source_formatted": "API",
            "is_linked_with_zohocrm": false,
            "payment_terms": 0,
            "payment_terms_label": "Due On Receipt",
            "currency_id": "116240000000000071",
            "twitter": "",
            "facebook": "",
            "currency_code": "EUR",
            "outstanding_receivable_amount": 0,
            "outstanding_receivable_amount_formatted": "€0,00",
            "outstanding_receivable_amount_bcy": 0,
            "outstanding_receivable_amount_bcy_formatted": "€0,00",
            "unused_credits_receivable_amount": 0,
            "unused_credits_receivable_amount_formatted": "€0,00",
            "unused_credits_receivable_amount_bcy": 0,
            "unused_credits_receivable_amount_bcy_formatted": "€0,00",
            "first_name": "Test User",
            "last_name": "Lastname",
            "email": "",
            "phone": "",
            "mobile": "",
            "is_portal_enabled": false,
            "portal_status": "disabled",
            "created_time": "2022-06-10T16:47:35+0200",
            "created_time_formatted": "10-06-2022",
            "last_modified_time": "2022-06-10T16:47:36+0200",
            "last_modified_time_formatted": "10-06-2022",
            "custom_fields": [
              {
                "field_id": "116240000000356070",
                "customfield_id": "116240000000356070",
                "show_in_store": false,
                "show_in_portal": false,
                "is_active": true,
                "index": 1,
                "label": "Shipment Notifications disabled",
                "show_on_pdf": false,
                "edit_on_portal": false,
                "edit_on_store": false,
                "api_name": "cf_shipment_notifications_disa",
                "show_in_all_pdf": false,
                "value_formatted": "false",
                "search_entity": "contact",
                "data_type": "check_box",
                "placeholder": "cf_shipment_notifications_disa",
                "value": false,
                "is_dependent_field": false
              }
            ],
            "cf_shipment_notifications_disa": "false",
            "cf_shipment_notifications_disa_unformatted": false,
            "custom_field_hash": {
              "cf_shipment_notifications_disa": "false",
              "cf_shipment_notifications_disa_unformatted": false
            },
            "ach_supported": false,
            "has_attachment": false
          },
          {
            "contact_id": "116240000001566053",
            "contact_name": "test_FgopWJyFXMBJW43vdzTfnr",
            "customer_name": "test_FgopWJyFXMBJW43vdzTfnr",
            "company_name": "",
            "website": "",
            "language_code": "",
            "language_code_formatted": "",
            "contact_type": "customer",
            "contact_type_formatted": "Customer",
            "status": "active",
            "status_formatted": "Active",
            "customer_sub_type": "business",
            "customer_sub_type_formatted": "Business",
            "source": "user",
            "source_formatted": "User",
            "is_linked_with_zohocrm": false,
            "payment_terms": 0,
            "payment_terms_label": "Due On Receipt",
            "currency_id": "116240000000000071",
            "twitter": "",
            "facebook": "",
            "currency_code": "EUR",
            "outstanding_receivable_amount": 0,
            "outstanding_receivable_amount_formatted": "€0,00",
            "outstanding_receivable_amount_bcy": 0,
            "outstanding_receivable_amount_bcy_formatted": "€0,00",
            "unused_credits_receivable_amount": 0,
            "unused_credits_receivable_amount_formatted": "€0,00",
            "unused_credits_receivable_amount_bcy": 0,
            "unused_credits_receivable_amount_bcy_formatted": "€0,00",
            "first_name": "",
            "last_name": "",
            "email": "",
            "phone": "",
            "mobile": "",
            "is_portal_enabled": false,
            "portal_status": "disabled",
            "created_time": "2022-06-02T11:59:01+0200",
            "created_time_formatted": "02-06-2022",
            "last_modified_time": "2022-06-02T11:59:01+0200",
            "last_modified_time_formatted": "02-06-2022",
            "custom_fields": [
              {
                "field_id": "116240000000356070",
                "customfield_id": "116240000000356070",
                "show_in_store": false,
                "show_in_portal": false,
                "is_active": true,
                "index": 1,
                "label": "Shipment Notifications disabled",
                "show_on_pdf": false,
                "edit_on_portal": false,
                "edit_on_store": false,
                "api_name": "cf_shipment_notifications_disa",
                "show_in_all_pdf": false,
                "value_formatted": "false",
                "search_entity": "contact",
                "data_type": "check_box",
                "placeholder": "cf_shipment_notifications_disa",
                "value": false,
                "is_dependent_field": false
              }
            ],
            "cf_shipment_notifications_disa": "false",
            "cf_shipment_notifications_disa_unformatted": false,
            "custom_field_hash": {
              "cf_shipment_notifications_disa": "false",
              "cf_shipment_notifications_disa_unformatted": false
            },
            "ach_supported": false,
            "has_attachment": false
          },
          {
            "contact_id": "116240000001492391",
            "contact_name": "test_MNsg85eBpPHf65C2iYJsND",
            "customer_name": "test_MNsg85eBpPHf65C2iYJsND",
            "company_name": "test_MNsg85eBpPHf65C2iYJsND",
            "website": "",
            "language_code": "",
            "language_code_formatted": "",
            "contact_type": "customer",
            "contact_type_formatted": "Customer",
            "status": "active",
            "status_formatted": "Active",
            "customer_sub_type": "business",
            "customer_sub_type_formatted": "Business",
            "source": "api",
            "source_formatted": "API",
            "is_linked_with_zohocrm": false,
            "payment_terms": 0,
            "payment_terms_label": "Due On Receipt",
            "currency_id": "116240000000000071",
            "twitter": "",
            "facebook": "",
            "currency_code": "EUR",
            "outstanding_receivable_amount": 0,
            "outstanding_receivable_amount_formatted": "€0,00",
            "outstanding_receivable_amount_bcy": 0,
            "outstanding_receivable_amount_bcy_formatted": "€0,00",
            "unused_credits_receivable_amount": 0,
            "unused_credits_receivable_amount_formatted": "€0,00",
            "unused_credits_receivable_amount_bcy": 0,
            "unused_credits_receivable_amount_bcy_formatted": "€0,00",
            "first_name": "",
            "last_name": "",
            "email": "",
            "phone": "",
            "mobile": "",
            "is_portal_enabled": false,
            "portal_status": "disabled",
            "created_time": "2022-04-14T16:09:03+0200",
            "created_time_formatted": "14-04-2022",
            "last_modified_time": "2022-04-14T16:09:09+0200",
            "last_modified_time_formatted": "14-04-2022",
            "custom_fields": [
              {
                "field_id": "116240000000356070",
                "customfield_id": "116240000000356070",
                "show_in_store": false,
                "show_in_portal": false,
                "is_active": true,
                "index": 1,
                "label": "Shipment Notifications disabled",
                "show_on_pdf": false,
                "edit_on_portal": false,
                "edit_on_store": false,
                "api_name": "cf_shipment_notifications_disa",
                "show_in_all_pdf": false,
                "value_formatted": "false",
                "search_entity": "contact",
                "data_type": "check_box",
                "placeholder": "cf_shipment_notifications_disa",
                "value": false,
                "is_dependent_field": false
              }
            ],
            "cf_shipment_notifications_disa": "false",
            "cf_shipment_notifications_disa_unformatted": false,
            "custom_field_hash": {
              "cf_shipment_notifications_disa": "false",
              "cf_shipment_notifications_disa_unformatted": false
            },
            "ach_supported": false,
            "has_attachment": false
          }
        ]),
    },
  } as unknown as Zoho;

  beforeAll(async () => {
    zohoApp = await prismaClient.zohoApp.findUnique({
      where: {
        id: "test",
      },
      include: { tenant: true },
    });
    if (!zohoApp) throw new Error("No testing Zoho App found!");
  });

  test("It should work to sync Zoho Contacts with internal ECI DB", async () => {
    const xx = new ZohoContactSyncService({
      zoho: mockedZohoClient,
      logger: new NoopLogger(),
      db: new PrismaClient(),
      zohoApp,
    });
    await xx.syncToECI();
  }, 90000);
});
