import { NoopLogger } from "@eci/pkg/logger";
import { PrismaClient } from "@eci/pkg/prisma";
import { beforeEach, describe, jest, test, beforeAll } from "@jest/globals";
import { Zoho, ZohoApiClient } from "@trieb.work/zoho-ts";
import { ZohoItemSyncService } from "./items";

let zohoApp: any;

beforeEach(() => {
  jest.clearAllMocks();
});

let zoho: Zoho;
describe("Zoho Inventory Item Sync", () => {
  const prismaClient = new PrismaClient();
  const mockedZohoClient = {
    item: {
      list: async () =>
        // copied from response of items overview page
        await Promise.resolve([
          {
            item_id: "116240000000378951",
            name: "3 Lebkuche in Bio-Folie",
            item_name: "3 Lebkuche in Bio-Folie",
            unit: "Stück",
            status: "active",
            source: "user",
            source_formatted: "User",
            is_combo_product: false,
            is_linked_with_zohocrm: false,
            zcrm_product_id: "",
            description: "",
            brand: "",
            manufacturer: "",
            rate: 0,
            rate_formatted: "€0,00",
            tax_id: "116240000001634022",
            tax_name: "Reduziert",
            tax_percentage: 7,
            purchase_account_id: "116240000000000509",
            purchase_account_name: "Kosten der verkauften Waren",
            account_id: "116240000000000376",
            account_name: "Verkäufe",
            purchase_description: "",
            purchase_rate: 2,
            purchase_rate_formatted: "€2,00",
            item_type: "inventory",
            item_type_formatted: "Inventory Items",
            product_type: "goods",
            product_type_formatted: "Goods",
            stock_on_hand: 100,
            stock_on_hand_formatted: "100,00",
            has_attachment: false,
            is_returnable: true,
            available_stock: 99,
            available_stock_formatted: "99,00",
            actual_available_stock: 100,
            actual_available_stock_formatted: "100,00",
            sku: "pf-leb-3-gemischt",
            upc: "",
            upc_formatted: "",
            ean: "",
            ean_formatted: "",
            isbn: "",
            part_number: "",
            reorder_level: "",
            image_name: "",
            image_type: "",
            image_document_id: "",
            created_time: "2020-12-03T15:53:44+0100",
            last_modified_time: "2022-08-03T21:33:54+0200",
            show_in_storefront: false,
            length: "",
            width: "",
            height: "",
            weight: 0.23,
            weight_unit: "kg",
            dimension_unit: "cm",
          },
          {
            item_id: "116240000000203041",
            name: "5 Lebkuchen in Bio-Folie - gemischt",
            item_name: "5 Lebkuchen in Bio-Folie - gemischt",
            unit: "pcs",
            status: "active",
            source: "user",
            source_formatted: "User",
            is_combo_product: false,
            is_linked_with_zohocrm: false,
            zcrm_product_id: "",
            description: "",
            brand: "",
            manufacturer: "",
            rate: 14.9,
            rate_formatted: "€14,90",
            tax_id: "116240000000147001",
            tax_name: "Reduziert - Temp",
            tax_percentage: 5,
            purchase_account_id: "116240000000000509",
            purchase_account_name: "Kosten der verkauften Waren",
            account_id: "116240000000000376",
            account_name: "Verkäufe",
            purchase_description: "",
            purchase_rate: 7,
            purchase_rate_formatted: "€7,00",
            item_type: "inventory",
            item_type_formatted: "Inventory Items",
            product_type: "goods",
            product_type_formatted: "Goods",
            stock_on_hand: 200,
            stock_on_hand_formatted: "200,00",
            has_attachment: false,
            is_returnable: true,
            available_stock: 190,
            available_stock_formatted: "190,00",
            actual_available_stock: 200,
            actual_available_stock_formatted: "200,00",
            sku: "pf-leb-5-gemischt",
            upc: "",
            upc_formatted: "",
            ean: "",
            ean_formatted: "",
            isbn: "",
            part_number: "",
            reorder_level: "",
            image_name: "",
            image_type: "",
            image_document_id: "",
            created_time: "2020-10-11T12:43:48+0200",
            last_modified_time: "2022-06-13T16:11:15+0200",
            show_in_storefront: false,
            length: "",
            width: "",
            height: "",
            weight: 450,
            weight_unit: "g",
            dimension_unit: "cm",
          },
          {
            group_id: "116240000000112152",
            group_name: "5 Lebkuchen in Tüte Gemischt Roh",
            item_id: "116240000000112130",
            name: "5 Lebkuchen in Tüte Gemischt Roh-dunkle schokolade",
            item_name: "5 Lebkuchen in Tüte Gemischt Roh-dunkle schokolade",
            unit: "pcs",
            status: "active",
            source: "user",
            source_formatted: "User",
            is_combo_product: false,
            is_linked_with_zohocrm: false,
            zcrm_product_id: "",
            description: "",
            brand: "",
            manufacturer: "Bäcker Bock Backwaren GmbH",
            rate: 0,
            rate_formatted: "€0,00",
            tax_id: "116240000001634022",
            tax_name: "Reduziert",
            tax_percentage: 7,
            purchase_account_id: "116240000000000509",
            purchase_account_name: "Kosten der verkauften Waren",
            account_id: "116240000000000376",
            account_name: "Verkäufe",
            purchase_description: "",
            purchase_rate: 7,
            purchase_rate_formatted: "€7,00",
            item_type: "inventory",
            item_type_formatted: "Inventory Items",
            product_type: "goods",
            product_type_formatted: "Goods",
            stock_on_hand: 225,
            stock_on_hand_formatted: "225,00",
            has_attachment: false,
            is_returnable: false,
            available_stock: 0,
            available_stock_formatted: "0,00",
            actual_available_stock: 225,
            actual_available_stock_formatted: "225,00",
            attribute_id1: "116240000000112138",
            attribute_id2: "",
            attribute_id3: "",
            attribute_name1: "sort",
            attribute_name2: "",
            attribute_name3: "",
            attribute_type1: "Text",
            attribute_type2: "",
            attribute_type3: "",
            attribute_option_id1: "116240000000112142",
            attribute_option_id2: "",
            attribute_option_id3: "",
            attribute_option_name1: "dunkle schokolade",
            attribute_option_name2: "",
            attribute_option_name3: "",
            attribute_option_data1: "",
            attribute_option_data2: "",
            attribute_option_data3: "",
            sku: "roh-leb-5-dunkle",
            upc: "",
            upc_formatted: "",
            ean: "",
            ean_formatted: "",
            isbn: "",
            part_number: "",
            reorder_level: 50,
            image_name: "",
            image_type: "",
            image_document_id: "",
            created_time: "2020-06-17T18:03:01+0200",
            last_modified_time: "2022-08-03T21:33:54+0200",
            show_in_storefront: false,
            length: "",
            width: "",
            height: "",
            weight: "",
            weight_unit: "kg",
            dimension_unit: "cm",
          },
          {
            group_id: "116240000000112152",
            group_name: "5 Lebkuchen in Tüte Gemischt Roh",
            item_id: "116240000000112128",
            name: "5 Lebkuchen in Tüte Gemischt Roh-gemischt",
            item_name: "5 Lebkuchen in Tüte Gemischt Roh-gemischt",
            unit: "pcs",
            status: "active",
            source: "user",
            source_formatted: "User",
            is_combo_product: false,
            is_linked_with_zohocrm: false,
            zcrm_product_id: "",
            description: "",
            brand: "",
            manufacturer: "Bäcker Bock Backwaren GmbH",
            rate: 0,
            rate_formatted: "€0,00",
            tax_id: "116240000001634022",
            tax_name: "Reduziert",
            tax_percentage: 7,
            purchase_account_id: "116240000000000509",
            purchase_account_name: "Kosten der verkauften Waren",
            account_id: "116240000000000376",
            account_name: "Verkäufe",
            purchase_description: "",
            purchase_rate: 7,
            purchase_rate_formatted: "€7,00",
            item_type: "inventory",
            item_type_formatted: "Inventory Items",
            product_type: "goods",
            product_type_formatted: "Goods",
            stock_on_hand: 99101,
            stock_on_hand_formatted: "99.101,00",
            has_attachment: false,
            is_returnable: false,
            available_stock: 99100,
            available_stock_formatted: "99.100,00",
            actual_available_stock: 99101,
            actual_available_stock_formatted: "99.101,00",
            attribute_id1: "116240000000112138",
            attribute_id2: "",
            attribute_id3: "",
            attribute_name1: "sort",
            attribute_name2: "",
            attribute_name3: "",
            attribute_type1: "Text",
            attribute_type2: "",
            attribute_type3: "",
            attribute_option_id1: "116240000000112140",
            attribute_option_id2: "",
            attribute_option_id3: "",
            attribute_option_name1: "gemischt",
            attribute_option_name2: "",
            attribute_option_name3: "",
            attribute_option_data1: "",
            attribute_option_data2: "",
            attribute_option_data3: "",
            sku: "roh-leb-5-gemischt",
            upc: "",
            upc_formatted: "",
            ean: "",
            ean_formatted: "",
            isbn: "",
            part_number: "",
            reorder_level: 50,
            image_name: "",
            image_type: "",
            image_document_id: "",
            created_time: "2020-06-17T18:03:01+0200",
            last_modified_time: "2022-08-03T21:33:54+0200",
            show_in_storefront: false,
            length: "",
            width: "",
            height: "",
            weight: "",
            weight_unit: "kg",
            dimension_unit: "cm",
          },
          {
            group_id: "116240000000112152",
            group_name: "5 Lebkuchen in Tüte Gemischt Roh",
            item_id: "116240000000112134",
            name: "5 Lebkuchen in Tüte Gemischt Roh-natur",
            item_name: "5 Lebkuchen in Tüte Gemischt Roh-natur",
            unit: "pcs",
            status: "active",
            source: "user",
            source_formatted: "User",
            is_combo_product: false,
            is_linked_with_zohocrm: false,
            zcrm_product_id: "",
            description: "",
            brand: "",
            manufacturer: "Bäcker Bock Backwaren GmbH",
            rate: 0,
            rate_formatted: "€0,00",
            tax_id: "116240000001634022",
            tax_name: "Reduziert",
            tax_percentage: 7,
            purchase_account_id: "116240000000000509",
            purchase_account_name: "Kosten der verkauften Waren",
            account_id: "116240000000000376",
            account_name: "Verkäufe",
            purchase_description: "",
            purchase_rate: 7,
            purchase_rate_formatted: "€7,00",
            item_type: "inventory",
            item_type_formatted: "Inventory Items",
            product_type: "goods",
            product_type_formatted: "Goods",
            stock_on_hand: 100001,
            stock_on_hand_formatted: "100.001,00",
            has_attachment: false,
            is_returnable: false,
            available_stock: 100000,
            available_stock_formatted: "100.000,00",
            actual_available_stock: 100001,
            actual_available_stock_formatted: "100.001,00",
            attribute_id1: "116240000000112138",
            attribute_id2: "",
            attribute_id3: "",
            attribute_name1: "sort",
            attribute_name2: "",
            attribute_name3: "",
            attribute_type1: "Text",
            attribute_type2: "",
            attribute_type3: "",
            attribute_option_id1: "116240000000112146",
            attribute_option_id2: "",
            attribute_option_id3: "",
            attribute_option_name1: "natur",
            attribute_option_name2: "",
            attribute_option_name3: "",
            attribute_option_data1: "",
            attribute_option_data2: "",
            attribute_option_data3: "",
            sku: "roh-leb-5-natur",
            upc: "",
            upc_formatted: "",
            ean: "",
            ean_formatted: "",
            isbn: "",
            part_number: "",
            reorder_level: 50,
            image_name: "",
            image_type: "",
            image_document_id: "",
            created_time: "2020-06-17T18:03:01+0200",
            last_modified_time: "2022-08-03T21:33:54+0200",
            show_in_storefront: false,
            length: "",
            width: "",
            height: "",
            weight: "",
            weight_unit: "kg",
            dimension_unit: "cm",
          },
          {
            group_id: "116240000000112152",
            group_name: "5 Lebkuchen in Tüte Gemischt Roh",
            item_id: "116240000000112132",
            name: "5 Lebkuchen in Tüte Gemischt Roh-weiße schokolade",
            item_name: "5 Lebkuchen in Tüte Gemischt Roh-weiße schokolade",
            unit: "pcs",
            status: "active",
            source: "user",
            source_formatted: "User",
            is_combo_product: false,
            is_linked_with_zohocrm: false,
            zcrm_product_id: "",
            description: "",
            brand: "",
            manufacturer: "Bäcker Bock Backwaren GmbH",
            rate: 0,
            rate_formatted: "€0,00",
            tax_id: "116240000001634022",
            tax_name: "Reduziert",
            tax_percentage: 7,
            purchase_account_id: "116240000000000509",
            purchase_account_name: "Kosten der verkauften Waren",
            account_id: "116240000000000376",
            account_name: "Verkäufe",
            purchase_description: "",
            purchase_rate: 7,
            purchase_rate_formatted: "€7,00",
            item_type: "inventory",
            item_type_formatted: "Inventory Items",
            product_type: "goods",
            product_type_formatted: "Goods",
            stock_on_hand: 8701,
            stock_on_hand_formatted: "8.701,00",
            has_attachment: false,
            is_returnable: false,
            available_stock: 8700,
            available_stock_formatted: "8.700,00",
            actual_available_stock: 8701,
            actual_available_stock_formatted: "8.701,00",
            attribute_id1: "116240000000112138",
            attribute_id2: "",
            attribute_id3: "",
            attribute_name1: "sort",
            attribute_name2: "",
            attribute_name3: "",
            attribute_type1: "Text",
            attribute_type2: "",
            attribute_type3: "",
            attribute_option_id1: "116240000000112144",
            attribute_option_id2: "",
            attribute_option_id3: "",
            attribute_option_name1: "weiße schokolade",
            attribute_option_name2: "",
            attribute_option_name3: "",
            attribute_option_data1: "",
            attribute_option_data2: "",
            attribute_option_data3: "",
            sku: "roh-leb-5-weis",
            upc: "",
            upc_formatted: "",
            ean: "",
            ean_formatted: "",
            isbn: "",
            part_number: "",
            reorder_level: 50,
            image_name: "",
            image_type: "",
            image_document_id: "",
            created_time: "2020-06-17T18:03:01+0200",
            last_modified_time: "2022-08-03T21:33:54+0200",
            show_in_storefront: false,
            length: "",
            width: "",
            height: "",
            weight: "",
            weight_unit: "kg",
            dimension_unit: "cm",
          },
          {
            group_id: "116240000000112152",
            group_name: "5 Lebkuchen in Tüte Gemischt Roh",
            item_id: "116240000000112136",
            name: "5 Lebkuchen in Tüte Gemischt Roh-zuckerguss",
            item_name: "5 Lebkuchen in Tüte Gemischt Roh-zuckerguss",
            unit: "pcs",
            status: "active",
            source: "user",
            source_formatted: "User",
            is_combo_product: false,
            is_linked_with_zohocrm: false,
            zcrm_product_id: "",
            description: "",
            brand: "",
            manufacturer: "Bäcker Bock Backwaren GmbH",
            rate: 0,
            rate_formatted: "",
            tax_id: "116240000001634022",
            tax_name: "Reduziert",
            tax_percentage: 7,
            purchase_account_id: "116240000000000509",
            purchase_account_name: "Kosten der verkauften Waren",
            account_id: "",
            account_name: "",
            purchase_description: "",
            purchase_rate: 7,
            purchase_rate_formatted: "€7,00",
            item_type: "purchases",
            item_type_formatted: "Purchase Items",
            product_type: "goods",
            product_type_formatted: "Goods",
            has_attachment: false,
            is_returnable: false,
            attribute_id1: "116240000000112138",
            attribute_id2: "",
            attribute_id3: "",
            attribute_name1: "sort",
            attribute_name2: "",
            attribute_name3: "",
            attribute_type1: "Text",
            attribute_type2: "",
            attribute_type3: "",
            attribute_option_id1: "116240000000112148",
            attribute_option_id2: "",
            attribute_option_id3: "",
            attribute_option_name1: "zuckerguss",
            attribute_option_name2: "",
            attribute_option_name3: "",
            attribute_option_data1: "",
            attribute_option_data2: "",
            attribute_option_data3: "",
            sku: "roh-leb-5-zucker",
            upc: "",
            upc_formatted: "",
            ean: "",
            ean_formatted: "",
            isbn: "",
            part_number: "",
            image_name: "",
            image_type: "",
            image_document_id: "",
            created_time: "2020-06-17T18:03:01+0200",
            last_modified_time: "2022-08-03T21:33:54+0200",
            show_in_storefront: false,
            length: "",
            width: "",
            height: "",
            weight: "",
            weight_unit: "kg",
            dimension_unit: "cm",
          },
          {
            item_id: "116240000000149052",
            name: "5er Set Grußkarten Piano",
            item_name: "5er Set Grußkarten Piano",
            unit: "pcs",
            status: "active",
            source: "user",
            source_formatted: "User",
            is_combo_product: true,
            is_linked_with_zohocrm: false,
            zcrm_product_id: "",
            description: "",
            brand: "",
            manufacturer: "",
            rate: 6,
            rate_formatted: "€6,00",
            tax_id: "116240000000147005",
            tax_name: "Regulär - temp",
            tax_percentage: 16,
            purchase_account_id: "116240000000000509",
            purchase_account_name: "Kosten der verkauften Waren",
            account_id: "116240000000000376",
            account_name: "Verkäufe",
            purchase_description: "",
            purchase_rate: 2.5,
            purchase_rate_formatted: "€2,50",
            item_type: "inventory",
            item_type_formatted: "Inventory Items",
            product_type: "goods",
            product_type_formatted: "Goods",
            stock_on_hand: 100,
            stock_on_hand_formatted: "100,00",
            has_attachment: false,
            is_returnable: true,
            available_stock: 100,
            available_stock_formatted: "100,00",
            actual_available_stock: 100,
            actual_available_stock_formatted: "100,00",
            sku: "kartenset-5-piano",
            upc: "",
            upc_formatted: "",
            ean: "",
            ean_formatted: "",
            isbn: "",
            part_number: "",
            reorder_level: "",
            image_name: "",
            image_type: "",
            image_document_id: "",
            created_time: "2020-07-09T15:37:42+0200",
            last_modified_time: "2021-11-14T15:59:07+0100",
            show_in_storefront: false,
            cf_saleor_id: "UHJvZHVjdDo1",
            cf_saleor_id_unformatted: "UHJvZHVjdDo1",
            length: "",
            width: "",
            height: "",
            weight: "",
            weight_unit: "kg",
            dimension_unit: "cm",
          },
          {
            item_id: "116240000000677007",
            name: "6 Cold Brew Ethiopia",
            item_name: "6 Cold Brew Ethiopia",
            unit: "Stück",
            status: "active",
            source: "user",
            source_formatted: "User",
            is_combo_product: true,
            is_linked_with_zohocrm: false,
            zcrm_product_id: "",
            description: "",
            brand: "",
            manufacturer: "",
            rate: 12,
            rate_formatted: "€12,00",
            tax_id: "116240000001634010",
            tax_name: "Regulär",
            tax_percentage: 19,
            purchase_account_id: "116240000000000509",
            purchase_account_name: "Kosten der verkauften Waren",
            account_id: "116240000000000376",
            account_name: "Verkäufe",
            purchase_description: "",
            purchase_rate: 6,
            purchase_rate_formatted: "€6,00",
            item_type: "inventory",
            item_type_formatted: "Inventory Items",
            product_type: "goods",
            product_type_formatted: "Goods",
            stock_on_hand: 0,
            stock_on_hand_formatted: "0,00",
            has_attachment: false,
            is_returnable: true,
            available_stock: 0,
            available_stock_formatted: "0,00",
            actual_available_stock: 0,
            actual_available_stock_formatted: "0,00",
            sku: "6-cold-brew-ethiopia",
            upc: "",
            upc_formatted: "",
            ean: "",
            ean_formatted: "",
            isbn: "",
            part_number: "",
            reorder_level: "",
            image_name: "",
            image_type: "",
            image_document_id: "",
            created_time: "2021-07-27T16:34:22+0200",
            last_modified_time: "2022-08-03T21:31:43+0200",
            show_in_storefront: false,
            length: "",
            width: "",
            height: "",
            weight: "",
            weight_unit: "kg",
            dimension_unit: "cm",
          },
          {
            item_id: "116240000000149043",
            name: "Briefumschlag A6 grün",
            item_name: "Briefumschlag A6 grün",
            unit: "pcs",
            status: "active",
            source: "user",
            source_formatted: "User",
            is_combo_product: false,
            is_linked_with_zohocrm: false,
            zcrm_product_id: "",
            description: "",
            brand: "Pfeffer & Frost",
            manufacturer: "",
            rate: 0,
            rate_formatted: "",
            tax_id: "",
            tax_name: "",
            tax_percentage: 0,
            purchase_account_id: "116240000000000509",
            purchase_account_name: "Kosten der verkauften Waren",
            account_id: "",
            account_name: "",
            purchase_description: "",
            purchase_rate: 0.2,
            purchase_rate_formatted: "€0,20",
            item_type: "purchases",
            item_type_formatted: "Purchase Items",
            product_type: "goods",
            product_type_formatted: "Goods",
            has_attachment: false,
            is_returnable: false,
            sku: "brief-a6-grün",
            upc: "",
            upc_formatted: "",
            ean: "",
            ean_formatted: "",
            isbn: "",
            part_number: "",
            image_name: "",
            image_type: "",
            image_document_id: "",
            created_time: "2020-07-09T15:35:45+0200",
            last_modified_time: "2020-07-09T15:35:45+0200",
            show_in_storefront: false,
            length: "",
            width: "",
            height: "",
            weight: "",
            weight_unit: "kg",
            dimension_unit: "cm",
          },
          {
            item_id: "116240000000149034",
            name: "Briefumschlag A6 hellblau",
            item_name: "Briefumschlag A6 hellblau",
            unit: "pcs",
            status: "active",
            source: "user",
            source_formatted: "User",
            is_combo_product: false,
            is_linked_with_zohocrm: false,
            zcrm_product_id: "",
            description: "",
            brand: "Pfeffer & Frost",
            manufacturer: "",
            rate: 0,
            rate_formatted: "",
            tax_id: "",
            tax_name: "",
            tax_percentage: 0,
            purchase_account_id: "116240000000000509",
            purchase_account_name: "Kosten der verkauften Waren",
            account_id: "",
            account_name: "",
            purchase_description: "",
            purchase_rate: 0.2,
            purchase_rate_formatted: "€0,20",
            item_type: "purchases",
            item_type_formatted: "Purchase Items",
            product_type: "goods",
            product_type_formatted: "Goods",
            has_attachment: false,
            is_returnable: false,
            sku: "brief-a6-hellblau",
            upc: "",
            upc_formatted: "",
            ean: "",
            ean_formatted: "",
            isbn: "",
            part_number: "",
            image_name: "",
            image_type: "",
            image_document_id: "",
            created_time: "2020-07-09T15:35:21+0200",
            last_modified_time: "2020-07-09T15:35:21+0200",
            show_in_storefront: false,
            length: "",
            width: "",
            height: "",
            weight: "",
            weight_unit: "kg",
            dimension_unit: "cm",
          },
          {
            item_id: "116240000000149025",
            name: "Briefumschlag DIN Lang blau",
            item_name: "Briefumschlag DIN Lang blau",
            unit: "pcs",
            status: "active",
            source: "user",
            source_formatted: "User",
            is_combo_product: false,
            is_linked_with_zohocrm: false,
            zcrm_product_id: "",
            description: "",
            brand: "Pfeffer & Frost",
            manufacturer: "",
            rate: 0,
            rate_formatted: "",
            tax_id: "",
            tax_name: "",
            tax_percentage: 0,
            purchase_account_id: "116240000000000509",
            purchase_account_name: "Kosten der verkauften Waren",
            account_id: "",
            account_name: "",
            purchase_description: "",
            purchase_rate: 0.2,
            purchase_rate_formatted: "€0,20",
            item_type: "purchases",
            item_type_formatted: "Purchase Items",
            product_type: "goods",
            product_type_formatted: "Goods",
            has_attachment: false,
            is_returnable: false,
            sku: "brief-lang-blau",
            upc: "",
            upc_formatted: "",
            ean: "",
            ean_formatted: "",
            isbn: "",
            part_number: "",
            image_name: "",
            image_type: "",
            image_document_id: "",
            created_time: "2020-07-09T15:34:21+0200",
            last_modified_time: "2020-07-09T15:34:21+0200",
            show_in_storefront: false,
            length: "",
            width: "",
            height: "",
            weight: "",
            weight_unit: "kg",
            dimension_unit: "cm",
          },
          {
            item_id: "116240000000631061",
            name: "Cold Brew Ethiopia",
            item_name: "Cold Brew Ethiopia",
            unit: "Stück",
            status: "active",
            source: "user",
            source_formatted: "User",
            is_combo_product: false,
            is_linked_with_zohocrm: false,
            zcrm_product_id: "",
            description: "",
            brand: "",
            manufacturer: "",
            rate: 2,
            rate_formatted: "€2,00",
            tax_id: "",
            tax_name: "",
            tax_percentage: 0,
            purchase_account_id: "116240000000000509",
            purchase_account_name: "Kosten der verkauften Waren",
            account_id: "116240000000000376",
            account_name: "Verkäufe",
            purchase_description: "",
            purchase_rate: 1,
            purchase_rate_formatted: "€1,00",
            item_type: "sales_and_purchases",
            item_type_formatted: "Sales and Purchase Items",
            product_type: "goods",
            product_type_formatted: "Goods",
            has_attachment: false,
            is_returnable: true,
            sku: "coldbrew-ethiopia",
            upc: "",
            upc_formatted: "",
            ean: "",
            ean_formatted: "",
            isbn: "",
            part_number: "",
            image_name: "",
            image_type: "",
            image_document_id: "",
            created_time: "2021-05-18T18:32:42+0200",
            last_modified_time: "2021-05-18T18:34:07+0200",
            show_in_storefront: false,
            length: "",
            width: "",
            height: "",
            weight: "",
            weight_unit: "kg",
            dimension_unit: "cm",
          },
          {
            item_id: "116240000000090037",
            name: "Designerdose Charlotte Dumortier - Natur",
            item_name: "Designerdose Charlotte Dumortier - Natur",
            unit: "box",
            status: "active",
            source: "user",
            source_formatted: "User",
            is_combo_product: true,
            is_linked_with_zohocrm: false,
            zcrm_product_id: "",
            description: "",
            brand: "",
            manufacturer: "",
            rate: 21.9,
            rate_formatted: "€21,90",
            tax_id: "116240000000147001",
            tax_name: "Reduziert - Temp",
            tax_percentage: 5,
            purchase_account_id: "116240000000000509",
            purchase_account_name: "Kosten der verkauften Waren",
            account_id: "116240000000000376",
            account_name: "Verkäufe",
            purchase_description: "",
            purchase_rate: 8.4,
            purchase_rate_formatted: "€8,40",
            item_type: "inventory",
            item_type_formatted: "Inventory Items",
            product_type: "goods",
            product_type_formatted: "Goods",
            stock_on_hand: 100,
            stock_on_hand_formatted: "100,00",
            has_attachment: false,
            is_returnable: true,
            available_stock: 100,
            available_stock_formatted: "100,00",
            actual_available_stock: 100,
            actual_available_stock_formatted: "100,00",
            sku: "pf-dose-5-cd-natur",
            upc: "",
            upc_formatted: "",
            ean: "",
            ean_formatted: "",
            isbn: "",
            part_number: "",
            reorder_level: 50,
            image_name: "PfefferundFrost_produktshot_naturelisen.jpg",
            image_type: "jpg",
            image_document_id: "116240000000109065",
            created_time: "2020-05-22T13:18:36+0200",
            last_modified_time: "2020-11-07T17:41:25+0100",
            show_in_storefront: false,
            cf_saleor_id: "UHJvZHVjdFZhcmlhbnQ6Mw==",
            cf_saleor_id_unformatted: "UHJvZHVjdFZhcmlhbnQ6Mw==",
            length: "",
            width: "",
            height: "",
            weight: 0.5,
            weight_unit: "kg",
            dimension_unit: "cm",
          },
          {
            item_id: "116240000000214357",
            name: "Designerdose Charlotte Dumortier - Weiße Schokolade",
            item_name: "Designerdose Charlotte Dumortier - Weiße Schokolade",
            unit: "box",
            status: "active",
            source: "user",
            source_formatted: "User",
            is_combo_product: true,
            is_linked_with_zohocrm: false,
            zcrm_product_id: "",
            description: "",
            brand: "",
            manufacturer: "",
            rate: 21.9,
            rate_formatted: "€21,90",
            tax_id: "116240000000147001",
            tax_name: "Reduziert - Temp",
            tax_percentage: 5,
            purchase_account_id: "116240000000000509",
            purchase_account_name: "Kosten der verkauften Waren",
            account_id: "116240000000000376",
            account_name: "Verkäufe",
            purchase_description: "",
            purchase_rate: 8.4,
            purchase_rate_formatted: "€8,40",
            item_type: "inventory",
            item_type_formatted: "Inventory Items",
            product_type: "goods",
            product_type_formatted: "Goods",
            stock_on_hand: 300,
            stock_on_hand_formatted: "300,00",
            has_attachment: false,
            is_returnable: true,
            available_stock: 300,
            available_stock_formatted: "300,00",
            actual_available_stock: 300,
            actual_available_stock_formatted: "300,00",
            sku: "pf-dose-5-cd-weis",
            upc: "",
            upc_formatted: "",
            ean: "",
            ean_formatted: "",
            isbn: "",
            part_number: "",
            reorder_level: 50,
            image_name: "",
            image_type: "",
            image_document_id: "",
            created_time: "2020-10-13T00:12:50+0200",
            last_modified_time: "2021-12-16T14:54:03+0100",
            show_in_storefront: false,
            cf_saleor_id: "UHJvZHVjdFZhcmlhbnQ6NA==",
            cf_saleor_id_unformatted: "UHJvZHVjdFZhcmlhbnQ6NA==",
            length: "",
            width: "",
            height: "",
            weight: 0.5,
            weight_unit: "kg",
            dimension_unit: "cm",
          },
          {
            item_id: "116240000000075033",
            name: "Designerdose Charlotte Dumortier Sorte Dunkle Schokolade",
            item_name:
              "Designerdose Charlotte Dumortier Sorte Dunkle Schokolade",
            unit: "box",
            status: "active",
            source: "user",
            source_formatted: "User",
            is_combo_product: true,
            is_linked_with_zohocrm: false,
            zcrm_product_id: "",
            description: "",
            brand: "",
            manufacturer: "",
            rate: 21.9,
            rate_formatted: "€21,90",
            tax_id: "116240000000147001",
            tax_name: "Reduziert - Temp",
            tax_percentage: 5,
            purchase_account_id: "116240000000000509",
            purchase_account_name: "Kosten der verkauften Waren",
            account_id: "116240000000000376",
            account_name: "Verkäufe",
            purchase_description: "",
            purchase_rate: 8.4,
            purchase_rate_formatted: "€8,40",
            item_type: "inventory",
            item_type_formatted: "Inventory Items",
            product_type: "goods",
            product_type_formatted: "Goods",
            stock_on_hand: 150,
            stock_on_hand_formatted: "150,00",
            has_attachment: false,
            is_returnable: true,
            available_stock: 150,
            available_stock_formatted: "150,00",
            actual_available_stock: 150,
            actual_available_stock_formatted: "150,00",
            sku: "pf-dose-5-cd-dunkle",
            upc: "",
            upc_formatted: "",
            ean: "",
            ean_formatted: "",
            isbn: "",
            part_number: "",
            reorder_level: 50,
            image_name: "PfefferundFrost_produktshot_dunkleschokolade.jpg",
            image_type: "jpg",
            image_document_id: "116240000000109073",
            created_time: "2020-05-18T11:40:34+0200",
            last_modified_time: "2021-07-09T12:41:48+0200",
            show_in_storefront: false,
            cf_saleor_id: "UHJvZHVjdFZhcmlhbnQ6NA==",
            cf_saleor_id_unformatted: "UHJvZHVjdFZhcmlhbnQ6NA==",
            length: "",
            width: "",
            height: "",
            weight: 0.5,
            weight_unit: "kg",
            dimension_unit: "cm",
          },
          {
            item_id: "116240000000037177",
            name: "Designerdose Charlotte Dumortier Sorte Gemischt",
            item_name: "Designerdose Charlotte Dumortier Sorte Gemischt",
            unit: "box",
            status: "active",
            source: "user",
            source_formatted: "User",
            is_combo_product: true,
            is_linked_with_zohocrm: false,
            zcrm_product_id: "",
            description: "",
            brand: "",
            manufacturer: "",
            rate: 21.9,
            rate_formatted: "€21,90",
            tax_id: "116240000000147001",
            tax_name: "Reduziert - Temp",
            tax_percentage: 5,
            purchase_account_id: "116240000000000509",
            purchase_account_name: "Kosten der verkauften Waren",
            account_id: "116240000000000376",
            account_name: "Verkäufe",
            purchase_description: "",
            purchase_rate: 8.4,
            purchase_rate_formatted: "€8,40",
            item_type: "inventory",
            item_type_formatted: "Inventory Items",
            product_type: "goods",
            product_type_formatted: "Goods",
            stock_on_hand: 50,
            stock_on_hand_formatted: "50,00",
            has_attachment: false,
            is_returnable: true,
            available_stock: 50,
            available_stock_formatted: "50,00",
            actual_available_stock: 50,
            actual_available_stock_formatted: "50,00",
            sku: "pf-dose-5-cd-gemischt",
            upc: "",
            upc_formatted: "",
            ean: "",
            ean_formatted: "",
            isbn: "",
            part_number: "",
            reorder_level: 50,
            image_name: "PfefferundFrost_produktshot_mischung.jpg",
            image_type: "jpg",
            image_document_id: "116240000000109089",
            created_time: "2020-04-20T12:11:21+0200",
            last_modified_time: "2021-02-25T21:08:12+0100",
            show_in_storefront: false,
            cf_saleor_id: "UHJvZHVjdFZhcmlhbnQ6Mw==",
            cf_saleor_id_unformatted: "UHJvZHVjdFZhcmlhbnQ6Mw==",
            length: "",
            width: "",
            height: "",
            weight: 0.5,
            weight_unit: "kg",
            dimension_unit: "cm",
          },
          {
            item_id: "116240000000049391",
            name: "Designerdose Charlotte Dumortier Sorte Zuckerguss",
            item_name: "Designerdose Charlotte Dumortier Sorte Zuckerguss",
            unit: "box",
            status: "active",
            source: "user",
            source_formatted: "User",
            is_combo_product: true,
            is_linked_with_zohocrm: false,
            zcrm_product_id: "",
            description: "",
            brand: "",
            manufacturer: "",
            rate: 21.9,
            rate_formatted: "€21,90",
            tax_id: "116240000000147001",
            tax_name: "Reduziert - Temp",
            tax_percentage: 5,
            purchase_account_id: "116240000000000509",
            purchase_account_name: "Kosten der verkauften Waren",
            account_id: "116240000000000376",
            account_name: "Verkäufe",
            purchase_description: "",
            purchase_rate: 8.4,
            purchase_rate_formatted: "€8,40",
            item_type: "inventory",
            item_type_formatted: "Inventory Items",
            product_type: "goods",
            product_type_formatted: "Goods",
            stock_on_hand: 130,
            stock_on_hand_formatted: "130,00",
            has_attachment: false,
            is_returnable: true,
            available_stock: 130,
            available_stock_formatted: "130,00",
            actual_available_stock: 130,
            actual_available_stock_formatted: "130,00",
            sku: "pf-dose-5-cd-zucker",
            upc: "",
            upc_formatted: "",
            ean: "",
            ean_formatted: "",
            isbn: "",
            part_number: "",
            reorder_level: 50,
            image_name: "PfefferundFrost_produktshot_zuckerguss.jpg",
            image_type: "jpg",
            image_document_id: "116240000000109081",
            created_time: "2020-04-21T14:48:07+0200",
            last_modified_time: "2020-11-07T17:41:25+0100",
            show_in_storefront: false,
            cf_saleor_id: "UHJvZHVjdFZhcmlhbnQ6Mg==",
            cf_saleor_id_unformatted: "UHJvZHVjdFZhcmlhbnQ6Mg==",
            length: "",
            width: "",
            height: "",
            weight: 0.5,
            weight_unit: "kg",
            dimension_unit: "cm",
          },
          {
            item_id: "116240000000209603",
            name: "Dose - Cachetejack - Dunkle Schokolade",
            item_name: "Dose - Cachetejack - Dunkle Schokolade",
            unit: "box",
            status: "active",
            source: "user",
            source_formatted: "User",
            is_combo_product: true,
            is_linked_with_zohocrm: false,
            zcrm_product_id: "",
            description: "",
            brand: "",
            manufacturer: "",
            rate: 21.9,
            rate_formatted: "€21,90",
            tax_id: "116240000000147001",
            tax_name: "Reduziert - Temp",
            tax_percentage: 5,
            purchase_account_id: "116240000000000509",
            purchase_account_name: "Kosten der verkauften Waren",
            account_id: "116240000000000376",
            account_name: "Verkäufe",
            purchase_description: "",
            purchase_rate: 8.4,
            purchase_rate_formatted: "€8,40",
            item_type: "inventory",
            item_type_formatted: "Inventory Items",
            product_type: "goods",
            product_type_formatted: "Goods",
            stock_on_hand: 175,
            stock_on_hand_formatted: "175,00",
            has_attachment: false,
            is_returnable: true,
            available_stock: 175,
            available_stock_formatted: "175,00",
            actual_available_stock: 175,
            actual_available_stock_formatted: "175,00",
            sku: "pf-dose-5-cj-dunkle",
            upc: "",
            upc_formatted: "",
            ean: "",
            ean_formatted: "",
            isbn: "",
            part_number: "",
            reorder_level: 50,
            image_name: "",
            image_type: "",
            image_document_id: "",
            created_time: "2020-10-12T21:27:43+0200",
            last_modified_time: "2021-07-09T12:41:48+0200",
            show_in_storefront: false,
            length: "",
            width: "",
            height: "",
            weight: 0.5,
            weight_unit: "kg",
            dimension_unit: "cm",
          },
          {
            item_id: "116240000000203164",
            name: "Dose - Cachetejack - Gemischt",
            item_name: "Dose - Cachetejack - Gemischt",
            unit: "box",
            status: "active",
            source: "user",
            source_formatted: "User",
            is_combo_product: true,
            is_linked_with_zohocrm: false,
            zcrm_product_id: "",
            description: "",
            brand: "",
            manufacturer: "",
            rate: 21.9,
            rate_formatted: "€21,90",
            tax_id: "116240000001634022",
            tax_name: "Reduziert",
            tax_percentage: 7,
            purchase_account_id: "116240000000000509",
            purchase_account_name: "Kosten der verkauften Waren",
            account_id: "116240000000000376",
            account_name: "Verkäufe",
            purchase_description: "",
            purchase_rate: 8.4,
            purchase_rate_formatted: "€8,40",
            item_type: "inventory",
            item_type_formatted: "Inventory Items",
            product_type: "goods",
            product_type_formatted: "Goods",
            stock_on_hand: 1100,
            stock_on_hand_formatted: "1.100,00",
            has_attachment: false,
            is_returnable: true,
            available_stock: 1100,
            available_stock_formatted: "1.100,00",
            actual_available_stock: 1100,
            actual_available_stock_formatted: "1.100,00",
            sku: "pf-dose-5-cj-gemischt",
            upc: "",
            upc_formatted: "",
            ean: "",
            ean_formatted: "",
            isbn: "",
            part_number: "",
            reorder_level: "",
            image_name: "",
            image_type: "",
            image_document_id: "",
            created_time: "2020-10-11T20:13:27+0200",
            last_modified_time: "2022-08-03T21:33:54+0200",
            show_in_storefront: false,
            length: "",
            width: "",
            height: "",
            weight: 0.5,
            weight_unit: "kg",
            dimension_unit: "cm",
          },
          {
            item_id: "116240000000209042",
            name: "Dose - Cachetejack - Weiße Schokolade",
            item_name: "Dose - Cachetejack - Weiße Schokolade",
            unit: "box",
            status: "active",
            source: "user",
            source_formatted: "User",
            is_combo_product: true,
            is_linked_with_zohocrm: false,
            zcrm_product_id: "",
            description: "",
            brand: "",
            manufacturer: "",
            rate: 21.9,
            rate_formatted: "€21,90",
            tax_id: "116240000000147001",
            tax_name: "Reduziert - Temp",
            tax_percentage: 5,
            purchase_account_id: "116240000000000509",
            purchase_account_name: "Kosten der verkauften Waren",
            account_id: "116240000000000376",
            account_name: "Verkäufe",
            purchase_description: "",
            purchase_rate: 8.4,
            purchase_rate_formatted: "€8,40",
            item_type: "inventory",
            item_type_formatted: "Inventory Items",
            product_type: "goods",
            product_type_formatted: "Goods",
            stock_on_hand: 900,
            stock_on_hand_formatted: "900,00",
            has_attachment: false,
            is_returnable: true,
            available_stock: 900,
            available_stock_formatted: "900,00",
            actual_available_stock: 900,
            actual_available_stock_formatted: "900,00",
            sku: "pf-dose-5-cj-weis",
            upc: "",
            upc_formatted: "",
            ean: "",
            ean_formatted: "",
            isbn: "",
            part_number: "",
            reorder_level: 50,
            image_name: "",
            image_type: "",
            image_document_id: "",
            created_time: "2020-10-12T16:57:25+0200",
            last_modified_time: "2020-10-12T23:36:56+0200",
            show_in_storefront: false,
            length: "",
            width: "",
            height: "",
            weight: 0.5,
            weight_unit: "kg",
            dimension_unit: "cm",
          },
          {
            item_id: "116240000000209978",
            name: "Dose - Cachetejack - Zuckerguss",
            item_name: "Dose - Cachetejack - Zuckerguss",
            unit: "box",
            status: "active",
            source: "user",
            source_formatted: "User",
            is_combo_product: true,
            is_linked_with_zohocrm: false,
            zcrm_product_id: "",
            description: "",
            brand: "",
            manufacturer: "",
            rate: 21.9,
            rate_formatted: "€21,90",
            tax_id: "116240000000147001",
            tax_name: "Reduziert - Temp",
            tax_percentage: 5,
            purchase_account_id: "116240000000000509",
            purchase_account_name: "Kosten der verkauften Waren",
            account_id: "116240000000000376",
            account_name: "Verkäufe",
            purchase_description: "",
            purchase_rate: 8.4,
            purchase_rate_formatted: "€8,40",
            item_type: "inventory",
            item_type_formatted: "Inventory Items",
            product_type: "goods",
            product_type_formatted: "Goods",
            stock_on_hand: 100,
            stock_on_hand_formatted: "100,00",
            has_attachment: false,
            is_returnable: true,
            available_stock: 100,
            available_stock_formatted: "100,00",
            actual_available_stock: 100,
            actual_available_stock_formatted: "100,00",
            sku: "pf-dose-5-cj-zucker",
            upc: "",
            upc_formatted: "",
            ean: "",
            ean_formatted: "",
            isbn: "",
            part_number: "",
            reorder_level: 50,
            image_name: "",
            image_type: "",
            image_document_id: "",
            created_time: "2020-10-12T22:18:04+0200",
            last_modified_time: "2020-10-12T22:18:11+0200",
            show_in_storefront: false,
            length: "",
            width: "",
            height: "",
            weight: 0.5,
            weight_unit: "kg",
            dimension_unit: "cm",
          },
          {
            item_id: "116240000001504040",
            name: "Dose - Maya Stepien - Gemischt",
            item_name: "Dose - Maya Stepien - Gemischt",
            unit: "box",
            status: "active",
            source: "user",
            source_formatted: "User",
            is_combo_product: true,
            is_linked_with_zohocrm: false,
            zcrm_product_id: "",
            description: "",
            brand: "",
            manufacturer: "",
            rate: 21.9,
            rate_formatted: "€21,90",
            tax_id: "116240000001634022",
            tax_name: "Reduziert",
            tax_percentage: 7,
            purchase_account_id: "116240000000000509",
            purchase_account_name: "Kosten der verkauften Waren",
            account_id: "116240000000000376",
            account_name: "Verkäufe",
            purchase_description: "",
            purchase_rate: 8.4,
            purchase_rate_formatted: "€8,40",
            item_type: "inventory",
            item_type_formatted: "Inventory Items",
            product_type: "goods",
            product_type_formatted: "Goods",
            stock_on_hand: 200,
            stock_on_hand_formatted: "200,00",
            has_attachment: false,
            is_returnable: true,
            available_stock: 200,
            available_stock_formatted: "200,00",
            actual_available_stock: 200,
            actual_available_stock_formatted: "200,00",
            sku: "pf-dose-5-ms-gemischt",
            upc: "",
            upc_formatted: "",
            ean: "",
            ean_formatted: "",
            isbn: "",
            part_number: "",
            reorder_level: "",
            image_name: "",
            image_type: "",
            image_document_id: "",
            created_time: "2022-04-20T10:46:58+0200",
            last_modified_time: "2022-08-03T21:33:54+0200",
            show_in_storefront: false,
            length: "",
            width: "",
            height: "",
            weight: 0.5,
            weight_unit: "kg",
            dimension_unit: "cm",
          },
          {
            item_id: "116240000000631074",
            name: "Granola Erdnuss + Cold Brew schokoladig",
            item_name: "Granola Erdnuss + Cold Brew schokoladig",
            unit: "Stück",
            status: "active",
            source: "user",
            source_formatted: "User",
            is_combo_product: true,
            is_linked_with_zohocrm: false,
            zcrm_product_id: "",
            description: "",
            brand: "",
            manufacturer: "",
            rate: 8.5,
            rate_formatted: "€8,50",
            tax_id: "116240000001634010",
            tax_name: "Regulär",
            tax_percentage: 19,
            purchase_account_id: "116240000000000509",
            purchase_account_name: "Kosten der verkauften Waren",
            account_id: "116240000000000376",
            account_name: "Verkäufe",
            purchase_description: "",
            purchase_rate: 5.5,
            purchase_rate_formatted: "€5,50",
            item_type: "inventory",
            item_type_formatted: "Inventory Items",
            product_type: "goods",
            product_type_formatted: "Goods",
            stock_on_hand: 0,
            stock_on_hand_formatted: "0,00",
            has_attachment: false,
            is_returnable: true,
            available_stock: 0,
            available_stock_formatted: "0,00",
            actual_available_stock: 0,
            actual_available_stock_formatted: "0,00",
            sku: "granola-erdnuss-cold-colombia",
            upc: "",
            upc_formatted: "",
            ean: "",
            ean_formatted: "",
            isbn: "",
            part_number: "",
            reorder_level: "",
            image_name: "",
            image_type: "",
            image_document_id: "",
            created_time: "2021-05-18T18:37:30+0200",
            last_modified_time: "2022-08-03T21:31:43+0200",
            show_in_storefront: false,
            length: "",
            width: "",
            height: "",
            weight: "",
            weight_unit: "kg",
            dimension_unit: "cm",
          },
          {
            item_id: "116240000000057084",
            name: "Grußkarte Cachetejack Weihnachtsmann",
            item_name: "Grußkarte Cachetejack Weihnachtsmann",
            unit: "pcs",
            status: "inactive",
            source: "user",
            source_formatted: "User",
            is_combo_product: false,
            is_linked_with_zohocrm: false,
            zcrm_product_id: "",
            description: "",
            brand: "",
            manufacturer: "",
            rate: 3.2,
            rate_formatted: "€3,20",
            tax_id: "116240000000147005",
            tax_name: "Regulär - temp",
            tax_percentage: 16,
            purchase_account_id: "116240000000000509",
            purchase_account_name: "Kosten der verkauften Waren",
            account_id: "116240000000000376",
            account_name: "Verkäufe",
            purchase_description: "",
            purchase_rate: 0.5,
            purchase_rate_formatted: "€0,50",
            item_type: "inventory",
            item_type_formatted: "Inventory Items",
            product_type: "goods",
            product_type_formatted: "Goods",
            stock_on_hand: 100,
            stock_on_hand_formatted: "100,00",
            has_attachment: false,
            is_returnable: false,
            available_stock: 100,
            available_stock_formatted: "100,00",
            actual_available_stock: 100,
            actual_available_stock_formatted: "100,00",
            sku: "grusskarte_cachetejack_weihnachtsmann",
            upc: "",
            upc_formatted: "",
            ean: "",
            ean_formatted: "",
            isbn: "",
            part_number: "",
            reorder_level: "",
            image_name: "",
            image_type: "",
            image_document_id: "",
            created_time: "2020-04-27T15:25:27+0200",
            last_modified_time: "2020-10-14T12:17:27+0200",
            show_in_storefront: false,
            length: "",
            width: "",
            height: "",
            weight: "",
            weight_unit: "kg",
            dimension_unit: "cm",
          },
        ]),
    },
  } as unknown as Zoho;

  beforeAll(async () => {
    // clean products in DB - this breaks tests, if you let it run in
    // parallel with Saleor item tests
    // await prismaClient.product.deleteMany({
    //   where: {
    //     tenantId: "test",
    //   },
    // });
    // await prismaClient.productVariant.deleteMany({
    //   where: {
    //     tenantId: "test",
    //   },
    // });
    // console.log("Cleaned all existing products from the DB");

    zohoApp = await prismaClient.zohoApp.findUnique({
      where: {
        id: "test",
      },
      include: { tenant: true },
    });
    if (!zohoApp) throw new Error("No testing Zoho App found!");

    zoho = new Zoho(
      await ZohoApiClient.fromOAuth({
        orgId: zohoApp.orgId,
        client: { id: zohoApp.clientId, secret: zohoApp.clientSecret },
      }),
    );
  });

  test("It should work to sync Zoho Items to internal ECI DB", async () => {
    const xx = new ZohoItemSyncService({
      zoho: mockedZohoClient,
      logger: new NoopLogger(),
      db: new PrismaClient(),
      zohoApp,
    });
    await xx.syncToECI();
  }, 90000);

  // test("It should work to sync Zoho Items from internal ECI DB", async () => {
  //   const xx = new ZohoItemSyncService({
  //     zoho: mockedZohoClient,
  //     logger: new NoopLogger(),
  //     db: new PrismaClient(),
  //     zohoApp,
  //   });
  //   await xx.syncFromECI();
  // }, 90000);
});
