apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "eci-worker.fullname" . }}
  labels:
    {{- include "eci-worker.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "eci-worker.selectorLabels" . | nindent 6 }}
  replicas: 1
  template:
    metadata:
      labels:
        {{- include "eci-worker.selectorLabels" . | nindent 8 }}
    spec:
      {{- if .Values.imagePullSecret }}
      imagePullSecrets: 
        - name: {{ .Values.imagePullSecret }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          imagePullPolicy: IfNotPresent
          image: "{{ .Values.image.imageName }}"
          env:
            - name: ECI_ENV
              value: "{{ .Values.eciEnv }}"
          envFrom:
            - secretRef:
                name: {{ include "eci-worker.fullname" . }}
          resources:
            requests:
              cpu: 50m
              memory: 180Mi
            limits:
              cpu: 100m
              memory: 250Mi
