apiVersion: v1
kind: Secret
metadata:
  name: {{ include "eci-worker.fullname" . }}
type: Opaque
data:
  DATABASE_URL: {{ .Values.databaseUrl | b64enc | quote }}
  REDIS_HOST: {{ .Values.redis.host | b64enc | quote }}
  REDIS_PORT: {{ .Values.redis.port | toString | b64enc | quote }}
  REDIS_PASSWORD: {{ .Values.redis.password | b64enc | quote }}
  SIGNING_KEY: {{ .Values.signingKey | b64enc | quote }}
  ELASTIC_LOGGING_SERVER: {{ .Values.elasticsearch.host | b64enc | quote }}
  ELASTIC_LOGGING_USERNAME: {{ .Values.elasticsearch.username | b64enc | quote }}
  ELASTIC_LOGGING_PASSWORD: {{ .Values.elasticsearch.password | b64enc | quote }}
  SENDGRID_API_KEY: {{ .Values.sendgridApiKey | b64enc | quote }}
  SECRET_KEY: {{ .Values.secretKey | b64enc | quote }}