#!/bin/zsh
. "$(dirname "$0")/_/husky.sh"

BRANCH=`git rev-parse --abbrev-ref HEAD`

if [[ "$BRANCH" =~ ^(master|main|testing)$ ]]; then
  echo "You are on branch $BRANCH. Are you sure you want to commit to this branch?"
  echo "If so, commit with --no-verify to bypass this pre-commit hook."
  exit 1
fi

yarn tsc
yarn test
yarn lint-staged
yarn prettier --check .
