name: Testing

on:
  pull_request:

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        saleor: ["3.0-triebwork7", "3.0-triebwork11"]
    services:
      saleor_db:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
          --name=saleor_db
      eci_db:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
        ports:
          - "15432:5432"
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
          --name=eci_db
      saleor_api:
        image: registry.gitlab.com/trieb.work/saleor:${{ matrix.saleor }}
        env:
          DATABASE_URL: postgres://postgres:postgres@saleordb:5432/postgres
          SECRET_KEY: can-be-anything
        options: --name=saleor_api
    steps:
      - name: Setup Saleor
        run: |
          docker exec saleor_api python manage.py migrate
          docker exec saleor_api python manage.py populatedb --createsuperuser
          # This will also create an admin user
          # email: admin@example.com
          # password: admin

      - name: Checkout code
        uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
      - uses: actions/cache@v2
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - name: Install
        run: yarn install

      - name: Build
        run: yarn build

      - name: Lint
        run: yarn fmt

      - name: Check types
        run: yarn tsc

      - name: Seed database
        run: |
          yarn db:push
          yarn db:seed
        env:
          DATABASE_URL: postgresql://postgres:postgres@localhost:15432/postgres
          DATABASE_URL_POOL: postgresql://postgres:postgres@localhost:15432/postgres
          SALEOR_TEMPORARY_APP_TOKEN: ${{secrets.SALEOR_TEMPORARY_APP_TOKEN}}

      - name: Unit tests
        run: yarn test
