name: Testing

on:
  pull_request:

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        saleor: ["3.0-triebwork7", "3.0-triebwork11"]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
      - uses: actions/cache@v2
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - name: Install
        run: yarn install

      - name: Build
        run: make build

      - name: Lint
        run: make fmt

      - name: Check types
        run: make tsc

      # - name: Seed database
      #   run: |
      #     yarn db:push
      #     yarn db:seed
      #   env:
      #     DATABASE_URL: postgresql://postgres:postgres@localhost:15432/postgres
      #     DATABASE_URL_POOL: postgresql://postgres:postgres@localhost:15432/postgres
      #     SALEOR_TEMPORARY_APP_TOKEN: ${{secrets.SALEOR_TEMPORARY_APP_TOKEN}}
      - name: Test (unit)
        run: make test

      - name: Test (e2e)
        run: |
          # choose a fixed version to download
          echo "SALEOR_TAG=:${{matrix.saleor}}" >> .env

          # Setup 3rd party services
          make init


          docker ps
          # Run unit and e2e tests
          make e2e
