name: Testing

on:
  pull_request:

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest
    # container: node:16

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
      saleor:
        image: registry.gitlab.com/trieb.work/saleor:3.0-triebwork7
        env:
          DATABASE_URL: postgres://postgres:postgres@postgres:5432/postgres
          SECRET_KEY: adgkadgkajsdg

    steps:

      - name: Setup Saleor
        run: |

          docker ps

      - name: Checkout code
        uses: actions/checkout@v2

      - uses: actions/cache@v2
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - name: Install
        run: yarn install

      - name: Build
        run: yarn build

      - name: Lint
        run: yarn fmt

      - name: Check types
        run: yarn tsc

      - name: Seed database
        run: |
          yarn db:push
          yarn db:seed
        env:
          DATABASE_URL: postgresql://postgres:postgres@postgres:5432/postgres
          DATABASE_URL_POOL: postgresql://postgres:postgres@postgres:5432/postgres
          SALEOR_TEMPORARY_APP_TOKEN: ${{secrets.SALEOR_TEMPORARY_APP_TOKEN}}

      - name: Unit tests
        run: yarn test
