name: Clean registry after PR close

# only trigger on pull request closed events
on:
  pull_request:
    types: [closed]

env:
  SERVICE: worker
jobs:
  cleanRegistry:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v2

      - name: Delete tag
        uses: bots-house/ghcr-delete-image-action@v1.0.0
        with:
          owner: ${{ github.repository_owner }}
          name: ghcr.io/${{ github.repository }}/${{ env.SERVICE }}
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: pr-${{github.event.pull_request.number}}
