name: Clean registry after PR close

# only trigger on pull request closed events
on:
  pull_request:
    types: [closed]

env:
  PR: pr-${{github.event.pull_request.number}}

jobs:
  cleanRegistry:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v2

      - name: Delete tag
        run: |
          echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin

# 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
