name: Integration

# All required 3rd party services are hosted in docker containers and available
# via localhost.
#
# The webhooks service is started inside a docker container as well and all
# integration tests are being run with a fresh database seed

on:
  pull_request:

jobs:
  tests:
    name: Integration
    runs-on: ubuntu-latest
    strategy:
      matrix:
        saleor: ["3.0-triebwork7", "3.0-triebwork11"]

    services:
      # Our own database where we store tenants and config
      eci_db:
        image: postgres
        ports:
          # Must be exposed on the host for prisma to migrate and seed
          - 5432:5432
        env:
          POSTGRES_DB: postgres
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres

      # Saleor Graphql API
      saleor_api:
        ports:
          - 8000:8000
        image: registry.gitlab.com/trieb.work/saleor:${{matrix.saleor}}
        env:
          DATABASE_URL: postgres://saleor:saleor@saleor_db:5432/postgres
          SECRET_KEY: super-secret
      # Required by saleor
      saleor_db:
        image: postgres
        env:
          POSTGRES_USER: saleor
          POSTGRES_PASSWORD: saleor

    env:
      DATABASE_URL: postgres://postgres:postgres@localhost:5432/postgres

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
      - uses: actions/cache@v2
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - name: Install dependencies
        run: yarn install

        # In this step, this action saves a list of existing images,
        # the cache is created without them in the post run.
        # It also restores the cache if it exists.
      - uses: satackey/action-docker-layer-caching@v0.0.11
        # Ignore the failure of a step and avoid terminating the job.
        continue-on-error: true

      - name: Build eci container
        run: docker build -t eci:latest -f=././apps/e2e/src/Dockerfile .

      - name: Start eci server
        run: docker run -d -p "3000:3000" --network "${{ job.services.network }}"  --name eci eci:latest

      - name: Apply database schema
        run: yarn prisma migrate deploy --schema=./libs/data-access/prisma/schema.prisma

      - name: Seed database
        run: yarn prisma db seed --preview-feature --schema=./libs/data-access/prisma/schema.prisma
        env:
          SALEOR_TEMPORARY_APP_TOKEN: abc
      - name: Test (e2e)
        run: yarn nx run e2e:e2e
        env:
          ECI_BASE_URL: http://localhost:3000
